- app/src/utils/RedirectionUtils.js
- app/src/views/features/sessions/SessionsIndexPageContainer/NetworkSessions/NetworkSessionViewer/NetworkSessionViewer.tsx
> fix: desktop sessions redirects

- app/src/features/settings/components/Profile/ManageTeams/TeamsList/index.js
> RQ-1289: Remove active/Inactive status from workspaces table

- app/src/components/authentication/AuthForm/AuthForm.css
- app/src/components/authentication/AuthForm/AuthFormHero.js
- app/src/componentsV2/banners/PlanExpiredBanner/index.scss
- app/src/componentsV2/banners/PlanExpiredBanner/index.tsx
- app/src/features/onboarding/index.ts
- app/src/features/pricing/components/CompaniesSection/index.scss
- app/src/features/pricing/components/PricingModal/components/FooterBanner/index.scss
- app/src/features/pricing/components/PricingModal/components/FooterBanner/index.tsx
- app/src/features/pricing/components/PricingModal/index.scss
- app/src/features/pricing/components/PricingModal/index.tsx
- app/src/layouts/DashboardLayout/MenuHeader/HeaderUser.jsx
- app/src/layouts/DashboardLayout/MenuHeader/MenuHeader.css
- app/src/layouts/DashboardLayout/MenuHeader/PlanExpiredBadge/index.scss
- app/src/layouts/DashboardLayout/MenuHeader/PlanExpiredBadge/index.tsx
- app/src/layouts/DashboardLayout/MenuHeader/index.js
- app/src/layouts/DashboardLayout/index.jsx
- app/src/modules/analytics/events/misc/constants.js
- app/src/modules/analytics/events/misc/monetizationExperiment.js
- app/src/store/features/userActions.js
- app/src/store/initial-state/index.js
- app/src/store/selectors.js
> [RQ-1278]: Paywall intensity monetization experiment

- app/src/features/settings/components/BillingTeam/components/UserPlanDetails/index.tsx
> chore: fix plan end date for appsumo subscription

- app/src/components/landing/Appsumo/Appsumo.tsx
- app/src/hooks/DbListenerInit/availableTeamsListener.js
> RQ-1301: Add new codes to existing appsumo workspace

- app/src/features/settings/analytics/index.ts
- app/src/features/settings/components/BillingTeam/components/MyBillingTeam/index.tsx
- app/src/features/settings/components/OrgMembers/index.tsx
- app/src/features/settings/components/OrgMembersTable/index.tsx
> RQ-1306: add source to members_not_found event in billing team and members tab

- app/package-lock.json
- app/package.json
- app/src/components/authentication/AuthForm/actions/index.js
- app/src/hooks/AuthHandler.js
> Added Formbricks 

- app/src/features/settings/components/BillingTeam/index.tsx
> chore: fix fetch other billing teams

- app/src/hooks/AuthHandler.js
> Fixed Formbricks logout issue

- app/src/features/settings/components/SettingsIndex/index.scss
> fix: sidebar overflow on too many billing teams

- browser-extension/mv2/src/client/js/requestResponseRuleHandler.js
- browser-extension/mv2/src/client/js/scriptRuleHandler.js
- browser-extension/mv2/src/client/js/sessionRecorder.js
- browser-extension/mv2/src/client/js/utils.js
- browser-extension/mv2/tests/helpers/mockClientUtils.js
- browser-extension/mv2/tests/specs/client/scriptRuleHandler.spec.js
> chore: extend common utility functions to support attributes for scripts

- app/src/components/features/rules/RuleBuilder/actions/index.js
- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/ActionHeader.js
- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/FixedRequestLogPane.css
- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/NetworkTable/NoTrafficCTA.jsx
- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/NetworkTable/index.tsx
- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/index.tsx
- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/Tables/GroupByNone.js
- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/TrafficTableV2.css
- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.js
- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/utils/index.ts
- app/src/modules/analytics/events/features/constants.js
- app/src/modules/analytics/events/features/sessionRecording/mockResponseFromSession.ts
- app/src/modules/analytics/events/features/sessionRecording/networkSessions.ts
- app/src/utils/RedirectionUtils.js
- app/src/views/features/sessions/SessionsIndexPageContainer/NetworkSessions/NetworkSessionViewer/NetworkSessionViewer.tsx
> [RQ-1286] mock responses from network traffic

- app/src/features/settings/components/BillingTeam/index.tsx
> chore:fix billing team view for other teams

- browser-extension/mv2/package-lock.json
- install.sh
- package-lock.json
- package.json
Reverts requestly/requestly#1407
> Revert "add patch-package to install script"

- app/src/features/settings/components/BillingTeam/components/MyBillingTeam/components/CancelPlanModal/index.tsx
- app/src/features/settings/components/BillingTeam/components/MyBillingTeam/components/TeamPlanDetails/components/TeamPlanActionButtons/index.tsx
- app/src/features/settings/components/BillingTeam/components/MyBillingTeam/components/TeamPlanDetails/index.tsx
- app/src/features/settings/components/BillingTeam/components/OtherBillingTeam/index.tsx
> fix: billing team view when no subscription is set

- app/src/components/Home/components/Templates/index.scss
- app/src/components/Home/components/Templates/index.tsx
- app/src/components/landing/ruleTemplates/templates.json
> RQ-1309 Fix: scroll issue for desktop users in templates section

- app/src/components/Home/components/Templates/index.tsx
- app/src/components/landing/ruleTemplates/templates.json
> RQ-1309: Fix homepage template section scrolling

- app/src/features/settings/components/BillingTeam/index.tsx
> chore: fix blank owner details in billing team

- app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/CustomScriptRow/index.js
Fixes:
- too many re-renders?
- correction in pop up message on source change
Closes issue:
> fix: insert script editor

- app/src/utils/StorageServiceWrapper.js
> chore: track promise for remove in storage helper

- app/src/utils/StorageServiceWrapper.js
* chore: track promise of removing record
* fix callback invocation
---------
Closes issue:
> chore: track promise for remove in storage helper (#1422)

- app/src/features/settings/analytics/constants.ts
- app/src/features/settings/analytics/index.ts
- app/src/features/settings/components/BillingTeam/components/UserPlanDetails/index.scss
- app/src/features/settings/components/BillingTeam/components/UserPlanDetails/index.tsx
- app/src/features/settings/components/Profile/ManageTeams/TeamViewer/BillingDetails/InvoiceTable/InvoiceTable.css
- app/src/features/settings/components/Profile/ManageTeams/TeamViewer/BillingDetails/InvoiceTable/index.js
- app/src/features/settings/components/Profile/PersonalSubscription/PersonalSubscription.js
- app/src/modules/analytics/events/misc/constants.js
- app/src/modules/analytics/events/misc/subscriptions.ts
> RQ-1315: Add touchpoint to download invoices for personal subscription

- app/src/features/settings/components/SettingsIndex/index.tsx
> fix: blank screen in /settings path

- app/src/actions/TeamWorkspaceActions.js
- app/src/features/settings/components/Profile/ManageTeams/TeamViewer/TeamSettings/index.js
- app/src/hooks/ActiveWorkspace.js
- app/src/hooks/DbListenerInit/DBListeners.js
- app/src/hooks/DbListenerInit/syncingNodeListener.ts
- app/src/layouts/DashboardLayout/MenuHeader/WorkspaceSelector/index.jsx
- app/src/utils/StorageServiceWrapper.js
- app/src/utils/syncing/syncDataUtils.js
Reverts requestly/requestly#1415
> Revert "fix: await pending transactions before changing workspace details"

- app/src/features/settings/components/BillingTeam/components/UserPlanDetails/index.tsx
- app/src/layouts/DashboardLayout/MenuHeader/index.js
> chore: fix reading null status value

- app/src/hooks/useGrowthbookIntegration.ts
> fix: paywall visibility experiment initialization

- app/src/features/settings/components/BillingTeam/components/BillingTeamsSidebar/index.tsx
- app/src/features/settings/components/BillingTeam/index.tsx
> RQ-1325: Add plan details option in billing team sidebar for individual subscriptions

- app/src/componentsV2/AppNotificationBanner/appNotificationBanner.scss
- app/src/componentsV2/AppNotificationBanner/index.tsx
> add warning theme to app banner

- app/src/components/sections/Footer/index.tsx
- app/src/config/constants/sub/links.js
> Updated Footer links and added new options

- app/src/features/rules/components/RulesList/components/RulesListIndex/RulesIndexViewWrapper.tsx
- app/src/features/rules/components/RulesList/components/RulesListIndex/RulesListIndex.tsx
- app/src/features/rules/components/RulesList/components/RulesTable/hooks/useRuleTableColumns.tsx
> Fix new rules table

- browser-extension/mv2/_locales/en/messages.json
- browser-extension/mv3/_locales/en/messages.json
> [RQ-1339] chore: update extension title and description

- app/src/features/onboarding/components/persona/components/personaScreen/index.tsx
- app/src/features/onboarding/components/teams/components/joinTeamsView/index.tsx
> chore: fix persona updated event

- app/src/features/settings/components/Profile/ManageTeams/TeamViewer/MembersDetails/AddMemberModal/index.jsx
> chore: fix invite members modal loading state

- app/src/components/landing/pricing/ComparisonTable/v2-free-enterprise/EnterpriseBanner.tsx
- app/src/lib/design-system/custom/base.css
> fix: enterprise plan style

- app/src/components/features/rules/RuleBuilder/Header/ActionButtons/CreateRuleButton/index.js
- app/src/modules/analytics/events/common/rules/index.js
> add save_type property in rule saved event

- app/src/components/authentication/AuthForm/AuthFormHero.js
- app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/index.tsx
- app/src/features/onboarding/components/auth/components/Banner/index.scss
- app/src/features/onboarding/components/auth/components/Banner/index.tsx
- app/src/features/pricing/components/PremiumFeature/index.scss
- app/src/features/pricing/components/PremiumFeature/index.tsx
- app/src/layouts/DashboardLayout/MenuHeader/HeaderUser.jsx
- app/src/layouts/DashboardLayout/MenuHeader/MenuHeader.css
> RQ-1344: No CC required experiment

- app/src/features/pricing/components/PricingModal/index.tsx
- app/src/features/pricing/components/PricingTable/components/PlanColumn/index.tsx
> fix: pricing modal overflow

- app/src/features/pricing/components/PricingModal/index.tsx
- app/src/features/pricing/components/PricingTable/PricingTableButtons.tsx
- app/src/features/pricing/components/PricingTable/components/PlanColumn/index.tsx
- app/src/features/pricing/components/PricingTable/index.tsx
- app/src/features/pricing/components/PricingTable/types.ts
- app/src/features/pricing/constants/pricingFeatures.ts
> pricing modal enterprise plan column changes

- app/src/features/pricing/components/PremiumFeature/index.tsx
- app/src/hooks/useGrowthbookIntegration.ts
> chore: remove paywall visibility experiment flag

- app/src/components/features/rules/RulesIndexPage/index.js
- app/src/config/constants/sub/analytics.js
- app/src/features/rules/components/RulesList/components/RulesListIndex/hooks/useFetchAndUpdateRules.tsx
- app/src/features/rules/constants/index.ts
- app/src/hooks/AuthHandler.js
> RQ-1355: seed user properties

- browser-extension/mv3/src/client-scripts/ajaxRequestInterceptor.js
> fix: response rule status code in MV3

- app/src/components/features/rules/RuleBuilder/Header/ActionButtons/CreateRuleButton/actions/index.js
- app/src/components/features/rules/RuleBuilder/Header/ActionButtons/CreateRuleButton/actions/insertScriptValidators.js
- app/src/components/features/rules/RuleBuilder/Header/ActionButtons/CreateRuleButton/index.js
- app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/CustomScriptRow/index.js
- app/src/components/misc/CodeEditor/CodeEditor.js
- copy fixes in warning messages
- editor toast id should be script.id not pair.id
Closes issue:
> minor fixes in insert script enhancements

- app/src/componentsV2/banners/PlanExpiredBanner/index.tsx
> chore: fix plan name in plan expired banner

- app/src/features/settings/components/Profile/ManageTeams/TeamViewer/MembersDetails/AddMemberModal/index.jsx
> Fix: invite modal toggle for other workspaces when user is in private workspace

- app/src/features/onboarding/components/onboardingView/index.tsx
- app/src/layouts/DashboardLayout/DashboardContent.js
> RQ-1390: rollout new onboarding

- .all-contributorsrc
- README.md
- app/package.json
- app/src/components/Home/components/HelpCard/index.tsx
- app/src/components/authentication/AuthForm/index.js
- app/src/components/features/mobileDebugger/Layout/MobileDebuggerLayout.tsx
- app/src/components/features/mocksV2/MockList/GettingStartedWithMocks/index.tsx
- app/src/components/features/rules/CreateTeamRuleCTA/index.js
- app/src/components/features/rules/NewRuleSelector/Examples/index.js
- app/src/components/landing/ruleSelection/rules-data.tsx
- app/src/components/mode-specific/desktop/UpdateDialog/BreakingDialog.js
- app/src/config/constants/sub/links.js
- app/src/features/onboarding/components/auth/components/Form/index.tsx
- app/src/features/rules/components/RulesList/components/RulesListIndex/components/GettingStarted/CreateTeamRuleCTA/index.js
- app/src/features/rules/components/RulesList/components/RulesListIndex/components/NewRuleSelector/Examples/index.js
- app/src/features/settings/components/DesktopSettings/index.jsx
- app/src/views/features/Updates/changeLogs.ts
- browser-extension/common/package.json
- browser-extension/config/package.json
- browser-extension/mv2/package.json
- browser-extension/mv3/package.json
- common/rule-processor/package.json
- ee/LICENSE
- package.json
> Updated Backlinks

- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/ActionHeader.js
- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.js
- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/index.js
> [RQ-1374] Fix: filter doesn't get cleared when navigated from Network Traffic to View Session

- app/src/features/pricing/components/PricingTable/PricingTableButtons.tsx
> RQ-1400: Allow unverified emails to checkout

- app/src/actions/TeamWorkspaceActions.js
- app/src/components/user/DeleteConfirmationModal/index.js
- app/src/features/rules/components/RulesList/components/RulesTable/utils/rules.ts
- app/src/features/settings/components/Profile/ManageTeams/TeamViewer/TeamSettings/WorkspaceStatusSyncing/index.js
- app/src/hooks/DbListenerInit/syncingNodeListener.ts
- app/src/utils/StorageServiceWrapper.js
> fix: storage deletion operations + syncing delays

- app/src/components/mode-specific/desktop/DesktopFilePicker/index.scss
- app/src/components/mode-specific/desktop/DesktopFilePicker/index.tsx
> RQ-1411: Fix mock and file server empty state screen

- app/src/actions/FirebaseActions.js
- app/src/modules/analytics/events/common/constants.js
> chore: add missing source in auth events

- app/src/components/authentication/DesktopSignIn/DesktopSignIn.js
> fix: sign up events fired when authenticated with google in desktop app

- app/src/components/features/rules/RuleBuilder/Header/ActionButtons/actions/index.js
> chore: increase timeout threshold while saving record

- app/src/actions/FirebaseActions.js
- app/src/components/authentication/AuthForm/MagicAuthLinkModal/MagicLinkModalContent.jsx
- app/src/components/misc/SignInViaEmailLink/SignInViaEmailLink.js
> RQ-1435: fix magic link auth events

- app/package-lock.json
- app/package.json
> chore: bump @formbricks/js version to 1.7.1

- app/src/modules/analytics/events/features/sessionRecording/mockResponseFromSession.ts
- app/src/views/features/sessions/SessionsIndexPageContainer/NetworkSessions/NetworkSessionViewer/CreateMocksModeBanner.tsx
> [ENGG-1379] fix: graphql events in mock responses

- app/src/features/onboarding/components/auth/components/Banner/index.tsx
- app/src/features/pricing/components/PremiumFeature/index.tsx
- app/src/features/settings/components/BillingTeam/components/UserPlanDetails/index.tsx
- app/src/hooks/useGrowthbookIntegration.ts
- app/src/layouts/DashboardLayout/MenuHeader/HeaderUser.jsx
> RQ-1371: trial days experiment

- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/LogFilter.tsx
- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/utils/index.ts
> [ENGG-1452] feat: mock responses select all graphQL payload keys using asterisk

- app/src/components/features/rules/RulesListContainer/index.js
- app/src/components/misc/CommandBar/config.tsx
- app/src/features/rules/components/RulesList/components/RulesListIndex/RulesListIndex.tsx
- app/src/utils/AuthUtils.js
> fix: old sign in nudge checks for new rule creation

- app/src/components/authentication/AuthModal/index.js
- app/src/components/features/rules/RuleBuilder/Header/ActionButtons/ShareRuleButton/index.jsx
- app/src/features/pricing/components/PremiumFeature/index.tsx
- app/src/layouts/DashboardLayout/Sidebar/PrimarySidebar/InviteButton.tsx
- app/src/modules/analytics/events/common/constants.js
> chore: fix auth modal missing source

- browser-extension/common/src/rulesStore.ts
> [ENGG-1413] fix: rule without status field should be treated disabled

- app/src/components/features/rules/RuleBuilder/Header/ActionButtons/CreateRuleButton/index.jsx
> ENGG-1475: Fix upgrade popover shows up when editing a rule with premium plan

- app/package-lock.json
- app/package.json
> Fix: Downgrade @formbricks/js

- app/src/layouts/DashboardLayout/MenuHeader/HeaderUser.jsx
- app/src/utils/RedirectionUtils.js
> [ENGG-1477]: add plans and billings option in profile dropdown

- app/src/layouts/DashboardLayout/MenuHeader/index.js
> fix: desktop app header overflow

- browser-extension/common/src/types.ts
- browser-extension/mv3/src/service-worker/services/utils.ts
> [ENGG-1366] MV3 fix: types

- app/src/features/settings/components/BillingTeam/components/RequestTeamAccess/components/Reminder/index.tsx
> fix: join billing reminder modal visibility

- app/src/features/rules/index.ts
> chore: fix import in compression.js

- app/src/features/onboarding/components/auth/components/Form/index.tsx
> chore: show sso touchpoint in sign up screen

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature-request.md
> Update GitHub issue templates

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/feature-request.yml
> chore: updated github templates

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/feature-request.yml
> chore: updated template

- app/src/features/rules/screens/rulesList/components/RulesList/components/RulesTable/hooks/useRuleTableColumns.tsx
- app/src/features/rules/screens/rulesList/components/RulesList/components/RulesTable/rulesTable.css
> [ENGG-1483] fix: show rule description

- app/src/components/authentication/AuthModal/index.js
> ENGG-1564 : fix missing auth_modal_shown event

- app/package-lock.json
- app/src/utils/Compression.js
store should have the right state for pair.isCompressed to avoid unexpected conflicts while saving
Closes issue:
> fix: maintain the right state for pair.isCompressed

- app/src/features/rules/screens/rulesList/components/RulesList/components/RulesTable/hooks/useRuleTableColumns.tsx
- app/src/features/rules/screens/rulesList/components/RulesList/components/RulesTable/rulesTable.css
> [ENGG-1480]: show active rules count in group

- app/src/layouts/DashboardLayout/MenuHeader/ProductsDropDown.tsx
- app/src/layouts/DashboardLayout/Sidebar/PrimarySidebar/index.tsx
> [ENGG-1473]: Added Beta Label to SessionBook

- app/src/lib/design-system-v2/helpers/theme.css
- app/src/lib/design-system-v2/tokens/colors.ts
> chore: updated color tokens

- app/src/componentsV2/ContentList/components/ContentListHeader/contentListHeader.scss
> [ENGG-1549] fix(style): rules table search input

- app/src/views/features/api-client/client-view/apiClientView.scss
> [ENGG-1547] fix(style): api client url input 

- app/src/components/misc/ExtensionInstalled/index.tsx
- app/src/layouts/DashboardLayout/DashboardContent.js
> [ENGG-1583] chore: setup experiment `activation without onboarding`

- app/src/componentsV2/ContentList/components/ContentListHeader/ContentListHeader.tsx
- app/src/componentsV2/ContentList/components/ContentListHeader/contentListHeader.scss
- app/src/componentsV2/ContentList/components/ContentListTable/ContentListTable.tsx
- app/src/componentsV2/ContentList/components/ContentListTable/components/BulkActionBar/BulkActionBar.tsx
- app/src/componentsV2/ContentList/components/ContentListTable/components/BulkActionBar/bulkActionBar.scss
- app/src/componentsV2/ContentList/components/ContentListTable/contentListTable.scss
- app/src/features/rules/container.scss
- app/src/features/rules/container.tsx
- app/src/features/rules/screens/rulesList/components/RulesList/RulesList.tsx
- app/src/features/rules/screens/rulesList/components/RulesList/components/RulesTable/rulesTable.css
- app/src/features/rules/screens/rulesList/components/RulesList/rulesList.scss
- app/src/lib/design-system-v2/helpers/theme.css
- app/src/lib/design-system-v2/tokens/colors.ts
> [ENGG-1592] chore: use color token in rules table

- app/src/features/settings/components/BillingTeam/components/BillingDetails/MyBillingTeamDetails/components/BillingTeamMembers/index.tsx
- app/src/features/settings/components/BillingTeam/components/BillingDetails/MyBillingTeamDetails/components/BillingTeamMembers/types.ts
- app/src/features/settings/components/BillingTeam/components/BillingDetails/MyBillingTeamDetails/components/BillingTeamMembers/utils.ts
> ENGG-1479: Move option to `remove` inside three dots

- app/src/hooks/AuthHandler.js
- app/src/hooks/PreLoadRemover.js
- common/logger.js
> [ENGG-1514] chore: added logs in authHandler

- app/src/utils/StorageServiceWrapper.js
> [ENGG-1601] fix: error in creating rule

- app/src/componentsV2/ContentList/components/ContentListTable/components/BulkActionBar/BulkActionBar.tsx
- app/src/features/rules/screens/rulesList/components/RulesList/components/RulesTable/RulesTable.tsx
https://github.com/requestly/requestly/assets/61556757/6638f6be-cf50-4110-99d0-105ce2ccfb00
> [ENGG-1604] fix: loader for bulk records toggle option

- app/src/componentsV2/AppNotificationBanner/index.tsx
> fix: commercial license visibility

- app/src/features/settings/components/Profile/ManageTeams/TeamViewer/TeamSettings/WorkspaceStatusSyncing/index.js
- app/src/hooks/ActiveWorkspace.js
- app/src/hooks/DbListenerInit/syncingNodeListener.ts
fixes the intermitent issue introduced by https://github.com/requestly/requestly/pull/1534
> fix: decompress records from the other triggers of syncing that were missed

- app/src/features/settings/components/Profile/ManageTeams/TeamViewer/TeamSettings/WorkspaceStatusSyncing/index.js
- app/src/hooks/ActiveWorkspace.js
- app/src/hooks/DbListenerInit/syncingNodeListener.ts
Reverts requestly/requestly#1598
> Revert "fix: decompress records from the other triggers of syncing that were missed"

- app/src/features/settings/components/Profile/ManageTeams/TeamViewer/TeamSettings/WorkspaceStatusSyncing/index.js
- app/src/hooks/ActiveWorkspace.js
- app/src/hooks/DbListenerInit/syncingNodeListener.ts
- app/src/utils/Compression.js
Reverts requestly/requestly#1599
i.e. brings back https://github.com/requestly/requestly/pull/1598
> Revert "Revert "fix: decompress records from the other triggers of syncing that were missed""

- app/src/layouts/DashboardLayout/MenuHeader/ProductsDropDown.scss
- app/src/layouts/DashboardLayout/MenuHeader/ProductsDropDown.tsx
> [ENGG-1532] Updated Product Dropdown

- app/src/components/features/rules/RuleBuilder/Help/Help.css
- app/src/components/features/rules/RuleBuilder/Help/index.tsx
- app/src/views/features/rules/RuleEditor/components/Header/ActionButtons/HelpButton/index.scss
- app/src/views/features/rules/RuleEditor/components/Header/ActionButtons/HelpButton/index.tsx
- app/src/views/features/rules/RuleEditor/components/Header/index.js
> ENGG-1533: Add help sidebar as overlay in rule editor

- app/src/views/features/rules/RuleEditor/RuleEditor.js
> fix: open test rule panel not opening on rule creation

- app/src/components/features/rules/RuleBuilder/Body/index.js
> revert: editor width changes

- app/src/views/features/rules/RuleEditor/RuleEditor.js
> fix: test rule overlay toggle on rule creation

- app/src/components/features/mocksV2/MockEditorIndex/Editor/index.css
- app/src/components/features/mocksV2/MockEditorIndex/Editor/index.tsx
> fix: mock editor header style

- app/src/features/mocks/analytics/constants.ts
- app/src/features/mocks/analytics/index.ts
- app/src/features/mocks/modals/MockPickerModal/MockPickerIndex.tsx
- app/src/features/mocks/screens/mocksList/components/MocksList/MocksList.tsx
- app/src/features/mocks/screens/mocksList/components/MocksList/components/GettingStarted/GettingStarted.tsx
- app/src/features/mocks/screens/mocksList/components/MocksList/components/GettingStarted/GettingStartedWithMocks/GettingStartedWithMocks.tsx
- app/src/features/mocks/screens/mocksList/components/MocksList/components/GettingStarted/GettingStartedWithMocks/gettingStartedWithMocks.scss
- app/src/features/mocks/screens/mocksList/components/MocksList/components/index.ts
- app/src/features/mocks/screens/mocksList/components/MocksList/hooks/useFetchMocks.ts
- app/src/modules/analytics/events/features/constants.js
- app/src/modules/analytics/events/features/mockServer/files/index.js
- app/src/modules/analytics/events/features/mockServer/mocks/index.js
> [ENGG-1628]: cleanup, refactor actions and analytics

- app/src/backend/billing/index.ts
- app/src/backend/billing/requestTeamAccess.ts
- app/src/backend/billing/reviewJoinRequest.ts
- app/src/features/settings/components/BillingTeam/components/BillingDetails/OtherBillingTeamDetails/index.tsx
- app/src/features/settings/components/BillingTeam/components/BillingDetails/index.tsx
- app/src/features/settings/components/BillingTeam/components/BillingDetails/modals/RequestBillingTeamAccessModal/RequestBillingTeamAccessModal.tsx
- app/src/features/settings/components/BillingTeam/components/BillingDetails/modals/ReviewJoinRequestModal/ReviewJoinRequestModal.scss
- app/src/features/settings/components/BillingTeam/components/BillingDetails/modals/ReviewJoinRequestModal/ReviewJoinRequestModal.tsx
- app/src/features/settings/components/BillingTeam/components/BillingDetails/modals/common/BillingTeamActionModal/BillingTeamActionModal.scss
- app/src/features/settings/components/BillingTeam/components/BillingDetails/modals/common/BillingTeamActionModal/BillingTeamActionModal.tsx
- app/src/features/settings/components/BillingTeam/components/BillingDetails/types.ts
> ENGG-1593: In-app billing team review/request flow improvement 

- app/src/features/settings/components/BillingTeam/components/BillingDetails/modals/ReviewJoinRequestModal/ReviewJoinRequestModal.tsx
> chore: fix request modal typo

- app/src/features/mocks/screens/mocksList/components/MocksList/MocksList.tsx
- app/src/features/mocks/screens/mocksList/components/MocksList/components/GettingStarted/GettingStarted.tsx
> fix: mocks upload modal

- app/src/features/mocks/screens/mocksList/components/MocksList/hooks/useFetchMocks.ts
> fix: mocks listing

- app/src/features/rules/screens/rulesList/components/RulesList/components/RulesTable/hooks/useRuleTableColumns.tsx
> ENGG-1649: show tooltip on rules status switch whose groups are disabled

- app/src/components/features/rules/TestThisRule/hooks/InitImplicitWidgetConfigHandler.ts
- app/src/features/settings/components/GlobalSettings/components/ImplicitRuleTesting/components/RuleTypesOptions/index.tsx
- app/src/features/settings/components/GlobalSettings/components/ImplicitRuleTesting/index.tsx
- app/src/features/settings/components/GlobalSettings/components/ImplicitRuleTesting/types.ts
- browser-extension/mv2/src/client/js/ruleExecutionHandler.js
- common/constants.js
> ENGG-1534: Implicit test this rule widget config fix

- app/src/hooks/useGoogleOneTapLogin.ts
- app/src/modules/analytics/events/common/auth/oneTapPrompt/index.ts
- app/src/modules/analytics/events/common/constants.js
> chore: migrate to federated onetap

- app/src/actions/FirebaseActions.js
- app/src/backend/auth/sso.ts
- app/src/components/authentication/AuthForm/index.js
- app/src/features/onboarding/components/auth/components/Form/components/SSOSignInForm/index.tsx
> feat: SSO support

- browser-extension/common/src/constants.ts
- browser-extension/mv3/src/content-scripts/app/messageHandler.ts
- browser-extension/mv3/src/service-worker/services/apiClient.ts
- browser-extension/mv3/src/service-worker/services/messageHandler.ts
> [ENGG-1656] feat MV3: API client

- browser-extension/mv3/src/service-worker/services/tabService.ts
> [ENGG-1625] fix: MV3 client page loaded event

- app/src/views/features/rules/RuleEditor/components/Header/ActionButtons/CreateRuleButton/index.jsx
> chore: remove rule info dialog from response rule editor

- app/src/features/settings/components/Profile/ManageTeams/TeamViewer/MembersDetails/TeamMembersTable/index.js
- app/src/features/settings/components/Profile/ManageTeams/TeamViewer/common/MemberRoleDropdown/index.tsx
> ENGG-1608: Replace the role of owner in a workspace with admin

- app/src/features/rules/screens/rulesList/components/RulesList/RulesList.tsx
- app/src/features/rules/screens/rulesList/components/RulesList/components/RulesTable/RulesTable.tsx
> ENGG-1676: send individual rule types attributes from new rules table

- app/src/backend/mocks/createMock.ts
- app/src/components/features/mocksV2/MockEditorIndex/MockEditorIndex.tsx
- app/src/features/mocks/modals/CreateCollectionModal/index.tsx
- app/src/features/mocks/modals/DeleteCollectionModal/index.tsx
- app/src/features/mocks/modals/UpdateMockCollectionModal/index.tsx
- app/src/features/mocks/screens/mocksList/components/MocksList/MocksList.tsx
- app/src/modules/analytics/events/features/constants.js
- app/src/modules/analytics/events/features/mocksV2/index.ts
> [ENGG-1680] chore: update analytics

- app/src/components/features/mocksV2/MockEditorIndex/Editor/index.tsx
- app/src/components/features/mocksV2/MockEditorIndex/MockEditorIndex.tsx
- app/src/features/mocks/modals/MockPickerModal/MockPickerIndex.tsx
- app/src/features/mocks/modals/MockPickerModal/mockPickerModal.scss
- app/src/lib/design-system/components/RQEditorTitle/RQEditorTitle.css
- app/src/lib/design-system/components/RQEditorTitle/index.tsx
> fix: mock editor layout in modal

- app/src/componentsV2/AppNotificationBanner/index.tsx
- app/src/componentsV2/ContentList/components/ContentListTable/ContentListTable.tsx
- app/src/componentsV2/banners/PlanExpiredBanner/index.scss
- app/src/componentsV2/banners/PlanExpiredBanner/index.tsx
- app/src/features/mocks/screens/mocksList/components/MocksList/components/MocksTable/MocksTable.tsx
- app/src/features/rules/screens/rulesList/components/RulesList/components/RulesTable/RulesTable.tsx
- app/src/features/rules/screens/sharedLists/components/SharedLists/components/SharedListsTable/SharedListsTable.tsx
- app/src/features/rules/screens/templatesList/components/TemplatesTable/TemplatesTable.tsx
- app/src/layouts/DashboardLayout/DashboardLayout.css
- app/src/layouts/DashboardLayout/index.jsx
- app/src/modules/analytics/events/common/constants.js
- app/src/store/features/userActions.js
- app/src/store/initial-state/index.js
- app/src/store/selectors.js
> ENGG-1638 fix: app layout breaks when app banner is visible

- app/src/features/rules/screens/rulesList/components/RulesList/RulesList.tsx
Reverts requestly/requestly#1645
> Revert "ENGG-1676: send individual rule types attributes from new rules table"

- app/src/features/rules/screens/rulesList/components/RulesList/hooks/useFetchAndUpdateRules.tsx
Debugging effort since https://github.com/requestly/requestly/pull/1659 did not fix the issue
> chore: add debug logs

- app/src/features/rules/screens/sharedLists/components/SharedLists/components/SharedListsTable/hooks/useSharedListsTableColumns.tsx
> fix: shared list table creation date and import count

- app/src/features/rules/analytics/constants.ts
- app/src/features/rules/analytics/index.ts
- app/src/features/rules/screens/rulesList/components/RulesList/hooks/useFetchAndUpdateRules.tsx
> Chore: add rules list loaded event

- app/src/actions/FirebaseActions.js
- app/src/features/onboarding/components/auth/components/Form/components/SSOSignInForm/index.tsx
> chore: added events in sso login

- browser-extension/mv2/src/client/js/requestResponseRuleHandler.js
> [ENGG-1588] feat: async support in response rule - XHR requests

- app/src/backend/billing/hooks/useBillingTeamsListener.ts
> ENGG-1707: fix members with different domain not able to view billing team

- app/src/features/settings/components/BillingTeam/components/BillingDetails/MyBillingTeamDetails/components/AddMembersDrawer/components/InviteMembersForm/components/PostUserAdditionView/PostUserAdditionView.tsx
> ENGG-1716: fix warning message visible when adding external domain users

- browser-extension/mv3/src/service-worker/services/messageHandler.ts
> [ENGG-1698] fix: implicit test rule

- app/package.json
- app/src/modules/analytics/events/migrations.ts
- app/src/modules/extension/utils.ts
> [ENGG-1567] chore: add extra event properties for migration

- app/src/features/rules/modals/MV3MigrationModal/MigrationModal/modal.scss
> [ENG-1567] fix: migration modal ui

- app/src/features/rules/modals/MV3MigrationModal/NotificationCard/card.scss
> [ENGG-1567] fix: notification card z-index

- app/src/components/features/rules/TestThisRule/hooks/InitImplicitWidgetConfigHandler.ts
- app/src/features/settings/components/GlobalSettings/components/ImplicitRuleTesting/index.tsx
> chore: remove implicit test rule feature flag

- app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/RequestSourceRow/index.js
- app/src/modules/extension/mv3RuleParser/parseRedirectRule.ts
> [ENGG-1779] fix: MV3 wildcard substitution

- browser-extension/mv2/src/external/tabService.js
- browser-extension/mv3/src/service-worker/services/tabService.ts
> [ENGG-1780] fix: session not saving for explicit test rule (new tab)

- app/src/modules/extension/mv3RuleParser/parseQueryParamRule.ts
> [ENGG-1578] fix: remove all in query params rule

- browser-extension/mv3/src/service-worker/services/webRequestInterceptor.ts
> [ENGG-1782] fix: extension icon not turning green for main_frame headers rule

- app/src/components/common/SourceUrl/index.tsx
- app/src/features/rules/modals/MV3MigrationModal/NotificationCard/index.jsx
> [ENGG-1781] fix: migration notification and path operator in test URL condition

- browser-extension/mv3/src/service-worker/services/utils.ts
> [ENGG-1784] fix: added onload listener for script rule

- browser-extension/mv2/src/background/ExtensionIconManager.js
- browser-extension/mv3/src/service-worker/services/extensionIconManager.ts
- browser-extension/mv3/src/service-worker/services/utils.ts
> [ENGG-1792] fix: extension icon state

- browser-extension/mv3/src/service-worker/services/sessionRecording.ts
> [ENGG-1797] fix: manual session replay stitching

- app/src/features/mocks/modals/CreateOrUpdateCollectionModalWrapper/CreateOrUpdateCollectionModal/createOrUpdateCollectionModal.scss
- app/src/features/mocks/modals/CreateOrUpdateCollectionModalWrapper/CreateOrUpdateCollectionModal/index.tsx
- app/src/features/mocks/modals/UpdateMocksCollectionModalWrapper/UpdateMocksCollectionModal/index.tsx
- app/src/features/mocks/modals/UpdateMocksCollectionModalWrapper/UpdateMocksCollectionModal/updateMocksCollectionModal.scss
- app/src/features/mocks/modals/UpdateMocksCollectionModalWrapper/index.tsx
- app/src/features/mocks/screens/mocksList/components/MocksList/MocksList.tsx
- app/src/features/mocks/screens/mocksList/components/MocksList/components/MocksTable/hooks/useMocksTableColumns.tsx
- app/src/features/mocks/screens/mocksList/components/MocksList/components/MocksTable/mocksTable.scss
Changes:
- Remove icons from table header
- Fix few styles
- Create new collection from "Move mock into collection" modal
Empty state: 
https://github.com/requestly/requestly/assets/61556757/01d1c9e5-a208-4333-a543-b2dec19bb9af
If collection already exist:
https://github.com/requestly/requestly/assets/61556757/1d3ab511-ebf2-4545-978d-81655066e8e4
> [ENGG-1813] fix:  design issues in mock server

- browser-extension/mv3/rollup.config.js
- browser-extension/mv3/src/manifest.chrome.json
- browser-extension/mv3/src/utils.ts
> fix: MV3 URL patterns

- app/src/features/mocks/screens/mocksList/components/MocksList/components/MocksTable/hooks/useMocksTableColumns.tsx
> chore(fix): mock server table change collection name action argument type

- app/src/App.js
- app/src/config/constants/sub/paths.js
- app/src/hooks/appUpdateChecker/useAppUpdateChecker.tsx
- remove legacy check for handling hash paths
- window.location.replace(window.location.href) -> window.location.reload()
> fix: snyk vulnerabilites in app

- app/src/backend/mocks/updateMock.ts
- app/src/components/features/mocksV2/types.ts
- app/src/features/mocks/contexts/actions.tsx
- app/src/features/mocks/screens/mocksList/components/MocksList/components/MocksTable/hooks/useMocksTableColumns.tsx
- app/src/features/mocks/screens/mocksList/components/MocksList/components/MocksTable/mocksTable.scss
- app/src/modules/analytics/events/features/mocksV2/index.ts
https://github.com/requestly/requestly/assets/61556757/9c058705-dc5a-4f06-a352-61d92e9d9604
> [ENGG-1815] feat: star/pin mock collection row

- browser-extension/mv3/src/service-worker/services/clientHandler.ts
> fix: rules caching frame issue

- browser-extension/mv3/src/client-scripts/ajaxRequestInterceptor.js
- browser-extension/mv3/src/service-worker/services/requestProcessor/handleCSPError.ts
- browser-extension/mv3/src/service-worker/services/requestProcessor/handleInitiatorDomainFunction.ts
- browser-extension/mv3/src/service-worker/services/requestProcessor/types.ts
- browser-extension/mv3/src/service-worker/services/ruleMatcher.ts
- browser-extension/mv3/src/service-worker/services/webRequestInterceptor.ts
- browser-extension/mv3/src/utils.ts
> fix: MV3 - change initiatorDomain to initiator in AjaxRequests

- browser-extension/mv3/src/service-worker/services/installUninstall.ts
> [ENGG-1832] MV3 added open rules page on update

- browser-extension/mv3/src/client-scripts/ajaxRequestInterceptor.js
> [ENGG-1829] fix: MV3 prefix extra params on XHR with _rq

- browser-extension/mv3/_locales/en/messages.json
> update mv3 extension name

- browser-extension/mv3/src/client-scripts/ajaxRequestInterceptor.js
> fix: mv3 request rule

- app/src/features/settings/components/GlobalSettings/components/ImplicitRuleTesting/index.tsx
> fix: group not enabling issue

- common/logger.js
> fix: logger undefined error

- app/src/routes/miscRoutes.tsx
> fix: updatedToMv3 route

- browser-extension/mv2/src/client/js/requestResponseRuleHandler.js
> [ENGG-1823] fix: x.com not loading on Arc

- app/src/componentsV2/ContentList/components/ContentListHeader/contentListHeader.scss
- app/src/componentsV2/ContentList/components/ContentListTable/ContentListTable.tsx
- app/src/componentsV2/ContentList/components/ContentListTable/contentListTable.scss
- app/src/features/rules/screens/rulesList/components/RulesList/components/RulesListContentHeader/RulesListContentHeader.tsx
- app/src/features/rules/screens/rulesList/components/RulesList/components/RulesTable/RulesTable.tsx
- app/src/features/rules/screens/rulesList/components/RulesList/components/RulesTable/hooks/useRuleTableColumns.tsx
- app/src/features/rules/screens/rulesList/components/RulesList/components/RulesTable/rulesTable.css
- app/src/features/rules/screens/rulesList/components/RulesList/rulesList.scss
> ENGG-1785: Rules table style fixes

- app/src/componentsV2/ContentList/components/ContentListTable/contentListTable.scss
- app/src/features/mocks/screens/mocksList/components/MocksList/mocksList.scss
- app/src/features/rules/screens/rulesList/components/RulesList/components/RulesTable/rulesTable.css
- app/src/features/rules/screens/rulesList/components/RulesList/rulesList.scss
- app/src/features/rules/screens/sharedListViewer/components/SharedListViewerList/SharedListViewerList.tsx
- app/src/features/rules/screens/sharedListViewer/components/SharedListViewerList/sharedListViewerList.scss
- app/src/features/rules/screens/sharedLists/components/SharedLists/components/SharedListsTable/sharedListsTable.scss
- app/src/features/rules/screens/templatesList/components/TemplatesTable/templatesTable.scss
> chore: style fixes in content list table

- browser-extension/mv3/src/service-worker/services/rulesManager.ts
> [ENGG-1834] fix: session rules being deleted on rules change listener

- app/src/features/settings/components/BillingTeam/components/UserPlanDetails/index.scss
- app/src/features/settings/components/BillingTeam/components/UserPlanDetails/index.tsx
- app/src/features/settings/components/Profile/ManageTeams/TeamViewer/BillingDetails/SubscriptionActionButtons/index.js
https://github.com/requestly/requestly/assets/57226514/35b075fb-f9ba-4505-bec2-b3d7843730e9
todo: test properly
> chore: add cancel button in billing info screen

- app/src/components/misc/ProductWalkthrough/Tooltip/index.tsx
- app/src/components/misc/ProductWalkthrough/constants.ts
- app/src/components/misc/ProductWalkthrough/tours.tsx
- app/src/components/misc/ProductWalkthrough/types.ts
- app/src/layouts/DashboardLayout/Sidebar/PrimarySidebar/components/CreditsButton/CreditsButton.tsx
- app/src/layouts/DashboardLayout/Sidebar/PrimarySidebar/components/CreditsButton/creditsButton.scss
- app/src/store/initial-state/index.js
> ENGG-1801: Add tour for credits button for new users

- app/src/features/onboarding/components/auth/components/Banner/index.scss
- app/src/features/onboarding/components/auth/components/Banner/index.tsx
> ENGG-1861: Update signup modal copy

- app/src/features/pricing/components/PremiumFeature/components/RequestFeatureModal/index.tsx
- app/src/features/pricing/components/PremiumFeature/index.tsx
> ENGG-1802: Add incentive checklist modal touchpoint in upgrade popover

- app/src/features/pricing/components/PremiumFeature/components/RequestFeatureModal/index.scss
- app/src/features/pricing/components/PremiumFeature/components/RequestFeatureModal/index.tsx
- app/src/features/pricing/components/PremiumFeature/index.tsx
> chore: Fix upgrade popover CTA

- app/src/features/onboarding/components/auth/components/Banner/index.scss
- app/src/features/onboarding/components/auth/components/Banner/index.tsx
> Chore: update signup modal copy

- app/src/features/incentivization/components/CreditsProgressbar/CreditsProgessbar.tsx
> fix: progress bar percent when no credits earned

- app/src/components/Home/home.scss
> fix: homepage cards padding

- app/src/features/pricing/components/PricingTable/components/PlanColumn/index.tsx
Fixed a typo on Pricing Page
- [ x] Make sure linting and unit tests pass.
- [ x] No install/build warnings introduced.
- [x ] Verified UI in browser.
- [ x] For UI changes, added/updated analytics events (if applicable).
- [ x] For changes in extension's code, manually tested in Chrome and Firefox.
- [ x] For changes in extension's code, both MV2 and MV3 are covered.
- [ x] Added/updated unit tests for this change.
- [x ] Raised pull request to update corresponding documentation (if already exists).
> Fixed the typo on pricing page.

- app/src/components/Home/index.tsx
- app/src/components/features/mocksV2/MockEditorIndex/MockEditorIndex.tsx
- app/src/componentsV2/modals/CreateWorkspaceModal/index.jsx
- app/src/features/pricing/components/PremiumFeature/components/RequestFeatureModal/index.tsx
- app/src/features/pricing/components/PremiumFeature/index.tsx
- app/src/layouts/DashboardLayout/MenuHeader/index.js
- app/src/layouts/DashboardLayout/Sidebar/PrimarySidebar/components/CreditsButton/CreditsButton.tsx
- app/src/layouts/DashboardLayout/Sidebar/PrimarySidebar/index.tsx
- app/src/views/features/rules/RuleEditor/components/Header/ActionButtons/CreateRuleButton/index.jsx
- app/src/views/features/sessions/SessionViewer/SaveRecordingConfigPopup.tsx
> Maintain incentivization touchpoints behind feature flag

- app/src/features/incentivization/components/IncentiveSectionHeader/index.tsx
> Fix: incentive onboarding days left badge visibility

- browser-extension/common/package-lock.json
- browser-extension/common/package.json
- browser-extension/common/rollup.config.js
- browser-extension/mv3/package-lock.json
- browser-extension/mv3/package.json
- browser-extension/mv3/rollup.config.js
- browser-extension/sessionbear/package-lock.json
- browser-extension/sessionbear/package.json
- browser-extension/sessionbear/rollup.config.js
1. changed package for `terser`
2. fixed vulnerabilities in `braces`
> chore: fixed vulnerable dependencies in extension repos

- app/package-lock.json
- app/package.json
- browser-extension/mv2/package-lock.json
- browser-extension/mv2/package.json
- browser-extension/mv3/package-lock.json
- browser-extension/mv3/package.json
- browser-extension/sessionbear/package-lock.json
- browser-extension/sessionbear/package.json
- package-lock.json
> [ENGG-1883] chore: upgrade web-sdk

- app/src/features/rules/screens/sharedListViewer/SharedListViewerScreen.tsx
- app/src/features/rules/screens/sharedListViewer/hooks/useFetchSharedListData.ts
> chore: soft delete sharedlist

- app/src/features/requestBot/RequestBot.tsx
> [ENGG-1922] fix: open chat widget

- app/src/backend/incentivization/claimIncentiveRewards.ts
- app/src/backend/incentivization/index.ts
- app/src/components/features/mocksV2/MockEditorIndex/MockEditorIndex.tsx
- app/src/components/features/rules/TestThisRule/components/TestRuleHeader/index.tsx
- app/src/componentsV2/modals/CreateWorkspaceModal/index.jsx
- app/src/features/incentivization/components/CreditsProgressbar/CreditsProgessbar.tsx
- app/src/features/incentivization/components/IncentiveTasksList/IncentiveTasksList.tsx
- app/src/features/incentivization/components/IncentiveTasksList/components/TaskHeader/TaskHeader.tsx
- app/src/features/incentivization/hooks/useFetchIncentivizationDetails.ts
- app/src/features/incentivization/modals/IncentiveTaskCompletedModal/IncentiveTaskCompletedModal.tsx
- app/src/features/incentivization/modals/RedeemCreditsModal/RedeemCreditsModal.tsx
- app/src/features/incentivization/types.ts
- app/src/features/incentivization/utils/index.ts
- app/src/views/features/rules/RuleEditor/components/Header/ActionButtons/CreateRuleButton/index.jsx
- app/src/views/features/sessions/SessionViewer/SaveRecordingConfigPopup.tsx
> [ENGG-1919] fix: incentivization UI as per new backend schema 

- app/src/hooks/useIsExtensionEnabled.ts
> fix: reading extension pause state

- app/src/components/features/mocksV2/MockEditorIndex/Editor/index.css
- app/src/components/features/mocksV2/MockEditorIndex/Editor/index.tsx
- app/src/components/features/rules/RuleBuilder/Body/index.js
- app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/AddCustomScriptRow/AddCustomScriptRow.css
- app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/AddCustomScriptRow/index.js
- app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/CustomScriptRow/CustomScriptRow.css
- app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/CustomScriptRow/index.jsx
- app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/RequestBodyRow/index.js
- app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/ResponseBodyRow/ResponseBodyRow.css
- app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/ResponseBodyRow/index.js
- app/src/componentsV2/CodeEditor/components/Editor/Editor.tsx
- app/src/componentsV2/CodeEditor/components/Editor/components/Toolbar/Toolbar.tsx
- app/src/componentsV2/CodeEditor/components/Editor/components/Toolbar/toolbar.scss
- app/src/componentsV2/CodeEditor/components/Editor/editor.scss
- app/src/componentsV2/CodeEditor/components/analytics/constants.ts
- app/src/componentsV2/CodeEditor/components/analytics/index.ts
- app/src/componentsV2/CodeEditor/types/index.ts
- app/src/lib/design-system/components/RQEditorTitle/RQEditorTitle.css
- app/src/lib/design-system/components/RQEditorTitle/index.tsx
- app/src/views/features/api-client/client-view/APIClientView.tsx
- app/src/views/features/api-client/client-view/request/RequestBody.tsx
- app/src/views/features/api-client/client-view/request/requestTabs.scss
> ENGG-1740: Code editor refactor and redesign

- browser-extension/mv3/release-extension.sh
> fix: release extension script

- app/src/componentsV2/CodeEditor/components/Editor/Editor.tsx
- app/src/componentsV2/CodeEditor/components/Editor/editor.scss
Closes issue: 
Fix for : #1837
> ENGG-1951: Fix: expand/collapse feature missing in code editor

- app/src/backend/sessionRecording/saveRecording.ts
- app/src/components/features/rules/TestThisRule/TestThisRule.tsx
- app/src/views/features/sessions/SessionViewer/SaveRecordingConfigPopup.tsx
- app/src/views/features/sessions/SessionsIndexPageContainer/SessionsIndexPage/index.js
> ENGG-1941: Add test this rule metadata in sessionbook data

- app/src/features/incentivization/hooks/useFetchIncentivizationDetails.ts
- app/src/features/incentivization/hooks/useIsIncentivizationEnabled.ts
> fix: incentive check for fetching milestones

- app/src/features/incentivization/hooks/useFetchIncentivizationDetails.ts
> fix: get user incentive details

- app/src/components/misc/ExtensionInstalled/index.tsx
- app/src/features/onboarding/components/onboardingContainer/index.tsx
- app/src/layouts/DashboardLayout/DashboardContent.js
> ENGG-1929: Onboarding mandatory signup experiment

- app/src/backend/billing/hooks/useBillingTeamsListener.ts
> fix: billing team page stuck at loading

- app/index.html
- app/src/features/mocks/screens/mocksList/components/MocksList/components/MocksTable/mocksTable.scss
> fix: mocks table font

- app/src/features/settings/components/BillingTeam/components/UserPlanDetails/index.tsx
- app/src/hooks/useGrowthbookIntegration.ts
> [ENGG-1957] fix: trial duration copy

- app/src/components/features/rules/TestThisRule/TestThisRule.tsx
- app/src/components/features/rules/TestThisRule/components/TestRuleHeader/index.tsx
- app/src/components/hoc/auth/AuthConfirmationPopover/index.tsx
> ENGG-1955: allow logged out users to test rules

- app/src/config/constants/index.js
- app/src/features/settings/components/BillingTeam/components/RequestTeamAccess/components/Reminder/index.tsx
> Chore: List billing teams with past_due subscription as well in join billing team reminder modal

- app/src/features/incentivization/hooks/useIsIncentivizationEnabled.ts
> [ENGG-1973] fix: add delay to init incentivization

- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/utils/index.ts
- app/src/views/features/sessions/SessionsIndexPageContainer/NetworkSessions/NetworkSessionViewer/CreateMocksModeBanner.tsx
fixes https://github.com/requestly/requestly/issues/1858
> feat: set the status code for rules created from mock session

- app/src/features/rules/container.tsx
- app/src/modules/analytics/events/common/rules/index.js
> [ENGG-1978] chore: enrich DNR saving error

- app/src/modules/extension/mv3RuleParser/parseReplaceRule.ts
- app/src/modules/extension/mv3RuleParser/utils.ts
Closes issue: Fixes https://github.com/requestly/requestly/issues/1797 partially
> [ENGG-1981] fix: 2kb errors for non replace rules

- app/src/features/rules/container.tsx
> chore: added troubleshooting link on rule save error

- app/src/modules/extension/mv3RuleParser/parseReplaceRule.ts
> [ENGG-1980] fix: replace rule 2kb issue

- app/src/modules/extension/utils.ts
> feat: auto migrate rules using schema_version

- app/src/components/sections/Footer/Footer.css
- app/src/components/sections/Footer/index.tsx
- app/src/layouts/DashboardLayout/Sidebar/PrimarySidebar/PrimarySidebar.css
- app/src/layouts/DashboardLayout/Sidebar/Sidebar.css
- browser-extension/common/src/popup/components/Popup/index.tsx
- browser-extension/common/src/popup/components/Popup/popup.css
- browser-extension/common/src/popup/utils.ts
> ENGG-1939: Show extension version in app and extension popup footer

- browser-extension/mv3/rollup.config.js
- browser-extension/mv3/src/service-worker/services/installUninstall.ts
- browser-extension/sessionbear/rollup.config.js
> chore: disable extension-updated route and remove MV3 from version name

- app/src/components/common/TestURLModal/index.tsx
> [ENGG-1950] fix: regex group null check

- browser-extension/mv3/src/service-worker/services/rulesManager.ts
- browser-extension/mv3/src/utils.ts
> [ENGG-1989] fix: DNR rules not getting unique ID while saving

- browser-extension/mv3/tests/rules/cancel/cancelRule.spec.ts
- browser-extension/mv3/tests/rules/cancel/cancel_rules.json
- browser-extension/mv3/tests/rules/cancel/testScenarios.ts
- Document cancel
- fetch cancel
- xhr cancel
- Cancel with specific page domain filter
> test mv3: cancel rule

- app/src/views/features/sessions/SessionViewer/SavedSessionViewer.tsx
- app/src/views/features/sessions/SessionViewer/SessionDetails.tsx
- app/src/views/features/sessions/SessionViewer/SessionPropertiesPanel.tsx
- app/src/views/features/sessions/SessionViewer/sessionViewer.scss
> ENGG-2014: Make sessions viewer page responsive

- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/FixedRequestLogPane.js
- app/src/componentsV2/CodeEditor/components/Editor/Editor.tsx
- app/src/componentsV2/CodeEditor/types/index.ts
- app/src/views/features/api-client/client-view/response/ResponseBody.tsx
using json type is the safe option here, since type of the content cannot be inferred
> chore: use the new code editor instead of just json preview in traffic table log pane

- app/src/components/misc/InstallExtensionCTA/index.tsx
- app/src/modules/analytics/events/common/constants.js
- app/src/modules/analytics/events/common/onboarding/index.js
> [ENGG-2020] chore: added event - extension install CTA shown

- app/src/components/misc/ProductWalkthrough/constants.ts
- app/src/components/misc/ProductWalkthrough/tours.tsx
- app/src/layouts/DashboardLayout/MenuHeader/index.js
- app/src/layouts/DashboardLayout/Sidebar/PrimarySidebar/components/CreditsButton/CreditsButton.tsx
- app/src/store/initial-state/index.js
> [ENGG-2006] chore: remove ask ai and credits tour

- app/src/features/mocks/screens/mocksList/components/MocksList/components/MocksTable/hooks/useMocksTableColumns.tsx
- app/src/features/mocks/screens/mocksList/components/MocksList/components/MocksTable/mocksTable.scss
https://github.com/requestly/requestly/assets/61556757/9b8588b1-39e3-49bd-b0a8-4f7861995931
> [ENGG-1985] fix: mock server table style

- browser-extension/mv3/package.json
- browser-extension/mv3/tests/rules/replace/replaceRule.spec.ts
- browser-extension/mv3/tests/rules/replace/replace_rules.json
- browser-extension/mv3/tests/rules/replace/testScenarios.ts
_one test case that doesn't work seems like a bug_
> test mv3: replace rule

- app/src/store/features/incentivization/slice.ts
> fix: incentivization logged out state

- app/src/features/incentivization/analytics/index.ts
- app/src/features/incentivization/modals/IncentiveTaskCompletedModal/IncentiveTaskCompletedModal.tsx
> [ENGG-2046] chore: fix incentivization analytics events

- app/src/features/pricing/components/PricingTable/components/PlanColumn/index.tsx
- app/src/features/pricing/components/PricingTable/index.scss
> chore: update enterprise plan card copy

- app/src/layouts/DashboardLayout/MenuHeader/MenuHeader.css
- app/src/layouts/DashboardLayout/MenuHeader/index.js
Closes issue: 
Preview : ![image](https://github.com/requestly/requestly/assets/66509841/58bfee02-4966-4396-bfff-74b6d68bb0a4)
> [ENGG-2035] Show Github star button in Header

- app/src/index.jsx
- app/src/routes/fullScreenRoutes.tsx
> Fix: selenium importer screen broken

- app/src/lib/design-system-v2/README.md
> Update design-system readme

- app/src/features/settings/components/GlobalSettings/index.jsx
> [ENGG-2061] fix: extension installed CTA in settings page

- app/src/lib/design-system-v2/helpers/theme.css
addresses further comments added to [this](https://github.com/requestly/requestly/pull/1934)
> chore: add secondary colors to theme.css

- app/src/constants/requestMethodColors.ts
- app/src/lib/design-system-v2/README.md
- app/src/lib/design-system-v2/helpers/ThemeProvider.tsx
- app/src/lib/design-system-v2/index.ts
> chore: added theme usage in js files

- app/src/features/onboarding/components/auth/index.tsx
> Fix: brand image in auth modal

- app/src/views/misc/Invite/InviteView.tsx
- app/src/views/misc/Invite/inviteView.scss
> Fix: workspace invite view

- app/src/features/sessionBook/components/SessionPlayer/SessionPlayer.tsx
- app/src/features/sessionBook/components/SessionPlayer/sessionPlayer.scss
- app/src/features/sessionBook/screens/DraftSessionScreen/components/DraftSessionViewer/draftSessionViewer.scss
- app/src/features/sessionBook/screens/SavedSessionScreen/components/SavedSessionViewer/SavedSessionViewer.tsx
- app/src/features/sessionBook/screens/SavedSessionScreen/components/SavedSessionViewer/savedSessionViewer.scss
> Fix: session player aspect ratio

- app/src/features/sessionBook/routes.tsx
> fix: circular redirect for saved session link

- app/src/views/features/rules/RuleEditor/RuleEditor.js
> fix: rule editor render on navigation

- app/src/views/features/rules/RuleEditor/RuleEditor.js
Reverts requestly/requestly#1973
> Revert "fix: rule editor render on navigation"

- app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/ModifyHeaderRow/index.js
> fix: header rule UI

- app/src/components/features/rules/RuleBuilder/Body/RuleBuilderBody.css
> [ENGG-2022] fix: rule pair overflow in editor

- app/src/components/features/rules/RuleBuilder/RuleBuilder.js
- app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/ModifyHeaderRow/index.js
> fix: rule editor re-render

- app/src/features/sessionBook/components/SessionViewerBottomSheet/components/SessionNetworkLogs/SessionNetworkLogs.tsx
- app/src/features/sessionBook/components/SessionViewerBottomSheet/hooks/useSessionBottomSheetTabItems.tsx
- app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/components/FiltersToolbar/filtersToolbar.scss
- app/src/lib/design-system/components/RQNetworkTable/RQNetworkTable.css
- app/src/views/features/sessions/SessionViewer/NetworkLogs/NetworkLogsPanel.tsx
> Fix: Session viewer bottom sheet tabs

- app/src/features/sessionBook/components/SessionConfigPopup/SessionConfigPopup.tsx
> chore: save session copy change

- app/src/features/rules/screens/rulesList/components/RulesList/RulesList.tsx
- app/src/features/rules/screens/rulesList/components/RulesList/rulesList.scss
- app/src/features/rules/screens/sharedLists/components/SharedLists/components/SharedListsContentHeader/SharedListsContentHeader.tsx
- app/src/features/rules/screens/sharedLists/components/SharedLists/components/SharedListsContentHeader/sharedListsContentHeader.scss
- app/src/features/rules/screens/templatesList/components/TemplatesTableContentHeader/TemplatesTableContentHeader.tsx
- app/src/features/rules/screens/templatesList/components/TemplatesTableContentHeader/templatesTableContentHeader.scss
> fix: update secondary sidebar toggle button position

- app/src/components/misc/SupportPanel/supportPanel.scss
> fix : update support widget position

- app/src/components/features/rules/DuplicateRuleModal/index.tsx
- app/src/utils/rules/misc.js
- app/src/views/features/rules/RuleEditor/components/Header/ActionButtons/CreateRuleButton/index.jsx
- also no longer resets the state for unsaved changes whenever save btn is clicked
> fix: script tag wrapping when duplicating script rule

- app/src/features/sessionBook/screens/DraftSessionScreen/DraftSessionScreen.tsx
- browser-extension/common/src/custom-elements/index.ts
- browser-extension/common/src/custom-elements/session-recording-widgets/draft-session-viewer/index.css
- browser-extension/common/src/custom-elements/session-recording-widgets/draft-session-viewer/index.ts
- browser-extension/sessionbear/src/constants.ts
- browser-extension/sessionbear/src/content-scripts/common/sessionRecorder.ts
- browser-extension/sessionbear/src/service-worker/services/sessionRecording.ts
Closes issue: 
https://github.com/user-attachments/assets/9d47b71f-e20c-42cf-8ac7-0a43e187d113
> ENGG-2041: draft session iframe injection and viewing flow

- app/src/features/sessionBook/analytics/index.ts
- app/src/features/sessionBook/screens/SavedSessionScreen/components/SavedSessionViewer/SavedSessionViewer.tsx
> chore: update session viewed event properties

- app/src/components/misc/SupportPanel/index.tsx
- app/src/modules/analytics/events/misc/UnifiedSupport.ts
- app/src/modules/analytics/events/misc/constants.js
> fix: support option opened analytics

- app/src/views/features/rules/RuleEditor/components/RuleDetailsPanel/RuleDetailsPanel.scss
- app/src/views/features/rules/RuleEditor/components/RuleDetailsPanel/RuleDetailsPanel.tsx
> fix: rules details panel description

- app/src/modules/analytics/events/common/constants.js
- app/src/modules/analytics/events/common/rules/index.js
- app/src/views/features/rules/RuleEditor/components/RuleDetailsPanel/RuleDetailsPanel.tsx
> [ENGG-2108] chore: fix rule details panel events

- app/src/componentsV2/CodeEditor/components/Editor/components/Toolbar/Toolbar.tsx
- app/src/componentsV2/CodeEditor/utils.ts
> fix: editor prettify toggle

- browser-extension/mv3/src/page-scripts/ajaxRequestInterceptor/xhr.js
> fix: add failsafe in xhr interceptor

- app/src/components/features/rules/RuleBuilder/RuleBuilder.js
> [ENGG-2117] fix: remove tours from rule editor

- browser-extension/mv3/src/service-worker/services/utils.ts
> [ENGG-1956] fix: extension icon not turning grey

- browser-extension/mv3/src/common/ruleMatcher.ts
> fix: graphQl payload filtering not working for numbers

- app/src/components/misc/SupportPanel/supportPanel.scss
> fix: adjust crisp chatbox position

- app/src/views/features/rules/RuleEditor/components/Header/ActionButtons/CreateRuleButton/actions/index.js
Fixes https://github.com/requestly/requestly/pull/2002#issuecomment-2257377440
> fix: request and response rule body validations for static type

- app/src/src-SessionBear/routes/miscRoutes.tsx
> chore: add goodbye route in Sessionbear

- browser-extension/common/src/custom-elements/session-recording-widgets/draft-session-viewer/index.css
> chore: fix draft session iframe height

- app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/components/FiltersToolbar/MethodFilter.tsx
- app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/components/FiltersToolbar/filtersToolbar.scss
> ENGG-2115: Add PATCH filter in network logs panel

- app/package-lock.json
- app/package.json
- browser-extension/common/package-lock.json
- browser-extension/common/package.json
> chore: bump @requestly-ui/resource-table to v0.1.8

- app/src/componentsV2/InlineInput/InlineInput.tsx
- app/src/componentsV2/InlineInput/inlineInput.scss
- app/src/features/sessionBook/components/SessionViewerBottomSheet/components/SessionInfo/SessionInfo.tsx
- app/src/lib/design-system/custom/base.css
> ENGG-2109: Fix saved session viewer description layout

- app/src/components/misc/SupportPanel/index.tsx
- app/src/components/misc/SupportPanel/sendSlackInvite.ts
- app/src/modules/analytics/events/misc/UnifiedSupport.ts
- app/src/modules/analytics/events/misc/constants.js
> Engg 2067: Fix Slack invite changes

- app/src/actions/TeamWorkspaceActions.js
- app/src/features/sessionBook/screens/SessionsListScreen/components/OnboardingView/SessionsOnboardingView.tsx
- app/src/hooks/AuthHandler.ts
- browser-extension/sessionbear/src/constants.ts
- browser-extension/sessionbear/src/content-scripts/common/sessionRecorder.ts
- browser-extension/sessionbear/src/service-worker/services/utils.ts
- common/constants.js
> Fix: authentication flow in draft session iframe

- app/src/config/constants/sub/email-domains.js
> chore: add rambler.ru in personal email domain list

- browser-extension/mv2/package-lock.json
- common/rule-processor/package-lock.json
- rule-processor
- browser-extension/mv2
> chore: ran npm audit fix to remove dependabot alerts

- app/src/views/features/rules/RuleEditor/RuleEditor.js
> ENGG-2131: Hide bottom sheet for create mode in rule editor

- app/src/views/features/rules/RuleEditor/RuleEditor.css
> ENGG-2131: fix scroll in rule editor screen

- app/src/backend/onboarding/index.ts
- app/src/config/constants/sub/analytics.js
- app/src/features/onboarding/analytics/constants.ts
- app/src/features/onboarding/analytics/index.ts
- app/src/features/onboarding/components/persona/components/IndustryInput/index.scss
- app/src/features/onboarding/components/persona/components/IndustryInput/index.tsx
- app/src/features/onboarding/components/persona/components/personaScreen/index.tsx
- app/src/store/features/userActions.js
- app/src/store/initial-state/index.js
> [ENGG-2118]: add industry question in onboarding

- app/src/features/onboarding/components/persona/components/IndustryInput/index.tsx
> chore: update onboarding industry dropdown options

- app/src/components/features/rules/RuleBuilder/Help/Help.scss
- app/src/components/features/rules/RuleBuilder/Help/index.tsx
- app/src/modules/analytics/events/common/constants.js
- app/src/modules/analytics/events/common/rules/index.js
- app/src/modules/analytics/events/features/templates/index.js
- app/src/views/features/rules/RuleEditor/components/RuleDetailsPanel/RuleDetailsPanel.scss
- app/src/views/features/rules/RuleEditor/components/RuleDetailsPanel/RuleDetailsPanel.tsx
- app/src/views/features/rules/RuleEditor/components/RuleDetailsPanel/constants.ts
- app/src/views/features/rules/RuleEditor/components/RuleDetailsPanel/types.ts
> [ENGG-2138]: update rule details component

- app/src/components/features/mocksV2/MockEditorIndex/MockEditorIndex.tsx
- app/src/features/mocks/contexts/actions.tsx
- app/src/features/mocks/contexts/modals.tsx
- app/src/features/mocks/modals/NewFileModalWrapper/NewFileModal/NewFileTypeSelector.tsx
- app/src/features/mocks/modals/NewFileModalWrapper/NewFileModal/index.tsx
- app/src/features/mocks/modals/NewFileModalWrapper/index.tsx
- app/src/features/mocks/screens/mocksList/components/MocksList/MocksList.tsx
- app/src/features/mocks/screens/mocksList/components/MocksList/components/MocksTable/MocksTable.tsx
- app/src/features/mocks/screens/mocksList/components/MocksList/components/MocksTable/hooks/useMocksTableColumns.tsx
- app/src/features/mocks/screens/mocksList/components/MocksList/components/MocksTable/mocksTable.scss
- app/src/utils/RedirectionUtils.js
https://github.com/user-attachments/assets/9b88f289-d560-41a4-989f-71999561b22a
> [ENGG-2121] feat: create mock from collection row

- app/src/features/sessionBook/components/SaveSessionButton/SaveSessionButton.tsx
- app/src/features/sessionBook/components/SessionConfigPopup/SessionConfigPopup.tsx
- app/src/features/sessionBook/components/SessionPlayer/SessionPlayer.tsx
- app/src/features/sessionBook/components/SessionPlayer/sessionPlayer.scss
- app/src/features/sessionBook/modals/ImportSessionModal/ImportSessionModal.tsx
- app/src/features/sessionBook/screens/DraftSessionScreen/DraftSessionScreen.tsx
- app/src/features/sessionBook/screens/DraftSessionScreen/components/DraftSessionViewer/DraftSessionViewer.tsx
- app/src/features/sessionBook/screens/DraftSessionScreen/components/SessionTrimmer/SessionTrimmer.tsx
- app/src/features/sessionBook/screens/DraftSessionScreen/components/SessionTrimmer/components/TrimHandle/TrimHandle.tsx
- app/src/features/sessionBook/screens/DraftSessionScreen/components/SessionTrimmer/sessionTrimmer.scss
- app/src/features/sessionBook/screens/DraftSessionScreen/hooks/useSaveDraftSession.ts
- app/src/store/features/session-recording/selectors.ts
- app/src/store/features/session-recording/slice.ts
https://github.com/user-attachments/assets/c367ec8f-f249-4367-a58c-be5864e5aa37
> ENGG-2001: Trim Session Replay

- app/src/features/rules/screens/rulesList/components/RulesList/components/GettingStarted/v2/gettingStarted.scss
- app/src/features/rules/screens/rulesList/components/RulesList/components/GettingStarted/v2/index.tsx
> ENGG-2178: Update shared rules view UI on rules empty state

- app/src/views/features/rules/RuleEditor/components/Header/ActionButtons/CreateRuleButton/actions/insertScriptValidators.js
in some very specific cases html validate is failing for no particular reason. Couldn't find anything in their issues or even inside their source code
> fix: wrap unexpected faliures from htmlValidate

- app/src/components/common/SharingModal/ShareLinkView.tsx
------------
**Summary:**
- Upgraded imports and introduced new constants and hooks in the codebase.
**Key points:**
- Imported `getCurrentlySelectedRuleData` from the store and added `useLocation` for route handling.
- Introduced a new constant `Data` and created a memoized `visibilityOptions` array using `useMemo`.
**Categories:**
**Store selectors and imports:**
- Imported `getCurrentlySelectedRuleData` from the store.
**Route handling and configuration:**
- Added `useLocation` hook for determining the current route.
**Component refactoring:**
- Modified the `ShareLinkView` component for rule editor support.
**Variables:**
- `Data`: A new constant that holds an object with a `name` property.
**Functions:**
- `useMemo`: A React hook used to memoize the creation of …
> [ENGG-1455] fix: sharedList name generation on rule editor

- app/src/store/features/rules/slice.ts
forgot to remove this comment after already addressing the changes in the [same PR](https://github.com/requestly/requestly/pull/1437)
> cleanup: the comment was already addressed during the changes

- app/src/features/sessionBook/components/SessionPlayer/SessionPlayer.tsx
- app/src/features/sessionBook/components/SessionPlayer/sessionPlayer.scss
- app/src/features/sessionBook/screens/DraftSessionScreen/components/DraftSessionViewer/DraftSessionViewer.tsx
- app/src/features/sessionBook/screens/DraftSessionScreen/components/SessionTrimmer/SessionTrimmer.tsx
- app/src/features/sessionBook/screens/DraftSessionScreen/components/SessionTrimmer/sessionTrimmer.scss
https://github.com/user-attachments/assets/110fcf7b-91ff-42ce-9e23-41790ec25ef5
> ENGG-2244: Session trimming enhancement

- app/src/features/sessionBook/screens/SessionsListScreen/components/SessionsList/components/SessionsTable/hooks/useSessionsTableColumns.tsx
- app/src/views/features/rules/RuleEditor/components/Header/ActionButtons/HelpButton/index.scss
- app/src/views/features/rules/RuleEditor/components/Header/ActionButtons/RuleEditorActionButtons.css
- app/src/views/features/rules/RuleEditor/components/Header/ActionButtons/TestRuleButton/index.scss
- app/src/views/features/rules/RuleEditor/components/Header/EditorGroupDropdown/EditorGroupDropdown.css
- app/src/views/features/rules/RuleEditor/components/Header/RuleEditorHeader.css
- app/src/views/features/rules/RuleEditor/components/Header/RuleOptions/RuleOptions.css
- app/src/views/features/rules/RuleEditor/components/Header/index.js
Changelog:
- Fix rule editor header for small screens
- Fix session list icon overlap issue for small screens
> [ENGG-2248] fix: responsiveness issues

- app/src/features/onboarding/components/auth/components/Form/components/SSOSignInForm/index.tsx
- app/src/utils/FormattingHelper.js
Added `isDisposableEmail` in the definition of `isCompanyEmail`
> [ENGG-2210] fix: isCompanyEmail definition

- app/src/components/mode-specific/desktop/MySources/Sources/InstructionsModal/Android/ConfigureAndroidApps.js
- app/src/components/mode-specific/desktop/MySources/Sources/InstructionsModal/Android/index.js
> docs: add instruction steps about ssl pinning for android setup

- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.jsx
> fix: crash on ios on agoda.com

- app/src/layouts/DashboardLayout/Sidebar/PrimarySidebar/PrimarySidebar.css
- app/src/layouts/DashboardLayout/Sidebar/PrimarySidebar/index.tsx
> add `new` badge for network traffic inspector

- app/index.html
> [ENG-2309] App Seo improvements

- browser-extension/common/src/custom-elements/test-rule-widget/implicit-test-rule-widget/index.ts
- browser-extension/common/src/custom-elements/test-rule-widget/index.css
https://github.com/user-attachments/assets/8300cd5f-a454-433b-948e-fb79b95ff058
> ENGG-2252: Add progress bar in implicit test this rule widget

- app/src/componentsV2/AppNotificationBanner/index.tsx
> ENGG-2304: Add accelerator program banner

- browser-extension/mv2/package-lock.json
- package-lock.json
- package.json
releasing after recent bundling changes - https://github.com/requestly/requestly/pull/2233
> chore: bump version of requestly-core to v1.1.0

- app/src/features/pricing/components/PricingPage/components/OtherWaysToMakePurchase/index.tsx
- app/src/features/pricing/components/PricingTable/components/PlanColumn/index.tsx
- Notification for selection of quantity on pricing table will be sent after delay of 4000ms using debouncing
- For Anonymous user, no notification alert in slack for pricing table, request quote, PO & additional users [button click event]
- For signed up users, slack notification will appear with the button click events alert too
> [ENGG-2353] Debouncing on pricing table

- app/src/features/apiClient/routes.tsx
- app/src/features/apiClient/screens/apiClient/components/clientView/APIClientView.tsx
- app/src/features/apiClient/screens/apiClient/components/clientView/apiClientView.scss
- app/src/features/apiClient/screens/apiClient/components/sidebar/collectionsList/requestRow/RequestRow.tsx
- app/src/lib/design-system-v2/components/RQBreadcrumb/RQBreadcrumb.scss
- app/src/lib/design-system-v2/components/RQBreadcrumb/RQBreadcrumb.tsx
- app/src/modules/analytics/events/features/apiClient/index.js
- app/src/modules/analytics/events/features/constants.js
https://github.com/user-attachments/assets/51ed7931-a7a0-4735-bab0-e982d34c75b1
> [ENGG-2351] feat: add api client breadcrumb

- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/ActionHeader.jsx
- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/FixedRequestLogPane.css
- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/FixedRequestLogPane.js
- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/TrafficTableV2.css
- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.jsx
> ENGG-2336: Fix network inspector bottom tab UI issues

- browser-extension/common/src/devtools/containers/network/details-tabs/ResponseTabContent/ResponseTabContent.tsx
https://github.com/user-attachments/assets/41322b02-b080-4d3d-a29b-bcba11727ec9
> [ENGG-2436] fix(extension): response rule creation from devtools for graphql request 

- app/src/hooks/DbListenerInit/userNodeListener.js
builds on top of https://github.com/requestly/requestly/pull/2165
> fix: emailVerified property getting overridden after first write for new accounts

- app/src/features/onboarding/components/teams/index.tsx
since the issue from fixed by https://github.com/requestly/requestly/pull/2003 reoccured, this was the only reason I found the race condition would occur.
could not consistently reproduce it without this fix, but the changes seem to make no harm to the current code
> attempt to improve previous fix for multiple onboarding workspace creation

- app/src/features/apiClient/screens/apiClient/components/sidebar/collectionsList/CollectionsList.tsx
- app/src/features/apiClient/screens/apiClient/utils.ts
UI Rendering for subcollections
> ENG-2467. Add logic to render sub collections

- app/src/features/pricing/components/PricingPage/PricingIndexPage.tsx
- app/src/features/pricing/components/PricingPage/components/SaleBanner/PricingBannerSale.scss
- app/src/features/pricing/components/PricingPage/components/SaleBanner/PricingBannerSale.tsx
> [ENGG-2476]Pricing page banner Black Friday

- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/Tables/GroupByNone.jsx
- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/TrafficTableV2.css
- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.jsx
- app/src/lib/design-system-v2/components/RQTooltip/RQTooltip.scss
- app/src/lib/design-system-v2/components/RQTooltip/RQTooltip.tsx
- app/src/lib/design-system-v2/components/index.ts
- Row color changed for modified requests
- Color changed for modified & selected request in traffic table
> [ENGG-2413] traffic table UI enhancements

- app/src/features/apiClient/contexts/apiClient.tsx
- app/src/features/apiClient/screens/apiClient/components/modals/deleteApiRecordModal/DeleteApiRecordModal.tsx
Reverts requestly/requestly#2356
> Revert "[ENGG-2485] fix: sidebar breadcrumb sync - navigate to root route"

- app/src/features/apiClient/screens/environment/components/VariablesList/VariablesList.tsx
> [ENGG-2498] Fix: Environment variables table overflowing

- app/src/features/apiClient/screens/apiClient/components/sidebar/components/apiClientSidebarHeader/ApiClientSidebarHeader.tsx
> [ENGG-2502] Import Postman renamed to Postman collection

- app/src/componentsV2/modals/CreateWorkspaceModal/index.jsx
> [ENGG-2493] Fix: Notify all teammates should be unchecked by default

- app/src/features/rules/screens/rulesList/components/RulesList/components/RulesTable/hooks/useRuleTableColumns.tsx
> [ENGG-2481] Ungroup Option in individual rule

- app/src/features/pricing/components/PricingTable/PricingTableButtons.tsx
- app/src/features/pricing/components/PricingTable/components/PlanColumn/index.tsx
- app/src/features/pricing/components/PricingTable/index.scss
- app/src/features/pricing/constants/pricingPlans.ts
Remove CTA from lite plan monthly duration.
> [ENG-2596]. Lite plan experiment.

- app/src/components/mode-specific/desktop/MySources/Sources/index.js
fixes changes in https://github.com/requestly/requestly/pull/2300 to accommodate changes made in https://github.com/requestly/requestly/pull/2361
> fix: action imports that were changed during redux rewrites

- app/src/features/apiClient/contexts/apiClient.tsx
- app/src/features/apiClient/screens/apiClient/components/clientView/APIClientView.tsx
- app/src/features/apiClient/screens/apiClient/components/clientView/components/request/components/KeyValueTable/KeyValueTable.tsx
- app/src/hooks/index.ts
- app/src/hooks/useHasUnsavedChanges.ts
- app/src/layouts/DashboardLayout/Sidebar/PrimarySidebar/PrimarySidebar.css
- app/src/layouts/TabsLayout/components/TabsLayoutContent/TabsLayoutContent.tsx
- app/src/layouts/TabsLayout/components/TabsLayoutContent/tabsLayoutContent.scss
- app/src/layouts/TabsLayout/components/TabsLayoutHeader/TabsLayoutHeader.tsx
- app/src/layouts/TabsLayout/contexts/tabsLayoutContext.tsx
Cases covered:
If any unsaved change tigger prompt: 
- while tab close clicked.
- when page refreshed.
- when any tab has unsaved changes and page is refreshed.
Demo:
https://github.com/user-attachments/assets/150b4605-a39a-427a-81af-e86547133729
> [ENGG-2567] feat: show unsaved changes indication 

- app/src/features/apiClient/helpers/APIClientManager/index.ts
- app/src/features/apiClient/helpers/auth.ts
- app/src/features/apiClient/screens/apiClient/components/clientView/APIClientView.tsx
- app/src/features/apiClient/screens/apiClient/components/clientView/components/Collection/CollectionView.tsx
- app/src/features/apiClient/screens/apiClient/components/clientView/components/request/components/AuthorizationView/authStaticData.ts
- app/src/features/apiClient/screens/apiClient/components/clientView/components/request/components/AuthorizationView/index.tsx
- app/src/features/apiClient/screens/apiClient/components/clientView/components/request/components/AuthorizationView/types/index.ts
cherry picks (_with cautious modifications_) changes from https://github.com/requestly/requestly/pull/2412  
most of it needs to be redone based on the improvements later made and merged through https://github.com/requestly/requestly/pull/2409
> feat: inherit from parent

- app/src/componentsV2/CodeEditor/components/Editor/components/Toolbar/Toolbar.tsx
- app/src/features/apiClient/screens/apiClient/APIClient.tsx
- app/src/features/apiClient/screens/apiClient/components/sidebar/APIClientSidebar.tsx
- app/src/features/apiClient/screens/apiClient/components/sidebar/components/apiClientSidebarHeader/ApiClientSidebarHeader.tsx
- app/src/features/apiClient/screens/apiClient/utils.ts
* Fixes cURL import modal stuck on loading issue
* import cURL modal not opening for other screens like env and empty state
* Handles missing loggedIn checks when clicking on import
> ENGG-2644: Fix cURL import modal stuck on loading issues

- app/src/componentsV2/CodeEditor/components/Editor/Editor.tsx
- app/src/features/apiClient/screens/apiClient/components/clientView/components/request/RequestBody.tsx
- Json body will not be copied in RAW body
- Also when switching content type the prettification will be applied
> [ENGG-2664] JSON body getting copied in RAW editor - API Client

- app/src/features/apiClient/container.tsx
- app/src/features/apiClient/contexts/apiClient.tsx
- app/src/features/apiClient/routes.tsx
- app/src/features/apiClient/screens/apiClient/APIClient.tsx
- app/src/features/apiClient/screens/environment/components/VariablesListHeader/variablesListHeader.scss
- app/src/features/apiClient/screens/environment/components/environmentView/EnvironmentView.tsx
- app/src/features/apiClient/screens/environment/components/environmentView/environmentView.scss
- app/src/features/apiClient/screens/environment/container.scss
- app/src/features/apiClient/screens/environment/container.tsx
Reverts requestly/requestly#2463
> Revert "[ENGG-2635] fix: incorrect data loads in tabs while switching"

- app/package.json
- app/tsconfig.json
- install.sh
- shared/README.md
- shared/build.sh
- shared/install.sh
- shared/package-lock.json
- shared/package.json
- shared/rollup.config.js
- shared/src/helpers/common/geolocation.ts
- shared/src/helpers/common/index.ts
- shared/src/helpers/index.ts
- shared/src/index.ts
- shared/src/types/common/index.ts
- shared/src/types/common/network/index.ts
- shared/src/types/entities/base.ts
- shared/src/types/entities/index.ts
- shared/src/types/entities/rules/base.ts
- shared/src/types/entities/rules/group.ts
- shared/src/types/entities/rules/index.ts
- shared/src/types/entities/rules/rule.ts
- shared/src/types/index.ts
- shared/tsconfig.json
> chore: init shared module

- app/package-lock.json
- app/src/features/apiClient/screens/apiClient/components/clientView/APIClientView.tsx
- app/src/features/apiClient/screens/apiClient/components/clientView/apiClientView.scss
> style: add color to methods in apiClient

- app/src/features/apiClient/contexts/apiClient.tsx
- app/src/features/apiClient/screens/apiClient/components/clientView/APIClientView.tsx
- app/src/features/apiClient/screens/apiClient/components/sidebar/components/collectionsList/requestRow/RequestRow.tsx
- app/src/layouts/TabsLayout/components/TabsLayoutContent/TabsLayoutContent.tsx
- app/src/layouts/TabsLayout/components/TabsLayoutContent/tabsLayoutContent.scss
- app/src/layouts/TabsLayout/contexts/tabsLayoutContext.tsx
- app/src/layouts/TabsLayout/types.ts
https://github.com/user-attachments/assets/da911c8c-d74f-4eb3-b62b-b55f873463ce
> [ENGG-2570] feat: add support for tabs preview mode

- app/src/actions/TeamWorkspaceActions.js
- app/src/backend/environment/hooks/useEnvironmentManager.ts
- app/src/store/features/variables/reducers.ts
- app/src/store/features/variables/types.ts
- Changed redux structure to store the environments mapped to `ownerId`
> [ENGG-2735] fix: current values get cleared on switching workspace

- app/src/features/apiClient/screens/environment/components/VariablesList/VariablesList.tsx
- app/src/features/apiClient/screens/environment/components/environmentView/EnvironmentView.tsx
Reverts requestly/requestly#2537
> Revert "fix: env variable row focus disappear issue"

- app/package-lock.json
- app/src/components/features/mocksV2/MockEditorIndex/Editor/Header/index.tsx
- app/src/components/features/mocksV2/MockEditorIndex/Editor/index.tsx
- app/src/components/features/mocksV2/MockEditorIndex/types.ts
- app/src/components/features/mocksV2/MockEditorIndex/utils.ts
Demo
<video src=https://github.com/user-attachments/assets/98041ccf-9711-4b0a-a0b3-5874cc69e33b />
> fix: only allow selected content-types in mock server

- app/src/layouts/DashboardLayout/Sidebar/PrimarySidebar/index.tsx
> [ENGG-2841]: reorder primary sidebar options

- app/src/features/apiClient/contexts/apiClient.tsx
- app/src/features/apiClient/screens/apiClient/components/clientView/APIClientView.tsx
- app/src/features/apiClient/screens/apiClient/components/clientView/components/request/components/RequestTabs/RequestTabs.tsx
- app/src/features/apiClient/screens/apiClient/components/clientView/components/request/request-body-state-manager.ts
- app/src/hooks/index.ts
- app/src/hooks/useDeepLinkState.ts
https://github.com/user-attachments/assets/b53ed8b7-7a01-46bc-96c6-9d9bf4a2da6d
> [ENGG-2838] feat: add deep links for api client content tabs

- app/src/componentsV2/CodeEditor/components/EditorV2/plugins/generateAutoCompletions/index.ts
- app/src/features/apiClient/screens/environment/components/SingleLineEditor/SingleLineEditor.tsx
> [ENGG-2858] fix: hide secret value in autocomplete dropdown

- app/src/features/settings/components/SettingsPrimarySidebar/index.scss
- app/src/features/settings/components/SettingsPrimarySidebar/index.tsx
- app/src/layouts/DashboardLayout/DashboardLayout.scss
- app/src/layouts/DashboardLayout/MenuHeader/HeaderText.jsx
- app/src/layouts/DashboardLayout/MenuHeader/HeaderUser.jsx
- app/src/layouts/DashboardLayout/MenuHeader/ProductsDropDown.tsx
- app/src/layouts/DashboardLayout/MenuHeader/WorkspaceSelector/index.jsx
- app/src/layouts/DashboardLayout/MenuHeader/index.js
- app/src/layouts/DashboardLayout/index.jsx
- app/src/src-SessionBear/layouts/DashboardLayout/index.jsx
Needs to support linux and window too in future
Related Desktop App PR - https://github.com/requestly/requestly-desktop-app/pull/124
> feat: support macOs frameless window

- shared/package-lock.json
- shared/package.json
- shared/rollup.config.js
- shared/src/types/entities/index.ts
- shared/src/types/entities/rules/base.ts
- shared/src/types/entities/rules/rule.ts
- shared/tsconfig.json
- Fix Watch mode
- Fix alias not resolved for type definitions
> chore: improve @requestly/shared build process

- app/src/features/apiClient/screens/apiClient/components/clientView/components/request/components/AuthorizationView/Description.tsx
- app/src/features/apiClient/screens/apiClient/components/clientView/components/request/components/AuthorizationView/HelpPanel.tsx
- app/src/features/apiClient/screens/apiClient/components/clientView/components/request/components/AuthorizationView/authStaticData.ts
- app/src/features/apiClient/screens/apiClient/components/clientView/components/request/components/AuthorizationView/authorizationView.scss
- app/src/features/apiClient/screens/apiClient/components/clientView/components/request/components/AuthorizationView/index.tsx
https://github.com/user-attachments/assets/1540eea5-32e6-4fe6-b010-dffe1511427a
> [ENGG-2868] fix: update api client auth tab help message

- app/src/constants/requestMethodColors.ts
- app/src/features/apiClient/screens/apiClient/components/clientView/apiClientView.scss
- app/src/features/apiClient/screens/apiClient/components/sidebar/components/collectionsList/collectionsList.scss
- app/src/features/apiClient/screens/apiClient/components/sidebar/components/collectionsList/requestRow/RequestRow.tsx
> [ENGG-2870] fix(style): update request method colors

- app/src/features/pricing/components/PricingPage/components/EnterpriseRequestBanner/index.css
- app/src/features/pricing/components/ProductSwitcher/index.tsx
- app/src/features/pricing/components/ProductSwitcher/productSwitcher.scss
https://github.com/user-attachments/assets/cb157ac4-04be-407b-8d24-c40de9564839
> [ENGG-2953] fix: pricing page responsiveness  

- app/src/components/features/mocksV2/MockEditorIndex/Editor/Header/index.tsx
- app/src/components/misc/ProductWalkthrough/Tooltip/index.tsx
- app/src/components/mode-specific/desktop/MySources/Sources/InstructionsModal/InstructionsHeader.tsx
- app/src/views/features/rules/RuleEditor/components/Header/EditorGroupDropdown/index.tsx
- app/src/views/features/rules/RuleEditor/components/Header/RuleOptions/index.jsx
- app/src/views/features/sessions/ConfigurationPage/ConfigurationPage.js
- app/src/views/features/sessions/SessionViewer/SavedSessionViewer.tsx
- app/src/views/features/sessions/SessionsIndexPageContainer/NetworkSessions/NetworkSessionViewer/NetworkSessionViewer.tsx
> [ENGG-2855] fix: mock server svg bug

- app/src/components/Home/index.tsx
Reverts requestly/requestly#2669
> Revert "[ENG-2860]: Fix display name crash"

- app/package-lock.json
- app/package.json
- app/src/componentsV2/CodeEditor/components/EditorV2/Editor.tsx
> [ENGG-2998] fix: typescript error in codeEditorV2

- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/FixedRequestLogPane.js
[Sentry Issue URL](https://requestly.sentry.io/issues/6271817225/)
> [ENGG-3007] sentry crash: body undefined issue in FixedRequestLogPane.js

- app/src/componentsV2/BottomSheet/components/BottomSheetLayout/BottomSheetLayout.scss
- app/src/features/apiClient/screens/apiClient/components/clientView/APIClientView.tsx
- app/src/features/apiClient/screens/apiClient/components/clientView/apiClientView.scss
> [ENG-2983]: API Client URL Tab Width Changes

- eligible-student-domains.md
This PR adds`.edu.in` to the list of eligible domains for the Student Program.
Issue - https://github.com/requestly/requestly/issues/2690
> Add .edu.in to eligible student domains

- app/src/services/DesktopBackgroundService.ts
Creates a base adapter class for an RPC like service created in the background. https://github.com/requestly/requestly-desktop-app/pull/129
> feat: Adapter for Desktop Background RPC service

- app/src/features/apiClient/screens/apiClient/components/sidebar/components/apiClientSidebarHeader/components/environmentSwitcher/EnvironmentSwitcher.tsx
- app/src/features/apiClient/screens/apiClient/components/sidebar/components/apiClientSidebarHeader/components/environmentSwitcher/environmentSwitcher.scss
https://github.com/user-attachments/assets/5261d36a-abc6-498a-aa66-6a4a33223ae5
> [ENGG-2989] fix: set max-height & scroll for env dropdown

- app/src/features/settings/components/Profile/ManageTeams/TeamViewer/MembersDetails/TeamMembersTable/index.js
- app/src/features/settings/components/Profile/ManageTeams/TeamViewer/MembersDetails/index.js
- app/src/features/settings/components/Profile/ManageTeams/TeamViewer/TeamSettings/WorkspaceStatusSyncing/index.js
Changes:
- Block adding a user /  public link creation
- Block removing a user
- Block and turn off sync rule status
> [ENGG-3173]: RBAC - workspaces 

- app/src/features/sessionBook/components/SaveSessionButton/SaveSessionButton.tsx
- app/src/features/sessionBook/components/SessionViewerBottomSheet/components/SessionInfo/SessionInfo.tsx
- app/src/features/sessionBook/screens/DraftSessionScreen/components/DraftSessionDetailsPanel/DraftSessionDetailsPanel.tsx
- app/src/features/sessionBook/screens/DraftSessionScreen/components/DraftSessionViewer/DraftSessionViewer.tsx
- app/src/features/sessionBook/screens/SavedSessionScreen/components/SavedSessionViewer/SavedSessionViewer.tsx
- app/src/features/sessionBook/screens/SavedSessionScreen/components/SessionsTitle/SessionTitle.tsx
- app/src/features/sessionBook/screens/SessionsListScreen/components/OnboardingView/SessionsOnboardingView.tsx
- app/src/features/sessionBook/screens/SessionsListScreen/components/SessionsList/components/SessionsListContentHeader/SessionsListContentHeader.tsx
- app/src/features/sessionBook/screens/SessionsListScreen/components/SessionsList/components/SessionsTable/hooks/useSessionsTableColumns.tsx
- app/src/features/settings/components/Profile/ManageTeams/TeamViewer/MembersDetails/TeamMembersTable/index.js
- app/src/features/settings/components/Profile/ManageTeams/TeamViewer/MembersDetails/index.js
- app/src/features/settings/components/Profile/ManageTeams/TeamViewer/TeamSettings/WorkspaceStatusSyncing/index.js
- Listing:
- Remove all top-right primary actions.
- Remove all share and delete options
- Saved view:
- Make breadcrumb read only
- Block all the editing options for all the inputs
- Draft view:
- Block save button and on hover show view only message
- Block all the inputs
> [ENGG-3115]: RBAC - sessions

- app/src/componentsV2/CodeEditor/components/EditorV2/Editor.tsx
> fix: reading undefined(length) sentry issue

- app/src/layouts/DashboardLayout/MenuHeader/ProductsDropDown.tsx
- app/src/layouts/DashboardLayout/Sidebar/PrimarySidebar/index.tsx
https://github.com/user-attachments/assets/57f94a05-688d-44b1-a783-3ad257b34314
> [ENGG-3323] fix: add beta label on apiClient

- app/src/features/pricing/components/PricingTable/components/PlanColumn/index.tsx
- app/src/features/pricing/components/PricingTable/index.scss
> fix: digits overflow on pricing page UI

- app/src/features/apiClient/screens/apiClient/components/clientView/APIClientView.tsx
- app/src/features/apiClient/screens/apiClient/components/clientView/components/Collection/CollectionView.tsx
- app/src/features/apiClient/screens/apiClient/components/sidebar/components/ErrorFilesList/errorFilesList.scss
Reverts requestly/requestly#2897
(everything seems good)
> Revert "Revert "[ENGG-3356]: local sync tabs regression fixes""

- browser-extension/mv3/src/utils.ts
> fix: xs-leak in extension

- app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/CustomScriptRow/index.jsx
> fix: rename mock server in insert scripts

- app/src/components/Home/components/EmptyCard/staticData.ts
- app/src/components/Home/components/HelpCard/index.tsx
- app/src/config/constants/sub/links.js
Updated all youtube links with rqst.ly shortlinks
> [ENGG-3403] fix: Broken tutorial link

- app/src/features/apiClient/screens/apiClient/components/clientView/APIClientView.tsx
> fix: generate client code CTA

- app/src/components/features/rules/RulePairs/Pairs/HeadersRulePair/HeadersRulePairV2/HeadersPairModificationRowV2.js
https://github.com/user-attachments/assets/435dec8a-60d6-4dfc-ba2b-a641218b8a16
> fix: enable spacing in modify header rule

- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/NetworkTable/index.tsx
> fix: reduce font-weight of method in network table 

- app/src/componentsV2/modals/CreateWorkspaceModal/CreateWorkspaceModal.css
- app/src/componentsV2/modals/CreateWorkspaceModal/index.jsx
> [ENGG-3397] fix: create workspace btn on next line

- app/src/layouts/DashboardLayout/MenuHeader/PremiumPlanBadge/PremiumPlanBadge.tsx
> [ENGG-3406] fix: plan expiration badge style change

- eligible-student-domains.md
This pull request updates the list of eligible domains for the student program in the `eligible-student-domains.md` file. It adds a new domain and corrects formatting.
Changes to eligible domains:
* Added the domain `"epitech.eu"` to the list of eligible student domains.
> Add epitech.eu domain for students

- app/src/components/common/ViewOnlyModeBanner/viewOnlyModeBanner.scss
- app/src/features/rules/screens/rulesList/components/RulesList/components/ImporterComponents/CharlesImporter/index.tsx
- app/src/features/rules/screens/rulesList/components/RulesList/components/ImporterComponents/ModheaderImporter/ImportFromModheaderScreen.tsx
- app/src/features/rules/screens/rulesList/components/RulesList/components/ImporterComponents/ResourceOverrideImporter/index.tsx
- app/src/routes/miscRoutes.tsx
Demo:
https://github.com/user-attachments/assets/c1adf443-f769-46f2-83cd-8d9a64993a5f
> [ENGG-3470] fix: rule importers for read role user

- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/FixedRequestLogPane.css
- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/FixedRequestLogPane.js
> [ENGG-3532] fix: method color change in request header

- app/src/features/pricing/constants/pricingFeatures.ts
> fix: remove non-commercial use only

- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/FixedRequestLogPane.js
> fix: added a check for string/object value

- browser-extension/common/src/popup/components/BlockedExtensionView/BlockedExtensionView.tsx
> fix: import blocked extension view scss

- app/src/components/authentication/LoginHandler/index.tsx
- app/src/features/onboarding/screens/BStackAuthStart/BStackAuthStart.tsx
- app/src/features/onboarding/screens/auth/AuthScreen.tsx
- app/src/features/onboarding/screens/auth/components/NewSignupCard/NewSignupCard.tsx
- app/src/features/onboarding/screens/auth/components/SignupWithBStackCard/SignupWithBStackCard.tsx
- app/src/features/onboarding/screens/auth/context/index.tsx
- app/src/features/onboarding/screens/auth/modals/AuthModal/AuthModal.tsx
- app/src/features/onboarding/utils.ts
- app/src/features/pricing/components/PricingTable/PricingTableButtons.tsx
- app/src/layouts/AppLayout/GlobalModals/index.tsx
- app/src/layouts/DashboardLayout/MenuHeader/HeaderUser.jsx
Was reverted due to https://requestly.sentry.io/issues/6504660161/?alert_rule_id=15725428&alert_type=issue&environment=production&notification_uuid=e2ff51fa-3ccd-4c37-acc1-0be2ab598766&project=4503895961305088&referrer=slack
> [ENGG-3541] fix: after signup redirect

- app/src/components/features/mocksV2/MockEditorIndex/Editor/Header/index.tsx
- app/src/constants/keyboardShortcuts.ts
https://github.com/user-attachments/assets/d4758ec6-ca50-48c5-8922-3e34f2800a10
> [ENGG-3606] feat: enable save shortcut-file server

- app/src/features/apiClient/screens/apiClient/components/modals/ImportFromCurlModal/ImportRequestModal.tsx
- app/src/features/apiClient/screens/apiClient/components/modals/ImportFromCurlModal/importFromCurlModal.scss
- app/src/features/apiClient/screens/apiClient/components/modals/index.ts
- app/src/features/apiClient/screens/apiClient/components/sidebar/APIClientSidebar.tsx
- app/src/features/apiClient/screens/apiClient/utils.ts
> ENGG-3656: Fix error messaging in curl importer modal

- app/src/features/apiClient/screens/apiClient/components/sidebar/components/apiClientSidebarHeader/components/environmentSwitcher/environmentSwitcher.scss
- app/src/features/apiClient/screens/apiClient/components/sidebar/components/collectionsList/collectionsList.scss
- app/src/features/apiClient/screens/environment/components/environmentsList/components/environmentsListItem/EnvironmentsListItem.tsx
- app/src/features/apiClient/screens/environment/components/environmentsList/environmentsList.scss
* Active env styling
* Sidebar item ellipsis to take available space
* minor styling fixes
> ENGG-3371: Fix API Client sidebar item styles

- app/src/features/apiClient/screens/apiClient/components/sidebar/APIClientSidebar.tsx
- app/src/features/apiClient/screens/apiClient/components/sidebar/apiClientSidebar.scss
- app/src/features/apiClient/screens/apiClient/components/sidebar/components/ErrorFilesList/ErrorFileslist.tsx
- app/src/features/apiClient/screens/apiClient/components/sidebar/components/ErrorFilesList/errorFilesList.scss
- app/src/features/apiClient/screens/apiClient/components/sidebar/components/collectionsList/CollectionsList.tsx
- app/src/features/apiClient/screens/apiClient/components/sidebar/components/collectionsList/collectionsList.scss
- app/src/features/apiClient/screens/environment/components/environmentsList/EnvironmentsList.tsx
- app/src/features/apiClient/screens/environment/components/environmentsList/environmentsList.scss
> ENGG-3565: Common section for error files in sidebar for apis and envs

- eligible-student-domains.md
add "strayer"edu to student domains
> add "strayer.edu" to student domains

- eligible-student-domains.md
> adding my other .edu

- app/package-lock.json
- app/package.json
- app/patches/@uiw+react-codemirror+4.22.1.patch
- app/src/componentsV2/CodeEditor/components/EditorV2/Editor.tsx
shared further details [here](https://github.com/uiwjs/react-codemirror/issues/694#issuecomment-2954215912)
> patch: react-codemirror

- app/src/features/apiClient/screens/apiClient/components/sidebar/components/ErrorFilesList/ErrorFileslist.tsx
- app/src/features/apiClient/screens/apiClient/components/sidebar/components/ErrorFilesList/errorFilesList.scss
> ENGG-3759: Add delete confirmatin popup for error files

- eligible-student-domains.md
> Add ".edu.pe" to eligible student domains

- app/patches/@uiw+react-codemirror+4.22.1.patch
the interval based ticking to just keep one timeout is clearly a improvement for performance.
<details>
<summary>logs while typing quickly for each case</summary>
```
/* LOGS FROM ORIGINAL APPROACH */
DG-2: updateListener-setTimeout-rq-cm-instance-1: 0.3740234375 ms
DG-2: updateListener-setTimeout-rq-cm-instance-1: 0.259033203125 ms
DG-2: updateListener-setTimeout-rq-cm-instance-1: 0.241943359375 ms
DG-2: updateListener-setTimeout-rq-cm-instance-1: 0.253173828125 ms
DG-2: updateListener-setTimeout-rq-cm-instance-1: 0.676025390625 ms
DG-2: updateListener-setTimeout-rq-cm-instance-1: 0.424072265625 ms
DG-2: updateListener-setTimeout-rq-cm-instance-1: 0.472900390625 ms
DG-2: updateListener-setTimeout-rq-cm-instance-1: 0.329833984375 ms
DG-2: updateListener-setTimeout-rq-cm-instance-1: …
```
> perf: create a custom timeoutLatch for tracking `isTyping`

- app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/utils/index.ts
fixes https://github.com/requestly/requestly/issues/3159
> fix: parse appName carefully and return Unknown App if no results

- app/src/componentsV2/Tabs/components/tabsContainer.scss
https://github.com/user-attachments/assets/18789a6b-9a5c-4078-a8a7-183990e249b7
> [ENGG-3874] fix: border for tab distinction

- app/package-lock.json
- app/package.json
- app/patches/@uiw+react-codemirror+4.22.1.patch
tries to improve on the [last implementation](https://github.com/requestly/requestly/pull/3112) as that had to be reverted because of regression
> patch react-codemirror: to not allow updates to be applied while typing

- app/package-lock.json
- package.json
- shared/package-lock.json
- shared/package.json
> chore: publish @requestly/shared@1.0.3 and @requestly/requestly-core@1.1.1

- app/src/features/settings/components/BillingTeam/components/BillingDetails/MyBillingTeamDetails/components/BillingTeamMembers/index.tsx
- app/src/features/settings/components/BillingTeam/components/BillingDetails/MyBillingTeamDetails/components/TeamPlanDetails/index.tsx
- app/src/features/settings/components/BillingTeam/components/BillingDetails/MyBillingTeamDetails/index.tsx
- app/src/features/settings/components/BillingTeam/types.ts
> [ENGG-3912] added banner to block actions for bstack migrated billing teams

- app/src/backend/apiClient/batchCreateApiRecordsWithExistingId.ts
- app/src/features/apiClient/helpers/modules/sync/localStore/components/AutoSyncLocalStoreDaemon.tsx
- app/src/features/apiClient/helpers/modules/sync/localStore/store/syncServiceStore.ts
- app/src/features/apiClient/helpers/modules/sync/localStore/store/types.ts
https://github.com/user-attachments/assets/f895930d-17a0-473f-a10d-62eb01881792
> fix: sync fire and forget could still lead to multiple syncs

- app/src/backend/mocks/updateMock.ts
- app/src/features/mocks/modals/ImportMocksModalWrapper/ImportMocksModal.tsx
Reverts requestly/requestly#3284
> Revert "[ENGG-4003] fix: mock gets imported with incorrect ownerId"

- app/src/features/apiClient/screens/apiClient/components/views/components/request/components/ApiClientUrl/ApiClientUrl.tsx
- app/src/features/apiClient/screens/apiClient/components/views/graphql/GraphQLClientView.tsx
- app/src/features/apiClient/screens/apiClient/components/views/graphql/components/GraphQLClientUrl/GraphQLClientUrl.tsx
- app/src/features/apiClient/screens/apiClient/components/views/graphql/components/GraphQLEditor/GraphQLEditor.tsx
- app/src/features/apiClient/screens/apiClient/components/views/graphql/components/GraphQLEditor/components/OperationEditor/GQ_SCHEMA.json
- app/src/features/apiClient/screens/apiClient/components/views/graphql/components/GraphQLEditor/components/OperationEditor/OperationEditor.tsx
- app/src/features/apiClient/screens/apiClient/components/views/graphql/components/GraphQLEditor/components/VariablesEditor/VariablesEditor.tsx
- app/src/features/apiClient/screens/apiClient/components/views/http/HttpClientView.tsx
- app/src/features/apiClient/screens/apiClient/components/views/http/components/HttpClientUrl/HttpClientUrl.tsx
- app/src/features/apiClient/store/apiRecord/base.ts
- app/src/features/apiClient/store/apiRecord/graphqlRecord/graphqlRecord.store.ts
- API client URL
- Editor components
- Operations
- Variables
> [ENGG-4011]: Add basic components in GraphQL client view for execution

- app/src/features/apiClient/screens/apiClient/components/views/graphql/components/SchemaBuilder/SchemaBuilder.tsx
- app/src/features/apiClient/screens/apiClient/components/views/graphql/components/SchemaBuilder/schemaBuilder.scss
> ENGG-4101: dropdown in query builder to add operations

- app/src/features/apiClient/store/apiClientFeatureContext/apiClientFeatureContext.store.ts
- app/src/features/apiClient/store/multiWorkspaceView/multiWorkspaceView.store.ts
- Workspaces store
- Contexts store
> [ENGG-4106]: stores for multi workspace view

- app/src/features/apiClient/store/apiClientFeatureContext/apiClientFeatureContext.store.ts
- app/src/features/apiClient/store/variables/variables.store.ts
Reverts requestly/requestly#3372
> Revert "[ENGG-4124]: use immer for zustand stores"

- app/src/features/workspaces/components/LocalWorkspaceAvatar.tsx
- app/src/layouts/DashboardLayout/MenuHeader/WorkspaceSelector/MultiWorkspaceAvatarGroup.tsx
- app/src/layouts/DashboardLayout/MenuHeader/WorkspaceSelector/WorkSpaceSelector.css
- app/src/layouts/DashboardLayout/MenuHeader/WorkspaceSelector/index.jsx
- app/src/layouts/DashboardLayout/MenuHeader/menuHeader.scss
https://github.com/user-attachments/assets/2688d645-d82a-41b7-829d-acbcdc941719
> [ENGG-4080] fix: improve the multi-workspace dropdown

- app/src/componentsV2/CodeEditor/components/EditorV2/components/VariablePopOver/index.tsx
- app/src/componentsV2/CodeEditor/components/EditorV2/components/VariablePopOver/variable-popover.scss
https://github.com/user-attachments/assets/323141b2-7db5-4411-80e2-0d2a0af77172
> [ENGG-4709] UI: Variable popover

- app/src/features/apiClient/screens/apiClient/components/sidebar/MultiWorkspaceSidebar/ContextualCollectionsSidebar/CollectionsList/contextualCollectionsList.scss
- app/src/features/apiClient/screens/apiClient/components/sidebar/MultiWorkspaceSidebar/ContextualCollectionsSidebar/ContextualCollectionsSidebar.tsx
- app/src/features/apiClient/screens/apiClient/components/sidebar/MultiWorkspaceSidebar/ContextualEnvironmentsSidebar/ContextualEnvironmentsSidebar.tsx
- app/src/features/apiClient/screens/apiClient/components/sidebar/MultiWorkspaceSidebar/WorkspaceProvider/WorkspaceCollapse/WorkspaceCollapse.tsx
- app/src/features/apiClient/screens/apiClient/components/sidebar/MultiWorkspaceSidebar/WorkspaceProvider/WorkspaceCollapse/workspaceCollapse.scss
- app/src/features/apiClient/screens/apiClient/components/sidebar/MultiWorkspaceSidebar/WorkspaceProvider/WorkspaceProvider.tsx
- app/src/features/apiClient/screens/apiClient/components/sidebar/components/apiClientSidebarHeader/components/environmentSwitcher/EnvironmentSwitcher.tsx
- app/src/features/apiClient/screens/apiClient/components/sidebar/components/apiClientSidebarHeader/components/environmentSwitcher/environmentSwitcher.scss
https://github.com/user-attachments/assets/cb94fc5e-1ff0-4918-a935-91010a2e8557
> [ENGG-4146]: show env switcher in workspace collapse

- app/src/features/apiClient/screens/apiClient/components/modals/MoveToCollectionModal/MoveToCollectionModal.tsx
- app/src/features/apiClient/screens/apiClient/components/modals/MoveToCollectionModal/moveToCollectionModal.scss
- app/src/features/apiClient/screens/apiClient/components/modals/MoveToCollectionModal/utils.ts
- app/src/features/apiClient/screens/apiClient/components/sidebar/MultiWorkspaceSidebar/ContextualCollectionsSidebar/ContextualCollectionsSidebar.tsx
https://github.com/user-attachments/assets/ef30e0f9-0a31-4626-bac4-c9c45b79f2cd
> [ENGG-4143] feat: move record across workspace

- app/src/features/apiClient/contexts/meta.tsx
picks out changes from https://github.com/requestly/requestly/pull/3429 (hence supersedes it for now)
> refactor: abstract out getApiClientFeatureContext

- app/src/features/apiClient/screens/apiClient/components/sidebar/MultiWorkspaceSidebar/ContextualEnvironmentsSidebar/ContextualEnvironmentsList/contextualEnvironmentsList.scss
https://github.com/user-attachments/assets/0596e086-0a13-4f8a-ac9e-cd9b6b69e373
> [ENGG-4124] fix: scroll on environment sidebar

- app/src/features/apiClient/screens/environment/components/RuntimeVariables/runtimevariables.scss
- app/src/features/apiClient/screens/environment/components/RuntimeVariables/runtimevariables.tsx
https://github.com/user-attachments/assets/d5d5d7b9-db90-48c9-80c5-64f0aeafc2b9
> [ENGG-4208] fix: unselect runtime variables from side panel
