app/src/layouts/DashboardLayout/Sidebar/ProductAnnouncement/index.tsx

Fixed Github Repo link

---

app/src/layouts/DashboardLayout/Sidebar/Sidebar.css
app/src/layouts/DashboardLayout/Sidebar/index.js
app/src/lib/design-system/custom/base.css

RQLY-1207: fix workspace invite button on mobile sidebar

---

app/src/components/features/sharedLists/CreateSharedListModal/index.js
app/src/components/landing/ruleSelection/rules-data.tsx
app/src/config/constants/sub/rule-types.js

RQLY-1194 reorder response and request rule option

---

app/src/components/features/mocksV2/utils/index.ts
app/src/config/constants/index.js

fix: mocks not working locally

---

app/src/components/features/rules/RuleBuilder/Header/EditorGroupDropdown/EditorGroupDropdown.css
app/src/components/features/rules/RuleBuilder/Header/EditorGroupDropdown/GroupMenuItem.tsx
app/src/components/features/rules/RuleBuilder/Header/EditorGroupDropdown/index.tsx
app/src/components/features/rules/RuleBuilder/Header/index.js
app/src/lib/design-system/components/RQDropdown/RQDropdown.css
app/src/lib/design-system/theme.js

Closes issue: 
- Improves rule editor group dropdown UX
https://user-images.githubusercontent.com/61556757/220602659-5bff3287-0f26-4f05-b305-7a8816690e01.mov

RQLY-1205: improve group menu in rule editor

---

app/src/components/features/mocksV2/MockEditor/Editor/index.tsx
app/src/components/features/mocksV2/MockEditor/types.ts
app/src/lib/design-system/components/RQEditorTitle/RQEditorTitle.css
app/src/lib/design-system/components/RQEditorTitle/index.tsx
app/src/lib/design-system/custom/base.css

Closes issue: 
https://app.requestly.io/sessions/saved/iXnMMusuEIAosDO6XLUz

RQLY-1200 add fields validation in mock server editor

---

app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/RequestSourceRow/index.js

RQLY-1206: fix dropdown selections in rule editors

---

browser-extension/mv2/src/background/background.js
browser-extension/mv2/src/client/js/consoleLoggerHandler.js

fix: typos in console logger handler

---

app/src/components/features/rules/RuleBuilder/Header/ActionButtons/CreateRuleButton/actions/index.js
app/src/components/features/rules/RuleBuilder/Header/ActionButtons/CreateRuleButton/index.js
app/src/components/features/rules/RulePairs/Filters/index.js
app/src/layouts/DashboardLayout/Sidebar/index.js
browser-extension/mv2/src/client/js/ruleMatcher.js
browser-extension/mv2/src/shared/utils.js
browser-extension/mv2/tests/specs/utils.spec.js
browser-extension/mv3/src/service-worker/services/ruleMatcher.ts

RQLY-1201: validation on saving bad regex

---

app/src/layouts/DashboardLayout/Sidebar/SideBarHeader/index.tsx
app/src/layouts/DashboardLayout/Sidebar/WorkspaceSelector/index.jsx

fix: workspace switch

---

app/src/components/features/rules/RulePairs/Pairs/HeadersRulePair/HeadersRulePairV2/HeadersPairModificationRowV2.js
app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/CustomScriptRow/index.js
app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/QueryParamModificationRow/index.js
app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/UserAgentSelectionRow/index.js
app/src/components/features/sharedLists/CreateSharedListModal/index.js

fix: click events in rule editor dropdown and shared list copy button

---

app/src/components/features/rules/RuleBuilder/Header/EditorGroupDropdown/GroupMenuItem.tsx
app/src/components/features/rules/RuleBuilder/Header/EditorGroupDropdown/index.tsx

RQLY-1245: fix group update action in rule editor

---

app/package-lock.json
app/package.json

RQLY-1241: fix: duplication of monaco-editor

---

app/src/components/features/rules/RuleBuilder/Header/EditorGroupDropdown/index.tsx
app/src/types/rules.ts

RQLY-1246: fix selected group order in rule editor

---

app/src/components/features/mocksV2/MockList/MocksTable/index.tsx

RQLY-1238 fix: mock table method/type col header name

---

app/src/components/features/mocksV2/MockEditor/Editor/index.tsx
app/src/components/features/mocksV2/MockEditor/utils.ts

RQLY-1250:fix mock endpoint and status code field validation

---

app/src/components/features/sharedLists/CreateSharedListModal/PostConfirmationModal/index.js
app/src/components/features/sharedLists/CreateSharedListModal/index.js
app/src/modules/analytics/events/features/sharedList/index.js

RQLY-1202: fix sharedList name creation for single rule

---

app/src/components/features/rules/DeleteRulesModal/index.js
app/src/components/features/rules/ExportRulesModal/index.js
app/src/components/features/rules/RuleBuilder/Header/index.js
app/src/components/features/rules/RulesListContainer/RulesTable/index.js

RQLY-1249: fix rule deletion from editor

---

app/src/components/landing/ruleSelection/RuleList/index.tsx
app/src/components/landing/ruleSelection/RuleList/ruleList.css
app/src/styles/custom/custom.css

RQLY-1248: custom scrollbar

---

app/src/components/features/rules/RulesListContainer/RulesTable/index.js
app/src/components/features/rules/RulesListContainer/RulesTable/rulesTable.css
app/src/components/features/rules/UngroupOrDeleteRulesModal/index.js

RQLY-1199: cleanup ungroup functionality

---

app/src/components/features/mocksV2/MockEditor/Editor/index.css
app/src/components/features/mocksV2/MockEditor/Editor/index.tsx
app/src/components/features/mocksV2/MockList/MocksTable/index.tsx
app/src/components/features/mocksV2/utils/index.ts
app/src/components/features/rules/RuleBuilder/Body/index.js
app/src/lib/design-system/components/RQEditorTitle/RQEditorTitle.css
app/src/lib/design-system/components/RQEditorTitle/index.tsx
app/src/styles/custom/custom.scss

RQLY-1235 add file-type tag in file server editor 

---

app/src/components/misc/PersonaSurvey/utils.ts

RQLY-1140-change persona survey modal ref release date

---

app/src/components/misc/PersonaSurvey/ModalFooter.tsx
app/src/components/misc/PersonaSurvey/Recommendations/index.css
app/src/components/misc/PersonaSurvey/Recommendations/index.tsx
app/src/components/misc/PersonaSurvey/config.tsx
app/src/components/misc/PersonaSurvey/index.css
app/src/components/misc/PersonaSurvey/index.tsx
app/src/components/misc/PersonaSurvey/types.ts
app/src/layouts/DashboardLayout/DashboardContent.js
app/src/modules/analytics/events/common/constants.js
app/src/modules/analytics/events/misc/constants.js
app/src/modules/analytics/events/misc/personaSurvey.ts

RQLY-1270 Persona survey enhancements 

---

app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/MembersDetails/index.js
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/index.js
app/src/layouts/DashboardLayout/Sidebar/WorkspaceSelector/index.jsx
app/src/utils/getColorFromString.js
app/src/utils/getColorFromString.ts
app/src/utils/teams/index.ts

Closes issue: 
https://user-images.githubusercontent.com/61556757/224238300-ad443d8a-d98b-4c64-8e6b-56b8605e21f8.mov

RQLY-1264: add color to workspace avatars

---

app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/MembersDetails/AddMemberModal/AddMemberModal.css
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/MembersDetails/AddMemberModal/index.jsx

fix(style): workspace add member modal email input

---

app/src/layouts/DashboardLayout/Sidebar/WorkspaceSelector/index.jsx

Closes issue: 
https://user-images.githubusercontent.com/61556757/224646362-e744e8ad-4769-4dee-8b78-14629f56abd2.mov

RQ-53: workspace switch from resource editor

---

app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/TeamSettings/TeamSettings.css
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/TeamSettings/WorkspaceStatusSyncing/index.js
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/TeamSettings/index.js
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/index.js
app/src/views/user/Settings/GlobalSettings/index.js

RQ-27: move `Sync Rule Status` setting in workspace settings

---

app/src/components/misc/PersonaSurvey/ModalFooter.tsx

RQ-37-hide recommendation screen for shared list importers

---

app/src/components/misc/PersonaSurvey/ModalFooter.tsx
app/src/components/misc/PersonaSurvey/Option/index.tsx
app/src/components/misc/PersonaSurvey/config.tsx
app/src/components/misc/PersonaSurvey/index.tsx
app/src/components/misc/PersonaSurvey/types.ts
app/src/components/misc/PersonaSurvey/utils.ts

RQ-38 Add randomness in persona survey options

---

app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/CreateWorkspaceModal/index.jsx
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/BillingDetails/SubscriptionActionButtons/index.js
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/MembersDetails/AddMemberModal/index.jsx
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/index.js
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamsList/index.js
app/src/layouts/DashboardLayout/Sidebar/WorkspaceSelector/index.jsx
app/src/modules/analytics/events/common/constants.js
app/src/modules/analytics/events/common/teams/index.js

RQ-57-add workspace analytics

---

app/src/backend/mocks/createMock.ts
app/src/backend/mocks/updateMock.ts
app/src/components/common/UserIcon/index.tsx
app/src/components/features/mocksV2/MockList/MocksTable/index.css
app/src/components/features/mocksV2/MockList/MocksTable/index.tsx
app/src/components/features/mocksV2/types.ts
app/src/components/features/rules/RulesListContainer/RulesTable/index.js

RQ-67-add created by and modified by in workspace mocks

---

app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/MembersDetails/AddMemberModal/index.jsx
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/MembersDetails/TeamMembersTable/RemoveUserModal/index.jsx
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/MembersDetails/TeamMembersTable/index.js
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/common/MemberRoleDropdown/index.tsx

Closes issue: 
https://user-images.githubusercontent.com/61556757/225327913-9f60475e-b01f-4280-bd16-b03c27a7476c.mov

RQ-51: feat `Leave workspace` option in teams

---

app/src/views/features/sessions/SessionsIndexPageContainer/SessionsIndexPage/RecordingsList/index.js
app/src/views/features/sessions/SessionsIndexPageContainer/SessionsIndexPage/index.js

1. Remove created by in private workspace
2. Fix pagination issue in teams session list

fix: bugs in session recording teams

---

app/src/components/features/rules/RuleBuilder/Header/ActionButtons/PinButton/index.jsx
app/src/components/features/rules/RuleBuilder/Header/ActionButtons/Status/index.js

fix: RQ-28 change in modification date when toggled from editor

---

app/src/views/features/rules/RuleSimulatorContainer/RuleSimulator/index.js

RQ-86: test rule without saving

---

app/src/components/features/rules/RulePairs/ResponseRuleResourceTypes/index.tsx

RQ-88: fix - unexpected unsaved rule indication for legacy response rules

---

app/src/components/features/rules/RulePairs/Pairs/ResponseRulePair/GraphqlRequestPayload/GraphqlRequestPayload.css
app/src/components/features/rules/RulePairs/Pairs/ResponseRulePair/GraphqlRequestPayload/index.tsx

RQ-83: modify response rule improvements

---

app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/RequestBodyRow/index.js
app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/ResponseBodyRow/index.js
app/src/utils/CodeEditorUtils.js

RQ-87- Support for JS objects in Static body in response and request rules

---

app/src/components/landing/ruleTemplates/RulePreviewModal/index.js

RQ-92: fix templates creation

---

app/src/components/misc/PersonaSurvey/config.tsx

RQ-91:add ChatGPT option in persona survey q3

---

app/src/components/misc/PersonaSurvey/Recommendations/personalizations.tsx
app/src/components/misc/PersonaSurvey/config.tsx
app/src/components/misc/PersonaSurvey/types.ts
app/src/components/misc/PersonaSurvey/utils.ts

RQ-95: Add full-stack and remove founder option from survey q1

---

app/package-lock.json
app/package.json
app/src/components/features/mocksV2/MockEditor/Editor/AIResponseModal/index.css
app/src/components/features/mocksV2/MockEditor/Editor/AIResponseModal/index.tsx
app/src/components/features/mocksV2/MockEditor/Editor/index.css
app/src/components/features/mocksV2/MockEditor/Editor/index.tsx

Mock Server Improvements

---

app/src/components/misc/PersonaSurvey/ModalFooter.tsx
app/src/components/misc/PersonaSurvey/actions.ts
app/src/components/misc/PersonaSurvey/config.tsx
app/src/components/misc/PersonaSurvey/index.tsx
app/src/components/misc/PersonaSurvey/utils.ts
app/src/config/constants/sub/analytics.js
app/src/modules/analytics/events/misc/personaSurvey.ts
app/src/store/features/userActions.js
app/src/store/initial-state/index.js

RQ-94 Change persona survey Q3

---

app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/DestinationURLRow/index.css
app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/DestinationURLRow/index.js
app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/RequestSourceRow/index.js
app/src/components/misc/MoreInfo/index.css
app/src/components/misc/MoreInfo/index.tsx
app/src/config/constants/sub/links.js
app/src/modules/analytics/events/misc/constants.js
app/src/modules/analytics/events/misc/moreInfo.ts

RQ-74: more info icon and tooltip in redirect rule

---

app/src/layouts/DashboardLayout/Sidebar/Sidebar.css
app/src/layouts/DashboardLayout/Sidebar/WorkspaceSelector/index.jsx

RQ-113: fix: made sidebar sticky and delay tootltip on workspace selector

---

app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/DestinationURLRow/index.js

RQ-82 disable destination switch and file selector in preview mode

---

app/src/config/PageScriptMessageHandler.js
app/src/modules/analytics/events/extension.ts
app/src/modules/analytics/index.js
browser-extension/common/package-lock.json
browser-extension/common/package.json
browser-extension/common/rollup.config.js
browser-extension/common/src/analytics/eventUtils.ts
browser-extension/common/src/utils.ts
browser-extension/mv2/jsList.json
browser-extension/mv2/src/background/background.js
browser-extension/mv2/src/modules/EventActions.js

- batched sending of events
- generateUUID utility created
- cleanup and reorder EventActions.js
- create event handler on UI
- handle acknowledgements

Batched acknowledged based event sending from background to UI

---

app/src/backend/teams/getTeamInvites.ts
app/src/backend/teams/index.ts
app/src/components/misc/Invite/AcceptInvite.tsx
app/src/components/misc/Invite/index.tsx
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/JoinWorkspaceModal/JoinWorkspaceModal.css
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/JoinWorkspaceModal/index.tsx
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/MembersDetails/index.js
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamsList/index.js
app/src/layouts/DashboardLayout/Sidebar/WorkspaceSelector/WorkSpaceSelector.css
app/src/layouts/DashboardLayout/Sidebar/WorkspaceSelector/index.jsx
app/src/modules/analytics/events/features/constants.js
app/src/modules/analytics/events/features/teams/index.js
app/src/styles/custom/custom.scss
app/src/types/index.ts
app/src/types/invite.ts
app/src/types/teamWorkspace.ts

Closes issue: 
https://user-images.githubusercontent.com/61556757/229145132-08522812-62f8-4a08-a8d5-88ed1ba4925e.mov

RQ-102: direct joining workspace from app

---

app/src/components/features/rules/RuleBuilder/Help/index.tsx
app/src/components/features/rules/RuleBuilder/index.js
app/src/components/misc/MoreInfo/index.tsx
app/src/components/misc/ProductWalkthrough/index.tsx
app/src/store/features/userActions.js
app/src/store/index.js
app/src/store/initial-state/index.js
app/src/store/selectors.js

Added A/B flag for Redirect Rule Onboarding flow
- Control
- Tour
- Tooltip
- Docs

RQ-72: Redirect rule onboarding experiment

---

app/src/components/features/rules/RuleBuilder/index.js

RQ-73-Fix walkthrough toggle

---

app/src/components/features/rules/RuleBuilder/Header/ActionButtons/index.js

Reverts requestly/requestly#471

Revert "hide: hot-fix-hide-editor-share-button"

---

app/src/lib/design-system/components/RQEditorTitle/RQEditorTitle.css

RQ-154: fix edit icon for editor title field

---

browser-extension/mv2/src/background/background.js
browser-extension/mv2/src/client/js/ruleExecutionHandler.js

- fixes the errors in extension runtime messages
- send message to sync applied rules in content script only when rules are cached

fix: extension runtime message errors

---

app/src/components/features/rules/RuleBuilder/index.js

Track docs sidebar viewewd event

---

app/src/config/PageScriptMessageHandler.js
app/src/hooks/useAppModeInitializer.js
app/src/modules/analytics/events/extension.ts

RQ-97 Extension Analytics - Fixed Cyclic dependency issue

---

app/src/config/PageScriptMessageHandler.js
browser-extension/mv2/src/shared/ContentScriptMessageHandler.js

fix: removal of extension message callback

---

app/src/components/features/rules/GettingStarted/PersonaRecommendation/FeatureCard/FeatureCard.css
app/src/components/features/rules/GettingStarted/PersonaRecommendation/FeatureCard/index.tsx
app/src/components/features/rules/GettingStarted/PersonaRecommendation/PersonaRecommendation.css
app/src/components/features/rules/GettingStarted/PersonaRecommendation/index.tsx
app/src/components/features/rules/GettingStarted/PersonaRecommendation/personaRecommendationData.tsx
app/src/components/features/rules/GettingStarted/PersonaRecommendation/types.ts
app/src/components/features/rules/GettingStarted/index.js
app/src/components/misc/PersonaSurvey/ModalFooter.tsx
app/src/components/misc/PersonaSurvey/Recommendations/index.tsx
app/src/components/misc/PersonaSurvey/config.tsx
app/src/components/misc/PersonaSurvey/index.tsx
app/src/components/misc/PersonaSurvey/types.ts
app/src/layouts/DashboardLayout/DashboardContent.js
app/src/layouts/DashboardLayout/index.js
app/src/modules/analytics/events/common/constants.js
app/src/modules/analytics/events/misc/constants.js
app/src/modules/analytics/events/misc/personaSurvey.ts

RQ-126: persona recommendation experiment

---

app/src/utils/rules/misc.js
app/src/views/features/rules/RuleSimulatorContainer/RuleSimulator/index.js

RQ-157 fix: test this rule for header rule

---

app/src/layouts/DashboardLayout/Sidebar/MenuItem/index.js
app/src/layouts/DashboardLayout/Sidebar/Sidebar.css

RQ-150: reordered items in sidebar

---

app/src/config/constants/sub/rule-editor-selectors.ts
app/src/types/rules.ts

RQ-161: add field selectors for each rule type

---

app/src/components/common/RuleEditorModal/index.tsx
app/src/components/features/rules/NewRuleSelector/index.js
app/src/components/features/rules/RuleBuilder/Header/ActionButtons/CreateRuleButton/index.js
app/src/components/features/rules/RulesListContainer/index.js
app/src/components/landing/ruleSelection/RuleHeader/index.tsx
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/ContextMenu.tsx
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.js
app/src/components/mode-specific/desktop/MySources/Sources/index.js
app/src/modules/analytics/events/common/rules/index.js
app/src/modules/analytics/events/desktopApp/constants.js
app/src/modules/analytics/events/desktopApp/index.js

RQ-162: analytics for rule creation through traffic table

---

app/src/components/features/rules/RuleBuilder/Header/ActionButtons/CreateRuleButton/index.js
app/src/components/features/rules/RuleBuilder/Header/ActionButtons/RuleEditorActionButtons.css

RQ-164: close rule created toast for editor modal on button click

---

app/src/components/common/RuleEditorModal/index.tsx
app/src/components/features/rules/RuleBuilder/Header/ActionButtons/CreateRuleButton/index.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.js

RQ-164 hide rule created toast on view rule click

---

app/src/components/misc/ProductWalkthrough/index.tsx
app/src/modules/analytics/events/misc/productWalkthrough.ts

RQ:162 fix tour analytics

---

app/src/components/common/RuleEditorModal/RuleEditorModal.css
app/src/components/common/RuleEditorModal/index.tsx
app/src/components/features/rules/RuleBuilder/Header/ActionButtons/RuleEditorActionButtons.css
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/ContextMenu.tsx

fix dropdown and toast style

---

app/src/components/mode-specific/desktop/MySources/Sources/index.css
app/src/components/mode-specific/desktop/MySources/Sources/index.js
app/src/layouts/DashboardLayout/DashboardContent.js
app/src/lib/design-system/custom/base.css
app/src/store/initial-state/index.js
app/src/store/initial-state/sub/appsList.json
app/src/styles/custom/custom.scss

Closes issue: 
https://user-images.githubusercontent.com/53986600/231057547-294756ed-e275-41ee-9fd8-d6e3e06efc18.mp4

RQ:143 Connected apps modal

---

app/src/components/misc/PersonaSurvey/ModalFooter.tsx

RQ-172: Remove persona recommendations from desktop app

---

app/src/utils/rules/misc.js

fix desktop only rule check in rule editor

---

app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/AddCustomScriptRow/AddCustomScriptRow.css
app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/AddCustomScriptRow/index.js

RQ-163-fix add custom script button in rule editor

---

app/src/components/mode-specific/desktop/MySources/Sources/index.css
app/src/components/mode-specific/desktop/MySources/Sources/index.js
app/src/lib/design-system/custom/variables.css

Connected apps modal chore fixes

---

app/src/components/misc/PersonaSurvey/Recommendations/personalizations.tsx
app/src/components/misc/PersonaSurvey/config.tsx
app/src/components/misc/PersonaSurvey/types.ts

RQ-194 :add sales role in persona survey q1

---

app/src/components/mode-specific/desktop/MySources/Sources/index.js

RQ-200: fix track interception started event

---

app/src/components/misc/PersonaSurvey/ModalFooter.tsx
app/src/components/misc/PersonaSurvey/index.tsx
app/src/modules/analytics/events/misc/personaSurvey.ts

RQ-199: hide survey modal in experiment recommendation screen

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/FixedRequestLogPane.css
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/FixedRequestLogPane.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/Preview/PayloadPreview.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.js
app/src/styles/custom/custom.scss

Closes issue: 
https://user-images.githubusercontent.com/61556757/231671392-37425bb4-fc4d-40a4-9e86-09720049d563.mov

fix(style): request log pane

---

app/src/components/mode-specific/desktop/InterceptTraffic/InterceptTraffic.css
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/ActionHeader.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/NetworkTable/index.tsx
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/Tables/GroupByNone.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/TrafficTableV2.css
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/utils/logUtils.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/index.js
app/src/components/mode-specific/desktop/InterceptTraffic/index.jsx
app/src/layouts/DashboardLayout/Sidebar/index.js
app/src/utils/PathUtils.js
app/src/utils/TrafficTableUtils.js

Closes issue: 
https://user-images.githubusercontent.com/61556757/231407043-d7b80240-5762-4c10-a9b4-ed49ef8d02c9.mov

RQ-166: traffic table sidebar

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/ActionHeader.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.js
app/src/store/constants.ts
app/src/store/features/desktop-traffic-table/selectors.ts
app/src/store/features/desktop-traffic-table/slice.ts
app/src/store/index.js
app/src/types/desktopApp/trafficTable/index.ts

[RQ-151] feat: traffic table persistence in desktop app

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/TrafficTableV2.css
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/utils/logUtils.js

RQ-204: fix traffic table group unselect

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/constant.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.js
app/src/modules/analytics/events/common/constants.js
app/src/modules/analytics/events/common/traffic-table/index.js

RQ-208: add traffic table sidebar filter analytics

---

app/src/layouts/DashboardLayout/Sidebar/SideBarHeader/index.tsx
app/src/layouts/DashboardLayout/Sidebar/WorkspaceSelector/index.jsx

Closes issue: https://github.com/requestly/requestly/issues/531

RQ-202: create / join workspace dropdown overlapped when sidebar is collapsed

---

app/src/components/common/RuleEditorModal/index.tsx
app/src/components/features/rules/DeleteRulesModal/index.js
app/src/components/features/rules/RuleBuilder/Header/ActionButtons/CreateRuleButton/index.js
app/src/components/features/rules/RuleBuilder/Header/ActionButtons/DeleteButton/index.jsx
app/src/components/features/rules/RuleBuilder/Header/ActionButtons/ExportButton/index.jsx
app/src/components/features/rules/RuleBuilder/Header/ActionButtons/PinButton/index.jsx
app/src/components/features/rules/RuleBuilder/Header/ActionButtons/ShareRuleButton/index.jsx
app/src/components/features/rules/RuleBuilder/Header/ActionButtons/Status/index.js
app/src/components/features/rules/RuleBuilder/Header/ActionButtons/index.js
app/src/components/features/rules/RuleBuilder/Header/RuleOptions/index.jsx
app/src/components/features/rules/RuleBuilder/Header/index.js
app/src/components/features/rules/RuleBuilder/index.js
app/src/components/features/rules/RulePairs/Pairs/HeadersRulePair/HeadersRulePairV2/index.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/Tables/columns/AppliedRules.js
app/src/modules/analytics/events/common/rules/index.js
app/src/utils/rules/misc.js
app/tsconfig.json

RQ-153: open applied rules in editor modal

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/TrafficTableV2.css
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.js
app/src/styles/custom/postMigrationCustom.scss

RQ-236: hide persistent alert from traffic table 

---

app/src/components/authentication/DesktopSignIn/index.js
app/src/components/features/rules/GettingStarted/index.js
app/src/components/misc/PersonaSurvey/utils.ts

RQ-232: fix persona survey flow for desktop app

---

app/src/components/authentication/DesktopSignIn/index.js

RQ-232: fix persona sync on browser when authenticating from dektop app

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/NetworkTable/VirtualTable.tsx

RQ-242 highlight log in traffic table when right-clicked

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/ActionHeader.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/FixedRequestLogPane.css
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/FixedRequestLogPane.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/TrafficTableV2.css
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.js

RQ-247: traffic table style fix

---

app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/DestinationURLRow/index.js
app/src/components/misc/MoreInfo/index.tsx
app/src/modules/analytics/events/misc/moreInfo.ts

RQ-244 fix more info icon/tooltip events

---

app/src/config/constants/sub/email-domains.js

RQ-226:update destroyable email domains

---

app/src/components/features/rules/RuleBuilder/index.js
app/src/components/misc/ProductWalkthrough/constants.ts
app/src/components/misc/ProductWalkthrough/index.tsx
app/src/components/misc/ProductWalkthrough/tours.tsx
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/ContextMenu/index.tsx
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/NetworkTable/index.tsx
app/src/components/sections/Navbars/NavbarRightContent/DesktopAppProxyInfo/index.jsx
app/src/config/constants/sub/features.js
app/src/layouts/DashboardLayout/MenuHeader/HeaderText.jsx
app/src/layouts/DashboardLayout/MenuHeader/utils.ts
app/src/store/features/userActions.js
app/src/store/initial-state/index.js
app/src/store/selectors.js

RQ-227 connected apps tour

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/Tables/GroupByNone.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.js

RQ-241 Improve empty state when no request matches the filter

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/ActionHeader.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/FixedRequestLogPane.css
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/TrafficTableV2.css
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.js

Closes issue: 
https://user-images.githubusercontent.com/53986600/235641026-85e1208d-68c6-4f08-9f55-57a1abf5c47f.mp4

RQ-258: Regex support in Desktop App Traffic Table Search

---

browser-extension/mv2/src/client/js/ruleExecutionHandler.js

chore: disable rule execution event

---

app/package-lock.json
app/package.json
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.js
app/src/store/features/desktop-traffic-table/slice.ts
app/src/store/index.js

Closes issue: 
- added autoBatchEnhancer in desktop app traffic table. This improves traffic table performance by batching the redux subscriptions.

[RQ-245] improve traffic table performance using autoBatchEnhancer

---

app/src/utils/charles-rule-adapters/block-cookies/header-config.ts
app/src/utils/charles-rule-adapters/block-cookies/index.ts
app/src/utils/charles-rule-adapters/getXmlToJs.ts
app/src/utils/charles-rule-adapters/no-caching/index.ts
app/src/utils/charles-rule-adapters/types.ts
app/src/utils/charles-rule-adapters/utils.ts

RQ-270: adapter for Charles block-cookies rule

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/TrafficTableV2.css
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.js
app/src/modules/analytics/events/common/constants.js
app/src/modules/analytics/events/common/traffic-table/index.js

Closes issue: 
https://user-images.githubusercontent.com/61556757/234861926-6df1c9f0-bbf8-4a1d-a210-fb1abd9d803a.mov

RQ-252: support multiple selection in traffic table sidebar for app/domain filter

---

app/src/components/features/rules/ChangeRuleGroupModal/actions/index.js
app/src/utils/charles-rule-adapters/block-cookies/index.ts
app/src/utils/charles-rule-adapters/getXmlToJs.ts
app/src/utils/charles-rule-adapters/map-remote/index.ts
app/src/utils/charles-rule-adapters/no-caching/index.ts
app/src/utils/charles-rule-adapters/types.ts
app/src/utils/charles-rule-adapters/utils.ts

RQ-273: map-remote rule adapter

---

app/src/utils/charles-rule-adapters/getXmlToJs.ts
app/src/utils/charles-rule-adapters/index.ts
app/src/utils/charles-rule-adapters/map-local/index.ts
app/src/utils/charles-rule-adapters/map-remote/index.ts
app/src/utils/charles-rule-adapters/types.ts

RQ-274: map-local rule adapter

---

app/src/components/features/rules/RuleBuilder/index.js
app/src/utils/charles-rule-adapters/block-cookies/index.ts
app/src/utils/charles-rule-adapters/block-list/index.ts
app/src/utils/charles-rule-adapters/getXmlToJs.ts
app/src/utils/charles-rule-adapters/types.ts

RQ-271: adapter for Charles block list rules

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/ContextMenu/index.tsx
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/NetworkTable/VirtualTable.tsx
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/NetworkTable/VirtualTableV2.tsx
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/NetworkTable/index.tsx

RQ-260 Replay Request Support in Desktop App

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/NetworkTable/VirtualTableV2.tsx
app/src/store/features/desktop-traffic-table/slice.ts

feat: add new desktop app traffic table logs in bottom

---

app/src/components/misc/ProductWalkthrough/tours.tsx
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/ContextMenu/index.tsx
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/NetworkTable/index.tsx
app/src/components/sections/Navbars/NavbarRightContent/DesktopAppProxyInfo/index.jsx
app/src/styles/custom/postMigrationCustom.scss

RQ-268 : start connected apps tour when interception starts

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/ContextMenu/index.tsx

RQ-268: chore connected apps tour merge commit

---

app/src/components/features/rules/GettingStarted/index.js
app/src/components/features/rules/ImportFromCharlesModal/ImportFromCharlesModal.css
app/src/components/features/rules/ImportFromCharlesModal/index.tsx

fix import modal content

---

app/src/modules/charles-rule-adapters/block-cookies/index.ts
app/src/modules/charles-rule-adapters/block-list/index.ts
app/src/modules/charles-rule-adapters/map-local/index.ts
app/src/modules/charles-rule-adapters/map-remote/index.ts
app/src/modules/charles-rule-adapters/no-caching/index.ts
app/src/modules/charles-rule-adapters/rewrite/actions.ts

fix(typo): charles imported rules 

---

app/src/components/features/rules/GettingStarted/index.js
app/src/components/features/rules/ImportFromCharlesModal/ImportFromCharlesModal.css
app/src/components/features/rules/ImportFromCharlesModal/index.tsx
app/src/components/features/rules/ImportRulesModal/index.js

RQ-311: add import from charles touch point on rules list page

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/ActionHeader.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/NetworkTable/NoTrafficCTA.jsx
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/NetworkTable/VirtualTableV2.tsx
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/NetworkTable/index.tsx
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/Tables/GroupByNone.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.js
app/src/modules/analytics/events/desktopApp/constants.js
app/src/modules/analytics/events/desktopApp/index.js
app/src/store/features/desktop-traffic-table/selectors.ts
app/src/store/features/desktop-traffic-table/slice.ts

RQ-278: traffic table filters persistance

---

app/package-lock.json
app/package.json

chore: install `1flow` js sdk

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.js

RQ-278: fix: null check when grouping traffic table logs

---

browser-extension/mv2/_locales/en/messages.json

RQ-309 Extension: Update Title & Description

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/NetworkTable/NoTrafficCTA.jsx

RQ-178: fix empty table placeholder

---

app/src/actions/TeamWorkspaceActions.js
app/src/hooks/ActiveWorkspace.js
app/src/hooks/AppModeInitializer.js
app/src/hooks/DbListenerInit/DBListeners.js
app/src/hooks/DbListenerInit/syncingNodeListener.js
app/src/utils/Toast.js
app/src/utils/syncing/SyncUtils.js
app/src/utils/syncing/syncDataUtils.js
browser-extension/common/src/constants.ts
browser-extension/common/src/popup/contexts/RecordsContext/index.tsx
browser-extension/mv2/src/background/background.js
browser-extension/mv2/src/modules/EventActions.js
browser-extension/mv2/src/pages/init.js
browser-extension/mv2/src/shared/constants.js
common/constants.js

* send notify event from extension popup on rule toggle
* generalized [ext] sendMessage to app function
* remove comments
* added comment
* add handler for NOTIFY_RECORD_UPDATED
* move sync-target detection logic to syncingNodeListener
* separate out fn: invokeSyncingIfRequired
* util: react toast all open tabs
* add listener for /rulesConfig node
* improve rule status syncing in team
* remove: console logs
---------
Closes issue:

Realtime rule toggle popup: refactored messaging to app (#570)

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/FixedRequestLogPane.css
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/FixedRequestLogPane.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/Preview/JsonPreviewV2.tsx

JSON preview in traffic table 
https://github.com/requestly/requestly/assets/57226514/ced54331-1a80-48e6-ae61-ec486fccfb4a

chore: replace old json preview+editor with better looking preview

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/ActionHeader.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/FixedRequestLogPane.css
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.js
app/src/lib/design-system/custom/base.css

RQ-322: fix traffic table header action buttons UI

---

app/src/components/common/RuleEditorModal/prefill.ts
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/ContextMenu/index.tsx

RQ-333: autofill body when creating modify response/request body rule from traffic table

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/NetworkTable/VirtualTableV2.tsx
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/NetworkTable/index.tsx
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.js

Closes issue: 
- Improved initial lag when rendering large number of rows
- Changed default column sizes

[RQ-245] improvement: improve desktop app table performance

---

app/src/components/authentication/AuthForm/AuthForm.css
app/src/components/features/mocksV2/MockEditor/Editor/index.css
app/src/components/features/mocksV2/MockList/MocksTable/index.css
app/src/components/features/rules/GettingStarted/gettingStarted.css
app/src/components/features/rules/RuleBuilder/Header/ActionButtons/CreateRuleButton/index.js
app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/AddCustomScriptRow/index.js
app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/CustomScriptRow/index.js
app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/DestinationURLRow/index.css
app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/DestinationURLRow/index.js
app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/RequestBodyRow/index.js
app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/ResponseBodyRow/ResponseBodyRow.css
app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/ResponseBodyRow/index.js
app/src/components/features/rules/RulePairs/RulePairs.css
app/src/components/features/rules/RulePairs/index.js
app/src/components/features/rules/RulesListContainer/RulesTable/index.js
app/src/components/hoc/auth/AuthConfirmationPopover/index.js
app/src/components/hoc/auth/AuthConfirmationPopover/popover.scss
app/src/components/mode-specific/desktop/misc/FileDialogButton.js
app/src/modules/analytics/events/common/rules/index.js
app/src/utils/rules/misc.js

RQ-379 RQ-424: Fix UI issues

---

app/src/components/features/rules/GettingStarted/PersonaRecommendation/index.tsx
app/src/components/features/rules/GettingStarted/index.js
app/src/components/hoc/auth/AuthConfirmationPopover/index.js
app/src/components/misc/PersonaSurvey/utils.ts
app/src/store/features/userActions.js

RQ-427 fix persona recommendation visibility bug

---

app/package-lock.json
app/package.json
app/src/components/features/rules/RuleBuilder/Help/Help.css
app/src/components/features/rules/RuleBuilder/Help/index.tsx
app/src/components/features/rules/RuleBuilder/Help/types.ts
app/src/components/features/rules/RuleBuilder/index.js

RQ-381: Add docs for all rule editors

---

app/src/components/features/rules/RuleBuilder/Help/index.tsx

RQ-468 Add fallback endpoints for rule editor doc maps

---

app/src/components/features/rules/RuleBuilder/index.js
app/src/routes/ruleRoutes.tsx
app/src/views/features/rules/RuleEditor/index.js

RQ-445: `window.location` prop cleanup

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/FixedRequestLogPane.js

RQ-474 Desktop app: Improve switching in Inspect Traffic

---

app/src/layouts/DashboardLayout/DashboardContent.js
app/src/layouts/DashboardLayout/index.jsx

[RQ-503] fix: stuck on getting-started screen on desktop app

---

app/src/components/authentication/AuthForm/AuthForm.css
app/src/components/authentication/AuthForm/AuthFormHero.js
app/src/components/features/rules/GettingStarted/PersonaRecommendation/FeatureCard/index.tsx
app/src/components/features/rules/GettingStarted/PersonaRecommendation/index.tsx
app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/BannerSteps/index.css
app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/BannerSteps/index.tsx
app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/OnboardingSteps/PersonaSurvey/GettingStartedWithSurvey.tsx
app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/OnboardingSteps/PersonaSurvey/index.css
app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/OnboardingSteps/TeamWorkspaces/Banner/index.tsx
app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/OnboardingSteps/TeamWorkspaces/Footer.tsx
app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/OnboardingSteps/TeamWorkspaces/WorkspaceCreation.tsx
app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/OnboardingSteps/TeamWorkspaces/index.css
app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/OnboardingSteps/TeamWorkspaces/index.tsx
app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/index.css
app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/index.tsx
app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/types.ts
app/src/components/features/rules/GettingStarted/index.js
app/src/lib/design-system/custom/base.css
app/src/store/features/userActions.js
app/src/store/selectors.js
app/src/styles/custom/custom.css

RQ-437 workspace creation and invite flow in onboarding

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/FixedRequestLogPane.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/NetworkTable/VirtualTableV2.tsx
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/NetworkTable/index.tsx
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/Preview/PayloadPreview.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.js
app/src/lib/design-system/components/RQCollapse/index.tsx

RQ-474 Desktop app: Add memoization in Table component

---

app/src/layouts/DashboardLayout/MenuHeader/index.js

fix: hide promo on desktop app

---

app/src/views/features/sessions/SessionsIndexPageContainer/NetworkSessions/NetworkSessionViewer.tsx

Changed the text in NetworkSessionViewer.tsx from 'Export as HAR' to 'Download HAR'

#728 Issue: Updated Text

---

app/src/layouts/DashboardLayout/Sidebar/PrimarySidebar/index.tsx
app/src/layouts/DashboardLayout/Sidebar/type.ts
app/src/utils/Toast.js
app/src/views/features/sessions/SessionsIndexPageContainer/NetworkSessions/SessionSaveModal.tsx

Closes issue: 
https://github.com/requestly/requestly/assets/61556757/6ecb8914-6c50-4027-a51b-b3b1e4ef2f66

RQ-526: fix network session saved toast and tooltip

---

app/src/components/features/rules/RuleBuilder/Body/RuleInfoBanner/index.tsx
app/src/components/features/rules/RuleBuilder/Body/RuleInfoBanner/ruleInfoBanner.css
app/src/components/features/rules/RuleBuilder/Header/ActionButtons/CreateRuleButton/actions/index.js
app/src/components/features/rules/RuleBuilder/Header/ActionButtons/CreateRuleButton/index.js

RQ-473: remove delay limit for desktop app

---

app/src/components/features/rules/GettingStarted/PersonaRecommendation/FeatureCard/index.tsx
app/src/components/features/rules/GettingStarted/PersonaRecommendation/index.tsx
app/src/components/features/rules/GettingStarted/PersonaRecommendation/personaRecommendationData.tsx
app/src/components/features/rules/GettingStarted/PersonaRecommendation/types.ts

RQ-305 API client option in Persona recommendation

---

app/src/components/common/APIClient/APIClient.tsx
app/src/components/common/APIClient/types.ts
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficExporter/harLogs/converter.ts
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficExporter/harLogs/types.ts
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficExporter/harLogs/utils.ts
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/NetworkTable/index.tsx
app/src/views/features/api-client/apiUtils.ts
app/src/views/features/sessions/SessionsIndexPageContainer/NetworkSessions/NetworkSessionViewer.tsx

RQ-515 Edit and replay not working in session HAR downloaded from Chrome

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/NetworkTable/index.tsx

Closes issue: 
https://github.com/requestly/requestly/assets/61556757/8617885c-6b42-47df-b03c-361108272b9a

RQ-516: add title attribute for traffic table cells

---

app/src/views/features/sessions/SessionsIndexPageContainer/NetworkSessions/NetworkSessionsList.jsx

Closes issue: 
- [✅] Make sure linting and unit tests pass.
- [✅] No install/build warnings introduced.
- [✅] Verified UI in browser.
- [✅] For UI changes, added/updated analytics events (if applicable).
- [✅] For changes in extension's code, manually tested in Chrome and Firefox.
- [✅] For changes in extension's code, both MV2 and MV3 are covered.
- [✅] Added/updated unit tests for this change.
- [✅] Raised pull request to update corresponding documentation (if already exists).

Change Password issue solved  #755

---

app/src/layouts/DashboardLayout/DashboardLayout.css
app/src/views/containers/common/ContainerWithSecondarySidebar/containerWithSecondarySidebar.css

RQ-544: fix layout overflow due to react tour lib

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/utils/index.ts
app/src/config/constants/sub/statusCode.js

https://github.com/requestly/requestly/assets/57226514/39be2fd7-04f5-4e7e-be56-0b5111a3ad8d

feat: filter status code by labels

---

app/src/backend/sessionRecording/getRecording.ts
app/src/views/features/sessions/SessionViewer/SavedSessionViewer.tsx

[RQ-524]: fix security issues in session recording

---

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficExporter/harLogs/converter.ts
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficExporter/harLogs/types.ts
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/FixedRequestLogPane.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/Preview/PayloadPreview.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/RequestSummary.js

so far, query params were not being sent to the UI.
This is a supporting PR for the core fix inside the proxy - https://github.com/requestly/requestly-proxy/pull/20

fix: expect query params from network logs

---

app/src/components/authentication/AuthForm/AuthForm.css
app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/index.css

RQ-437: fix auth modal bg missing

---

app/src/components/features/rules/RuleEditorSplitPane/index.js
app/src/components/features/rules/RuleEditorSplitPane/ruleEditorSplitPane.css
app/src/components/features/rules/RulesListContainer/RulesTable/index.js
app/src/components/features/rules/RulesListContainer/RulesTable/rulesTable.css
app/src/components/features/trash/TrashTableContainer/index.js
app/src/components/landing/ruleTemplates/index.js
app/src/layouts/DashboardLayout/MenuHeader/MenuHeader.css
app/src/layouts/DashboardLayout/MenuHeader/WorkspaceSelector/WorkSpaceSelector.css
app/src/layouts/DashboardLayout/MenuHeader/WorkspaceSelector/index.jsx
app/src/lib/design-system/components/RQBadge/RQBadge.css
app/src/lib/design-system/components/RQButton/RQButton.css
app/src/lib/design-system/custom/variables.css
app/src/styles/custom/custom.css
app/src/views/containers/common/SecondarySidebarLink/SecondarySidebarLink.css
app/src/views/features/rules/RuleSimulatorContainer/RuleSimulator/index.js
app/src/views/features/sessions/SessionsIndexPageContainer/SessionsIndexPage/RecordingsList/index.js

Closes issue: 
https://github.com/requestly/requestly/assets/61556757/b50e9ebf-5344-4c23-925f-fba278e016fe
https://github.com/requestly/requestly/assets/61556757/48979c67-e1ff-4ff9-ae49-d4408934c7c9
https://github.com/requestly/requestly/assets/61556757/8ca8d42f-aae6-4c74-a46b-b8745bd3181c

RQ-519: improve hover states

---

app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/MembersDetails/TeamMembersTable/index.js
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/common/PendingMemberRoleDropwdown/index.tsx

https://github.com/requestly/requestly/assets/57226514/26d558eb-c5ce-4e2b-a377-1f07c695d1d7

chore: disable revoke invite button for non admin users

---

app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/MembersDetails/AddMemberModal/index.jsx

chore: remove Email address label in add member modal

---

app/src/lib/design-system/components/RQButton/RQButton.css
app/src/lib/design-system/components/RQButton/index.tsx
app/src/styles/custom/custom.css

fix: default btn style on auth page

---

app/src/components/features/rules/RuleBuilder/Header/ActionButtons/CreateRuleButton/actions/index.js
app/src/components/features/rules/RulePairs/Pairs/ResponseRulePair/GraphqlRequestPayload/index.tsx

Closes issue: https://github.com/requestly/requestly/issues/726

#726 RQ-572 Modify API Response Rule - Make GraphQL operation filter optional

---

app/src/components/features/rules/UngroupOrDeleteRulesModal/index.js

style: fix delete group modal

---

app/src/components/features/rules/RenameGroupModal/index.js
app/src/components/features/rules/RenameGroupModal/index.scss

style: fix rename group modal

---

app/src/components/features/mocksV2/MockList/GettingStartedWithMocks/index.tsx
app/src/components/features/mocksV2/MockList/MocksTable/index.tsx
app/src/components/features/rules/RenameGroupModal/index.js
app/src/components/features/rules/RenameGroupModal/index.scss
app/src/components/features/rules/UngroupOrDeleteRulesModal/index.js
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/MembersDetails/AddMemberModal/index.jsx
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/MembersDetails/TeamMembersTable/index.js
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/common/PendingMemberRoleDropwdown/index.tsx

Minor UI styling and copy issues

Minor bug fixes

---

app/src/components/features/rules/RuleBuilder/Header/ActionButtons/Status/index.js
app/src/components/features/rules/RulesListContainer/RulesTable/index.js
app/src/components/misc/ProductWalkthrough/Tooltip/index.tsx
app/src/components/misc/ProductWalkthrough/constants.ts
app/src/components/misc/ProductWalkthrough/tours.tsx
app/src/components/misc/ProductWalkthrough/types.ts
app/src/store/features/userActions.js
app/src/store/initial-state/index.js
app/src/store/selectors.js

RQ-512: group and rule creation activation experiment

---

app/src/views/features/sessions/SessionViewer/DraftSessionViewer.tsx

RQ-557 auto generate draft session title

---

app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/CreateWorkspaceModal/index.jsx
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/MembersDetails/AddMemberModal/index.jsx
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/TeamSettings/index.js

before: 
workspace settings:
add member modal
after: 
workspace settings:
add member modal:

chore: remove unnecessary learn more message for team workspace

---

app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/OnboardingSteps/TeamWorkspaces/JoinWorkspace.tsx
app/src/components/misc/Invite/AcceptInvite.tsx
app/src/modules/analytics/events/features/teams/index.js

RQ-590(chore): add `team_name` property in `workspace_invite_accepted` event

---

app/src/components/features/rules/GettingStarted/GettingStarted.js
app/src/components/features/rules/ImportFromCharlesModal/index.tsx
app/src/components/features/rules/ImportRulesModal/index.js
app/src/modules/analytics/events/features/rules/index.js

chore: add link to how to export from charles

---

app/src/components/features/sharedLists/SharedListViewerIndexPage/SharedListViewerIndexPage.js

RQ-560(fix): page loader for shared list

---

browser-extension/common/src/popup/components/SessionRecording/SessionRecordingView.tsx

RQ-612(fix): update watch recording icon

---

app/src/views/features/sessions/SessionsIndexPageContainer/SessionsIndexPage/index.js

RQ-611(fix): sessions page loading state

---

app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/MembersDetails/PublicInviteLink/index.tsx
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/MembersDetails/index.js

RQ-602(fix): public invite link option

---

app/src/components/features/sharedLists/CreateSharedListModal/PostConfirmationModal/index.js

RQ-619 fix: shared list post creation mail sent multiple times

---

app/src/components/mode-specific/redirects/NavigateToAppModesRootRoute.tsx
app/src/components/redirects/RootComponent.tsx
app/src/layouts/DashboardLayout/DashboardContent.js
app/src/routes/ruleRoutes.tsx

[RQ-598] fix: root route redirect for desktop app initial render

---

app/src/components/features/sharedLists/CreateSharedListModal/PostConfirmationModal/index.js
app/src/components/features/sharedLists/CreateSharedListModal/index.js

RQ-619: fix shared list creation email sent multiple times from rules list

---

app/src/components/misc/ExtensionDeactivationMessage/index.js

RQ-631: update resume extension message

---

common/logger.js

RQ-635 enable logger for both web app and desktop app

---

app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/RequestSourceRow/index.js
app/src/components/misc/CommandBar/index.tsx
app/src/modules/analytics/events/features/constants.js
app/src/modules/analytics/events/features/testUrlModal/index.js
app/src/modules/analytics/events/misc/commandBar.ts
app/src/modules/analytics/events/misc/constants.js

RQ-646 update cmd+k and test URL condition events

---

app/src/components/features/rules/RulesListContainer/RulesTable/index.js
app/src/utils/Misc.js

show cmd+k as input suffix in rules search input 
Selectively only showing for web apps on macOS and desktop app users

feat: cmd+k suffix in rules table search input

---

app/src/components/features/mocksV2/MockEditorIndex/Editor/index.tsx
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficExporter/HarImportModal/index.tsx
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/ActionHeader.js
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/ContextMenu/index.tsx
app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.js
app/src/utils/AnalyticsUtils.js
app/src/views/features/api-client/ImportRequestModal.tsx
app/src/views/features/api-client/client-view/APIClientView.tsx
app/src/views/features/api-client/sidebar/APIClientSidebar.tsx
app/src/views/features/sessions/SessionsIndexPageContainer/NetworkSessions/NetworkSessionViewer/NetworkSessionViewer.tsx
app/src/views/features/sessions/SessionsIndexPageContainer/NetworkSessions/NetworkSessionsList.jsx
app/src/views/features/sessions/SessionsIndexPageContainer/NetworkSessions/SessionSaveModal.tsx

added these for network sessions, traffic table and api client.
Also added RQLastActivity in api client events

chore: new user attribute rq_last_desktop_activity 

---

app/src/components/misc/CommandBar/index.tsx

RQ-659 Fix: cmd+k not opening for windows/linux

---

app/src/components/common/SourceUrl/index.tsx
app/src/components/common/SourceUrl/types.ts
app/src/components/common/TestURLModal/index.tsx
app/src/types/index.ts
app/src/types/sessionRecording.ts
app/src/views/features/sessions/SessionsSettingsPage/PageSourceRow/index.tsx
app/src/views/features/sessions/SessionsSettingsPage/PageSourceRow/pageSourceRow.css
app/src/views/features/sessions/SessionsSettingsPage/index.tsx
app/src/views/features/sessions/types.ts

[RQ-674] refactor: use source URL common component for session settings 

---

app/src/backend/sessionRecording/getRecording.ts
app/src/backend/sessionRecording/saveRecording.ts
app/src/components/common/FilePicker/index.tsx
app/src/components/misc/SplitButtons/index.tsx
app/src/components/misc/SplitButtons/splitButtons.scss
app/src/modules/analytics/events/features/constants.js
app/src/modules/analytics/events/features/sessionRecording/index.js
app/src/store/features/session-recording/selectors.ts
app/src/store/features/session-recording/slice.ts
app/src/views/features/sessions/SessionViewer/DraftSessionViewer.tsx
app/src/views/features/sessions/SessionViewer/SaveRecordingConfigPopup.tsx
app/src/views/features/sessions/SessionViewer/SavedSessionViewer.tsx
app/src/views/features/sessions/SessionViewer/SessionDetails.tsx
app/src/views/features/sessions/SessionViewer/SessionPropertiesPanel.tsx
app/src/views/features/sessions/SessionViewer/SessionViewerTitle.tsx
app/src/views/features/sessions/SessionViewer/constants.ts
app/src/views/features/sessions/SessionViewer/sessionEventsUtils.ts
app/src/views/features/sessions/SessionViewer/sessionViewer.scss
app/src/views/features/sessions/SessionViewer/types.ts
app/src/views/features/sessions/SessionsIndexPageContainer/SessionsIndexPage/OnboardingView.tsx
app/src/views/features/sessions/SessionsIndexPageContainer/SessionsIndexPage/RecordingsList/index.js
app/src/views/features/sessions/SessionsIndexPageContainer/SessionsIndexPage/index.js
app/src/views/features/sessions/SessionsIndexPageContainer/SessionsIndexPage/index.scss
app/src/views/features/sessions/ShareButton/index.js
app/src/views/features/sessions/api.ts

Closes issue: 
- Add session recording import and export support
https://github.com/requestly/requestly/assets/61556757/4ffd1b8d-df8e-462c-baba-15aa88f1e196

[RQ-644] feat: session recording import/export

---

app/package-lock.json
app/package.json
browser-extension/mv2/package-lock.json
browser-extension/mv2/package.json
browser-extension/mv3/package-lock.json
browser-extension/mv3/package.json

[RQ-681] chore: upgraded web-sdk

---

app/src/views/features/sessions/SessionsIndexPageContainer/SessionsIndexPage/index.js

update open downloaded session dialog header

---

app/src/views/features/sessions/SessionViewer/PageURLInfo.tsx
app/src/views/features/sessions/SessionViewer/SessionDetails.tsx
app/src/views/features/sessions/SessionViewer/sessionEventsUtils.ts
app/src/views/features/sessions/SessionViewer/types.ts

RQ-675 Update URL in Recording with page navigations

---

app/src/components/features/rules/RulesListContainer/RulesTable/index.js
app/src/components/landing/Home/HomeV2/index.tsx

RQ-669: remove cmd+k suffix from rule table search

---

app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/JoinWorkspaceModal/index.tsx
app/src/layouts/DashboardLayout/MenuHeader/WorkspaceSelector/WorkSpaceSelector.css
app/src/layouts/DashboardLayout/MenuHeader/WorkspaceSelector/index.jsx
app/src/store/features/userActions.js
app/src/store/initial-state/index.js
app/src/store/selectors.js

Closes issue: 
https://github.com/requestly/requestly/assets/53986600/3e721761-2718-4973-ac70-fd96c313c205

[RQ-645]: Add notification dot on workspace dropdown for unseen invites

---

app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/MembersDetails/index.js

fix: Invite members modal

---

app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/CreateWorkspaceModal/index.jsx
app/src/utils/Misc.js

RQ-645: Add checkbox to invite all org members

---

browser-extension/common/src/custom-elements/session-recording-widget/index.css
browser-extension/common/src/custom-elements/toast/index.css
browser-extension/mv2/jsList.json
browser-extension/mv2/src/client/js/client.js
browser-extension/mv2/src/client/js/utils.js
browser-extension/mv2/src/pages/init.js

RQ-698 Bug: Session Recording does not work on Requestly app

---

app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/JoinWorkspaceModal/JoinWorkspaceModal.css
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/JoinWorkspaceModal/index.tsx
app/src/layouts/DashboardLayout/MenuHeader/WorkspaceSelector/index.jsx

Closes issue: 
* Directly join team workspaces from join workspace modal
* Reorder team invites (team with highest number of members will be on top)

RQ-645: Join workspace modal changes

---

app/src/views/features/sessions/SessionViewer/SessionPropertiesPanel.tsx

[RQ-700]: update session description in server only when changed

---

app/src/views/features/sessions/SessionViewer/DraftSessionViewer.tsx
app/src/views/features/sessions/SessionViewer/SaveRecordingConfigPopup.tsx

Closes issue: 
https://github.com/requestly/requestly/assets/61556757/c849502d-db02-49e0-a9ef-e4a3e52c083d

[RQ-699]: add draft session discard confirmation

---

app/src/components/misc/JoinWorkspaceCard/index.css
app/src/components/misc/JoinWorkspaceCard/index.tsx
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/CreateWorkspaceModal/index.jsx
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/JoinWorkspaceModal/JoinWorkspaceModal.css
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/JoinWorkspaceModal/index.tsx
app/src/layouts/DashboardLayout/DashboardContent.js
app/src/store/features/userActions.js
app/src/store/initial-state/index.js
app/src/store/selectors.js
app/src/types/index.ts
app/src/types/user.ts

RQ-645 workspace joining nudge

---

app/src/components/misc/PersonaSurvey/index.tsx

RQ-717 fix empty questionnaire in workspace onboarding

---

app/src/components/misc/CommandBar/config.tsx
app/src/components/misc/JoinWorkspaceCard/index.tsx
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/CreateFirstTeam/index.js
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/CreateWorkspaceModal/index.jsx
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/JoinWorkspaceModal/index.tsx
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/SwitchWorkspaceModal/SwitchWorkspaceModal.tsx
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamsList/index.js
app/src/layouts/DashboardLayout/MenuHeader/WorkspaceSelector/index.jsx
app/src/layouts/DashboardLayout/Sidebar/PrimarySidebar/InviteButton.tsx
app/src/modules/analytics/events/common/constants.js
app/src/modules/analytics/events/common/onboarding/header.js
app/src/modules/analytics/events/common/teams/index.js
app/src/modules/analytics/events/features/teams/index.js

[RQ-645]: Workspace joining card analytics

---

app/src/components/misc/ProductWalkthrough/tours.tsx

RQ-701: add overlay for save draft session tooltip

---

app/src/layouts/DashboardLayout/index.jsx

fix: one tap sign in for iframe embed

---

app/src/components/misc/PersonaSurvey/index.tsx

[RQ-717] fix: empty questionnaire in desktop app

---

app/src/components/features/rules/RuleBuilder/Header/ActionButtons/actions/index.js

[RQ-734] fix: unsaved changes dialog shows up when saving a rule of a group

---

app/src/routes/sessionRoutes.tsx

RQ-707: handle multiple redirect for saved session page

---

browser-extension/common/src/popup/components/Popup/PopupHeader.tsx

[RQ-727]: extension popup opens the root route

---

app/src/layouts/DashboardLayout/DashboardContent.js

[RQ-743] fix: workspace joining nudge on iframe embed

---

app/src/components/landing/Home/index.scss
app/src/components/landing/Home/index.tsx

Closes issue: 
https://app.requestly.io/sessions/saved/zQwWRKoS6guJOvndNOuz

[RQ-732]: Highlight session recording on homepage

---

browser-extension/common/src/popup/components/Popup/index.tsx

chore:fix typo in extension product hunt banner

---

app/src/components/misc/CodeEditor/CodeEditor.js
app/src/components/misc/CodeEditor/index.tsx
app/src/components/misc/LottieAnimation/AstronautAnimation/index.ts
app/src/components/misc/LottieAnimation/InviteAcceptAnimation/index.ts
app/src/components/misc/LottieAnimation/TeamSolvingPuzzleAnimation/index.ts
app/src/components/misc/LottieAnimation/TeamWideAnimation/index.ts
app/src/components/misc/LottieAnimation/TeamWorkSolvePuzzleAnimation/index.ts
app/src/components/misc/LottieAnimation/WelcomeAnimation/index.ts
app/src/utils/lazyWithRetry.tsx

[RQ-510] chore: added lazyWithRetry

---

app/src/layouts/DashboardLayout/AppBanner/appBanner.scss
app/src/layouts/DashboardLayout/AppBanner/index.tsx
app/src/layouts/DashboardLayout/index.jsx
app/src/modules/analytics/events/common/constants.js
app/src/modules/analytics/events/common/onboarding/appBanner.ts
app/src/store/features/userActions.js
app/src/store/initial-state/index.js
app/src/store/selectors.js

Closes issue: 
https://github.com/requestly/requestly/assets/61556757/c865a41d-b74a-4de1-abd8-100ae0765541

[RQ-757]: add product hunt banner in app

---

app/src/modules/analytics/events/common/onboarding/appBanner.ts

chore: fix app banner analytic event param

---

app/src/views/features/sessions/SessionsIndexPageContainer/SessionsIndexPage/OnboardingView.tsx

Closes issue:  RQ-758
Starts the recording from the onboarding page on pressing enter.

[RQ-758] feat: start recording on enter

---

app/src/hooks/useGoogleOneTapLogin.ts
app/src/layouts/DashboardLayout/index.jsx

[RQ-763] fix: disable one tap signin prompt in embed

---

app/src/layouts/DashboardLayout/AppBanner/index.tsx
app/src/layouts/DashboardLayout/index.jsx
app/src/store/features/userActions.js
app/src/store/initial-state/index.js
app/src/store/selectors.js

chore: update product hunt banner state

---

app/src/config/constants/sub/analytics.js
app/src/layouts/DashboardLayout/DashboardContent.js

RQ-756: Add user attribute if ref is producthunt

---

app/src/views/features/sessions/SessionsHomeView.js

fix: hide onboardings if ref is producthunt

---

app/src/components/user/AccountIndexPage/ManageAccount/ActiveLicenseInfo/SubscriptionInfo/index.js
app/src/components/user/AccountIndexPage/ManageAccount/ActiveLicenseInfo/index.js
app/src/views/features/sessions/SessionViewer/SaveRecordingConfigPopup.tsx

[RQ-731] chore: session replay pro

---

app/src/views/features/sessions/SessionsIndexPageContainer/SessionsIndexPage/OnboardingView.tsx
app/src/views/features/sessions/SessionsIndexPageContainer/SessionsIndexPage/index.scss

chore: added activate deal after 1st session alert

---

app/src/components/landing/pricing/ComparisonTable/v2-free-enterprise/index.js

Closes issue: 
removed Use Requeslty With from session recording section in pricing page

Fix: Removed 'use Requestly with ' form session recording (pricing page)

---

app/src/components/authentication/AuthModal/AuthModal.css
app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/OnboardingSteps/TeamWorkspaces/JoinWorkspace.tsx
app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/OnboardingSteps/TeamWorkspaces/index.css
app/src/components/misc/PersonaSurvey/config.tsx

fix: onboarding typo and stylings

---

app/src/components/features/rules/GettingStarted/PersonaRecommendation/index.tsx

chore: redirect user to root on skipping recommendations

---

app/src/layouts/DashboardLayout/MenuHeader/index.js

added producthunt badge on header

---

app/src/views/features/sessions/SessionViewer/sessionViewer.scss

[RQ-715] fix(style): session recording logs panel overflow

---

app/src/views/features/sessions/SessionsIndexPageContainer/SessionsIndexPage/OnboardingView.tsx
app/src/views/features/sessions/SessionsIndexPageContainer/SessionsIndexPage/index.scss

Reverts requestly/requestly#962

Revert "chore: added activate deal after 1st session alert"

---

app/src/components/features/rules/RuleBuilder/Body/index.js
app/src/components/features/rules/TestThisRule/index.css
app/src/components/features/rules/TestThisRule/index.tsx

Closes issue: 
Changes:
* Test this rule UI (except the test sessions list)
* Added validations for page URL
* Disable whole component if there are unsaved changes 
* After creating rule, scroll down to test this rule box

RQ-785: Test this rule UI

---

app/src/components/common/RuleEditorModal/RuleEditorModal.css

fix(style): rule editor modal

---

app/src/components/features/rules/TestThisRule/TestReports.tsx
app/src/components/features/rules/TestThisRule/index.css
app/src/components/features/rules/TestThisRule/index.tsx
app/src/config/constants/sub/links.js
app/src/modules/analytics/events/features/constants.js
app/src/modules/analytics/events/features/ruleEditor/index.js

RQ-785: Test this rule analytics and help link

---

app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/CreateWorkspaceModal/index.jsx

RQ-806 Fix: create workspace button disabled for default team name

---

app/src/components/features/rules/RuleBuilder/Header/ActionButtons/Status/index.js
app/src/components/misc/CodeEditor/CodeEditor.js

[RQ-814] fix: modify request rule toggle disabled in rule editor

---

app/src/components/common/SharingModal/index.css
app/src/components/common/SharingModal/index.tsx
app/src/components/common/SharingModal/types.ts
app/src/layouts/DashboardLayout/DashboardContent.js

RQ-800 add sharing option tabs in modal

---

browser-extension/mv2/src/background/background.js
browser-extension/mv2/src/client/js/sessionRecorder.js

[RQ-816] fix: sessions not being stitched

---

app/src/components/common/SharingModal/DownloadRules/index.tsx
app/src/components/common/SharingModal/ShareLinkView.tsx
app/src/components/common/SharingModal/index.tsx
app/src/components/features/rules/RuleBuilder/Header/ActionButtons/ShareRuleButton/index.jsx
app/src/components/features/rules/RulesListContainer/RulesTable/index.js
app/src/components/features/rules/RulesListContainer/index.js
app/src/components/misc/CopyValue/index.tsx
app/src/modules/analytics/events/features/sharedList/index.js
app/src/modules/analytics/events/misc/constants.js
app/src/modules/analytics/events/misc/sharing.js

RQ-800: share modal analytics

---

app/src/components/features/rules/TestThisRule/TestReports.tsx
app/src/components/features/rules/TestThisRule/index.tsx
app/src/modules/analytics/events/features/constants.js
app/src/modules/analytics/events/features/ruleEditor/index.js

[RQ-836] added events on test this rule

---

app/src/components/common/SharingModal/DownloadRules/index.tsx
app/src/components/common/SharingModal/ShareLinkView.tsx
app/src/components/misc/ProductWalkthrough/tours.tsx
app/src/modules/analytics/events/misc/constants.js
app/src/modules/analytics/events/misc/sharing.js

RQ-800 chore: fix typos and remove rule download event

---

app/src/components/features/rules/RuleEditorSplitPane/ExecutionLogs.js

Fix URL capitalization

---

app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/RequestBodyRow/index.js
browser-extension/common/src/devtools/containers/network/details-tabs/PayloadTabContent/PayloadTabContent.tsx
browser-extension/common/src/devtools/containers/network/details-tabs/PayloadTabContent/components/QueryParams/QueryParamsPanel.tsx
browser-extension/common/src/devtools/containers/network/details-tabs/PayloadTabContent/components/RequestBody/RequestBody.tsx
browser-extension/common/src/devtools/containers/network/details-tabs/PayloadTabContent/components/RequestBody/RequestBodyPanel.tsx
browser-extension/common/src/devtools/containers/network/details-tabs/PayloadTabContent/components/RequestBody/RequestBodyParsed.tsx
browser-extension/common/src/devtools/containers/network/details-tabs/PayloadTabContent/payloadTabContent.scss
browser-extension/common/src/devtools/types.ts
browser-extension/common/src/devtools/utils.ts

[RQ-824] feat: Requestly devtools request support

---

browser-extension/mv2/src/background/background.js

Closes issue: 
https://github.com/requestly/requestly/assets/61556757/7a5a6dd1-99aa-446a-a1dc-6b7476b364d0
https://github.com/requestly/requestly/assets/61556757/ea9d6f78-bcd8-4e19-ba38-4950ee719ced

[RQ-811] fix: session replay icon display issue

---

app/src/components/common/FeatureLimiterBanner/featureLimiterBanner.tsx
app/src/modules/analytics/events/common/constants.js
app/src/modules/analytics/events/common/feature-limiter/index.ts

[RQ-827] analytics: added event for feature limiter banner

---

browser-extension/mv2/src/background/background.js

handle invalid URL in extension for response headers

---

app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/detailsTabs.tsx
app/src/views/features/sessions/SessionViewer/NetworkLogs/helpers.ts

[RQ-870] fix: handle invalid urls in network log

---

app/src/hooks/featureLimiter/useFeatureLimiter.ts

[RQ-827] fix: feature limit value is persisted

---

browser-extension/common/src/devtools/devtools.html
browser-extension/common/src/devtools/devtools.js

[RQ-872] enhancement: added emoji in requestly devtools tab name

---

app/src/components/common/SharingModal/Workspaces/WorkspaceShareMenu.tsx
app/src/components/common/SharingModal/Workspaces/index.scss
app/src/components/common/SharingModal/index.css
app/src/components/common/SharingModal/index.tsx

Closes issue: 
* Added footer for shared list and download tabs
* Fixed typos

RQ-800: Sharing modal improvements

---

browser-extension/mv2/src/client/js/ruleExecutionHandler.js

[RQ-871] added communication for response header modification in test-rule-widget

---

app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/RequestBodyRow/index.js
app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/ResponseBodyRow/index.js

RQ-878: fix code editor minifies code on change in static mode

---

app/src/components/landing/pricing/ComparisonTable/v2-free-enterprise/index.css
app/src/components/landing/pricing/ComparisonTable/v2-free-enterprise/index.js
app/src/components/landing/pricing/ComparisonTable/v2-free-enterprise/pricingFeatures.js
app/src/components/landing/pricing/ComparisonTable/v2-free-enterprise/pricingPlans.js
app/src/components/landing/pricing/EnterpriseRequestBanner/index.css
app/src/components/landing/pricing/EnterpriseRequestBanner/index.js
app/src/components/landing/pricing/PricingIndexPage/index.css
app/src/config/constants/sub/pricing.js

[RQ-874] fix: org banner style

---

app/src/views/features/sessions/SessionViewer/SaveRecordingConfigPopup.tsx

RQ-842: Remove login for downloading local sessions

---

app/src/components/common/SharingModal/Workspaces/ShareFromWorkspace.tsx
app/src/components/common/SharingModal/index.tsx

Chore: update sharing modal footer copy and query param variable in rule link

---

app/src/components/landing/pricing/ComparisonTable/v2-free-enterprise/WorkspaceDropdown.tsx
app/src/utils/PremiumUtils.js

[RQ-828] fix: premium plan name getter

---

app/src/modules/analytics/events/features/constants.js
app/src/modules/analytics/events/features/sessionRecording/index.js
app/src/views/features/sessions/SessionsIndexPageContainer/SessionsIndexPage/OnboardingView.tsx
app/src/views/features/sessions/SessionsIndexPageContainer/SessionsIndexPage/RecordingsList/index.js
app/src/views/features/sessions/SessionsIndexPageContainer/SessionsIndexPage/index.js
app/src/views/features/sessions/SessionsIndexPageContainer/SessionsIndexPage/index.scss

RQ-846: Second session replay

---

app/package-lock.json
app/package.json
app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/index.tsx
app/src/lib/design-system/components/RQNetworkTable/index.tsx
app/src/modules/analytics/events/features/constants.js
app/src/modules/analytics/events/features/sessionRecording/index.js
app/src/views/features/api-client/client-view/request/RequestTabs.tsx
app/src/views/features/sessions/SessionViewer/NetworkLogs/NetworkLogsPanel.tsx

[RQ-853]: add replay request support for session recording network logs

---

app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/index.tsx
app/src/lib/design-system/components/RQNetworkTable/index.tsx
app/src/lib/design-system/components/index.ts
app/src/views/features/sessions/SessionViewer/NetworkLogs/NetworkLogsPanel.tsx
app/src/views/features/sessions/SessionViewer/NetworkLogs/helpers.ts

Closes issue: https://github.com/requestly/requestly/issues/255

[RQ-852]: add rule creation support from session recording network logs

---

app/src/views/features/api-client/client-view/APIClientView.tsx

chore: fix extension paused banner style

---

app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/MembersDetails/TeamMembersTable/index.js

RQ-899 chore: replace requestly.extension mail with enterpise.support mail in team members list

---

browser-extension/common/src/popup/components/OnboardingScreen/index.tsx
browser-extension/common/src/popup/components/common/RuleItem/index.tsx
browser-extension/common/src/popup/events.ts

[RQ-896] chore: fix analytics event in popup

---

app/src/components/common/FeatureLimiterBanner/featureLimiterBanner.tsx
app/src/modules/analytics/events/common/constants.js
app/src/modules/analytics/events/common/feature-limiter/index.ts

[RQ-827] added feature limiter banner viewed event

---

app/src/components/landing/pricing/ComparisonTable/v2-free-enterprise/index.css
app/src/components/landing/pricing/ComparisonTable/v2-free-enterprise/index.js

CX-104: pricing table responsive

---

app/src/components/landing/pricing/ComparisonTable/v2-free-enterprise/index.css
app/src/components/landing/pricing/ComparisonTable/v2-free-enterprise/index.js
app/src/layouts/DashboardLayout/DashboardContent.js
app/src/layouts/DashboardLayout/DashboardLayout.css

fix: pricing page table styles and responsiveness

---

app/src/layouts/DashboardLayout/DashboardContent.js
app/src/layouts/DashboardLayout/DashboardLayout.css

RQ-912 chore: fix app scroll

---

app/src/components/features/rules/RulesListContainer/index.js
app/src/hooks/DbListenerInit/DBListeners.js
app/src/hooks/DbListenerInit/userSubscriptionNodeListener.js
app/src/hooks/featureLimiter/useFeatureLimiter.ts

RQ-911: Fix feature limit banner visible to professional plan users

---

app/src/components/common/SharingModal/ShareLinkView.tsx
app/src/components/common/SharingModal/index.css
app/src/components/misc/CopyValue/index.css

[RQ-908] fix: reduce copy on shared list screen in sharing modal

---

app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/SwitchWorkspaceModal/SwitchWorkspaceModal.tsx

RQ-902: fix available teams ordering in switch workspace modal

---

app/src/hooks/useDebounce.ts
app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/components/FiltersToolbar/FiltersToolbar.tsx
app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/components/FiltersToolbar/filtersToolbar.scss
app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/components/FiltersToolbar/types.ts
app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/index.tsx
app/src/lib/design-system/components/RQNetworkTable/RQNetworkTable.css

Closes issue: 
https://app.requestly.io/sessions/saved/m844xVVsXZOYxEfdlx7z

[RQ-869]: Search in session replay network table

---

app/src/components/landing/pricing/ComparisonTable/v2-free-enterprise/WorkspaceDropdown.tsx
app/src/components/landing/pricing/ComparisonTable/v2-free-enterprise/index.js

[RQ-917] fix: null check on enterprise plan table

---

app/src/components/landing/Appsumo/Appsumo.tsx

[RQ-893] fix: incomplete appsumo-form submit

---

app/src/views/features/sessions/SessionViewer/sessionViewer.scss

RQ-910  chore: fix session replay description missing line breaks

---

app/src/backend/sessionRecording/saveRecording.ts
app/src/components/features/rules/TestThisRule/TestReports.tsx
app/src/modules/analytics/events/features/sessionRecording/index.js
app/src/views/features/sessions/SessionViewer/DraftSessionViewer.tsx
app/src/views/features/sessions/SessionViewer/SaveRecordingConfigPopup.tsx
app/src/views/features/sessions/SessionViewer/constants.ts

RQ-920: Add source on session replay saved event

---

app/src/views/features/sessions/SessionViewer/SaveRecordingConfigPopup.tsx

chore: add session replay saved source in dependency array

---

app/src/hooks/DbListenerInit/availableTeamsListener.js

RQ-925: Filter out teams from available teams with deleted flag

---

app/src/components/landing/pricing/ComparisonTable/v2-free-enterprise/index.css
app/src/components/landing/pricing/ComparisonTable/v2-free-enterprise/index.js

fix: workspace selector in pricing page

---

app/src/components/features/filesLibrary/FileEditor/index.js
app/src/components/features/mocksV2/MockEditorIndex/Editor/index.tsx
app/src/components/features/rules/RuleBuilder/Body/index.js
app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/RequestSourceRow/index.js
app/src/lib/design-system/components/RQEditorTitle/index.tsx

[RQ-665]: rule name auto-populate for new rule

---

app/src/layouts/DashboardLayout/Sidebar/PrimarySidebar/index.tsx
app/src/modules/analytics/events/features/apiClient/index.js
app/src/modules/analytics/events/features/constants.js
app/src/views/features/api-client/APIClientContainer.tsx
app/src/views/features/api-client/client-view/APIClientView.tsx

Reverts requestly/requestly#1094

Revert "chore: show install extension dialog only after api client is used"

---

app/src/components/sections/Footer/index.tsx
app/src/config/constants/sub/links.js

RQ-921: Add productlift changelog link in footer

---

app/src/components/common/PinExtensionPopup/hooks/usePinExtensionPopup.ts

fix: pin extension popup

---

app/src/actions/TeamWorkspaceActions.js
app/src/hooks/DbListenerInit/syncingNodeListener.ts

Closes issue: 
https://app.requestly.io/sessions/saved/TFgw1rNsh3H3JMt0iBUs

[RQ-901] fix: rules cloning issue while workspace switching

---

app/src/modules/analytics/events/features/sessionRecording/index.js
app/src/views/features/sessions/SessionViewer/DraftSessionViewer.tsx

[RQ-937] chore: add source in draft session viewed event

---

app/src/layouts/DashboardLayout/Sidebar/PrimarySidebar/index.tsx
app/src/modules/analytics/events/features/apiClient/index.js
app/src/modules/analytics/events/features/constants.js
app/src/views/features/api-client/APIClientContainer.tsx
app/src/views/features/api-client/client-view/APIClientView.tsx

added check for desktop app as well

show extension install modal in api client 

---

app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/OnboardingSteps/TeamWorkspaces/WorkspaceCreation.tsx
app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/index.tsx
app/src/components/misc/PersonaSurvey/ModalFooter.tsx
app/src/components/misc/PersonaSurvey/actions.ts
app/src/components/misc/PersonaSurvey/config.tsx

[RQ-907 RQ-932] Onboarding changes: switch to workspace on creation

---

app/src/components/landing/Appsumo/Appsumo.tsx
app/src/lib/design-system/custom/base.css

RQ-945: create a default team for new users in Appsumo flow

---

app/src/modules/analytics/events/features/constants.js
app/src/modules/analytics/events/features/sessionRecording/index.js
app/src/views/features/sessions/SessionViewer/SavedSessionViewer.tsx
app/src/views/features/sessions/errors/BadSessionError/index.tsx

RQ-946: added error screen for bad session replay

---

browser-extension/mv2/src/background/background.js

Closes issue: 
- Fixes icon issue caused by `Referer` header.

[RQ-934] fix: icon issue in session replay player 

---

browser-extension/common/src/popup/index.css

add new colors variables

---

app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/components/FiltersToolbar/FiltersToolbar.tsx
app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/components/FiltersToolbar/MethodFilter.tsx
app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/components/FiltersToolbar/StatusCodeFilter.tsx
app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/components/FiltersToolbar/filtersToolbar.scss
app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/components/FiltersToolbar/types.ts
app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/index.tsx
app/src/views/features/sessions/SessionViewer/sessionViewer.scss

Closes issue: 
https://app.requestly.io/sessions/saved/7JYSsD4mYbiOatWChIqt

RQ-933 : Status code and method filters in session replay network logs

---

app/src/App.js
app/src/store/selectors.js
app/src/utils/DateTimeUtils.js
app/src/views/features/sessions/SessionsSettingsPage/hooks/index.ts
app/src/views/features/sessions/SessionsSettingsPage/hooks/useInitializeNewUserSessionConfig.ts
app/src/views/features/sessions/SessionsSettingsPage/hooks/useInitializeNewUserSessionRecordingConfig.ts
app/src/views/features/sessions/SessionsSettingsPage/index.tsx

[RQ-957]: default on auto session recording for new users 

---

app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/index.tsx
app/src/lib/design-system/components/RQNetworkTable/RQNetworkTable.css
app/src/lib/design-system/components/RQNetworkTable/index.tsx
app/src/views/features/sessions/SessionViewer/NetworkLogs/NetworkLogsPanel.tsx
app/src/views/features/sessions/SessionViewer/NetworkLogs/helpers.ts
app/src/views/features/sessions/SessionViewer/SessionDetails.tsx
app/src/views/features/sessions/SessionViewer/sessionViewer.scss

RQ-880 : Add pointer to most recent log and fade out pending logs

---

app/src/lib/design-system/custom/variables.css

[RQ-943] chore: add color tokens according to design

---

app/src/modules/analytics/events/features/sessionRecording/index.js
app/src/views/features/sessions/SessionViewer/DraftSessionViewer.tsx
app/src/views/features/sessions/SessionViewer/SaveRecordingConfigPopup.tsx
app/src/views/features/sessions/SessionViewer/types.ts
browser-extension/mv2/src/client/js/sessionRecorder.js

[RQ-905] added recording_mode to session events

---

app/src/components/features/rules/RulesListContainer/index.js
app/src/modules/analytics/events/features/sessionRecording/index.js
browser-extension/common/src/popup/components/HttpsRuleOptions/index.tsx
browser-extension/common/src/popup/components/PopupTabs/index.tsx
browser-extension/common/src/popup/components/SessionRecording/SessionRecordingView.tsx
browser-extension/common/src/popup/events.ts

chore: add/fix analytics

---

browser-extension/common/src/custom-elements/session-recording-widgets/manual-mode-widget/index.ts
browser-extension/mv2/src/background/background.js
browser-extension/mv2/src/client/js/ruleExecutionHandler.js
browser-extension/mv2/src/client/js/sessionRecorder.js

fix: test this rule ext recording icon

---

app/src/views/features/sessions/SessionViewer/ConsoleLogs/ConsoleLogRow.tsx
app/src/views/features/sessions/SessionViewer/ConsoleLogs/ConsoleLogsPanel.tsx
app/src/views/features/sessions/SessionViewer/ConsoleLogs/LogIcon.tsx
app/src/views/features/sessions/SessionViewer/ConsoleLogs/console.scss
app/src/views/features/sessions/SessionViewer/SessionDetails.tsx
app/src/views/features/sessions/SessionViewer/SessionDetailsPanelRow.tsx
app/src/views/features/sessions/SessionViewer/sessionEventsUtils.ts
app/src/views/features/sessions/SessionViewer/sessionViewer.scss

Closes issue: 
https://app.requestly.io/sessions/saved/JDkP1j7p4o5ctnJ13pJt

[RQ:881] Add pointer to most recent console log

---

app/src/components/authentication/AuthForm/AuthForm.css

chore: fix auth modal form bg-color

---

app/src/components/common/SharingModal/Workspaces/ShareFromPrivate.tsx
app/src/components/common/SharingModal/Workspaces/ShareFromWorkspace.tsx
app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/OnboardingSteps/TeamWorkspaces/WorkspaceCreation.tsx
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/CreateWorkspaceModal/index.jsx
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/MembersDetails/AddMemberModal/index.jsx
app/src/modules/analytics/events/features/teams/index.js

[RQ-976] added num_users event param for add_team_member_success event

---

app/src/utils/DateTimeUtils.js
app/src/views/features/sessions/SessionsSettingsPage/hooks/useInitializeNewUserSessionRecordingConfig.ts

[RQ-977]: default on auto recording for new and existing users who haven't use session replay

---

app/src/components/features/rules/RulesListContainer/RulesTable/index.js
app/src/components/misc/ProductWalkthrough/constants.ts
app/src/components/misc/ProductWalkthrough/tours.tsx

RQ-980: Remove rule list tour nudges

---

browser-extension/common/src/custom-elements/session-recording-widgets/auto-mode-widget/index.css
browser-extension/common/src/custom-elements/session-recording-widgets/auto-mode-widget/index.ts
browser-extension/common/src/popup/components/SessionRecording/SessionRecordingView.tsx
browser-extension/mv2/src/background/background.js
browser-extension/mv2/src/client/js/sessionRecorder.js
browser-extension/mv2/src/shared/constants.js

[RQ-1001] feat: start explicit recording when auto recording configured

---

app/src/hooks/DbListenerInit/syncingNodeListener.ts

fix: session recording config override for new users

---

app/src/views/features/sessions/SessionViewer/ConsoleLogs/ConsoleLogRow.tsx

chore: fix see more/less button visible for all logs

---

app/src/views/features/sessions/SessionsSettingsPage/hooks/useInitializeNewUserSessionRecordingConfig.ts

[RQ-1026] fix: default auto recording config for existing users

---

app/src/assets/icons/premium.svg
app/src/components/common/FeatureLimiterBanner/featureLimiterBanner.tsx
app/src/components/common/PremiumIcon/index.tsx
app/src/components/common/PremiumIcon/premiumIcon.css
app/src/components/common/SharingModal/index.css
app/src/components/common/SharingModal/index.tsx
app/src/components/features/rules/RuleBuilder/Body/Columns/AddPairButton/index.js
app/src/components/features/rules/RuleBuilder/Header/ActionButtons/ShareRuleButton/index.jsx
app/src/components/features/rules/RuleBuilder/Header/RuleOptions/RuleOptions.css
app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/RequestBodyRow/index.js
app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/ResponseBodyRow/index.js
app/src/components/features/rules/RulePairs/ResponseRuleResourceTypes/ResponseRuleResourceTypes.css
app/src/components/features/rules/RulePairs/ResponseRuleResourceTypes/index.tsx
app/src/components/features/rules/RulesListContainer/RulesTable/AuthPopoverButtons.tsx
app/src/components/features/rules/RulesListContainer/RulesTable/index.js
app/src/components/features/rules/RulesListContainer/RulesTable/rulesTable.css
app/src/components/landing/pricing/EnterpriseRequestBanner/index.js
app/src/components/landing/ruleSelection/RuleHeader/index.tsx
app/src/components/landing/ruleSelection/RuleList/RuleItem/index.tsx
app/src/components/user/AccountIndexPage/ManageAccount/ActiveLicenseInfo/GetASubscription/index.js
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/BillingDetails/SubscriptionActionButtons/index.js
app/src/hooks/featureLimiter/featureLimitTypes.ts
app/src/hooks/featureLimiter/types.ts
app/src/hooks/featureLimiter/useFeatureLimiter.ts
app/src/modules/analytics/events/common/constants.js
app/src/modules/analytics/events/common/feature-limiter/index.ts
app/src/modules/analytics/events/common/pricing/index.ts
app/src/modules/analytics/events/common/teams/index.js

[RQ-1023]: show crown icon next to premium features

---

app/src/components/features/rules/RuleBuilder/Header/ActionButtons/CreateRuleButton/index.js
browser-extension/common/src/devtools/events.ts
browser-extension/common/src/devtools/utils.ts

[RQ-1025] chore: update `rule_created` event source property for devtools

---

app/package.json
app/src/utils/files/urlUtils.js

chore: remove axios dependency

---

app/src/views/features/sessions/SessionsHomeView.js
app/src/views/features/sessions/SessionsIndexPageContainer/SessionsIndexPage/OnboardingView.tsx
app/src/views/features/sessions/SessionsIndexPageContainer/index.js

[RQ-1032] fix: session settings unresponsive issue

---

app/src/actions/FirebaseActions.js

[RQ-1041] fix: email_type in login_success

---

app/src/features/pricing/components/PricingTable/index.tsx

chore: fix upgrade button showing up in enterprise plan card in pricing modal

---

app/src/layouts/DashboardLayout/MenuHeader/PremiumPlanBadge/PremiumPlanBadge.tsx
app/src/layouts/DashboardLayout/MenuHeader/PremiumPlanBadge/premiumPlanBadge.scss
app/src/layouts/DashboardLayout/MenuHeader/index.js

[RQ-1049] Signup trial flow

---

app/package-lock.json
app/package.json
browser-extension/mv2/package-lock.json
browser-extension/mv2/package.json
browser-extension/mv3/package-lock.json
browser-extension/mv3/package.json

chore: bump web-sdk version

---

app/src/features/pricing/components/PremiumFeature/index.tsx
app/src/hooks/AuthHandler.js
app/src/layouts/DashboardLayout/index.jsx
app/src/store/features/userActions.js

Fix: user organization admin details not being fetched

---

app/src/components/common/FeatureLimiterBanner/featureLimiterBanner.tsx
app/src/components/misc/PersonaSurvey/actions.ts
app/src/components/user/AccountIndexPage/ManageAccount/ActiveLicenseInfo/GetASubscription/index.js
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/BillingDetails/SubscriptionActionButtons/index.js
app/src/features/pricing/analytics/index.ts
app/src/features/pricing/components/PremiumFeature/components/RequestFeatureModal/index.tsx
app/src/features/pricing/components/PremiumFeature/index.tsx
app/src/features/pricing/components/PricingModal/index.tsx
app/src/features/pricing/components/PricingTable/index.tsx

RQ-1063: Onboarding and pricing modal  analytics fixes

---

app/src/App.js

[RQ-1062] disable auto recording by default

---

app/src/layouts/DashboardLayout/MenuHeader/PremiumPlanBadge/PremiumPlanBadge.tsx
app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/index.tsx

fix: planName in badge

---

app/src/actions/FirebaseActions.js
app/src/layouts/DashboardLayout/MenuHeader/HeaderUser.jsx
app/src/layouts/DashboardLayout/MenuHeader/MenuHeader.css
app/src/layouts/DashboardLayout/MenuHeader/index.js

[RQ-1065] fix: user display style fixes

---

app/src/components/features/rules/RuleBuilder/Body/RuleInfoBanner/index.tsx

[RQ-1069] : added  communication about authorization header not forwarded when URL redirection

---

app/src/features/pricing/components/PricingTable/index.tsx
app/src/features/pricing/constants/pricingFeatures.ts

[RQ-1079] fix: pricing table buttons and features

---

app/src/components/features/rules/RuleBuilder/Body/RuleInfoBanner/index.tsx

[RQ-1069] added more_info_clicked_event

---

app/src/features/pricing/components/PricingTable/index.tsx

[RQ-1050] fix: checkout initiated event

---

app/src/features/pricing/components/PricingTable/index.tsx

[RQ-1050] fix: manage subscription redirect

---

app/src/layouts/DashboardLayout/AppNotificationBanner/OrgNotificationBanner.tsx

[RQ-1116] fix: team plan request banner analytics

---

app/src/layouts/DashboardLayout/AppNotificationBanner/OrgNotificationBanner.tsx
app/src/layouts/DashboardLayout/AppNotificationBanner/appNotificationBanner.scss

[RQ-1116] fix: org banner styles

---

app/src/layouts/DashboardLayout/AppNotificationBanner/OrgNotificationBanner.tsx

[RQ-1116] fix: org banner copy

---

app/src/components/features/rules/DeleteRulesModal/actions/index.js
app/src/components/features/rules/DeleteRulesModal/index.js
app/src/components/features/rules/RulesListContainer/RulesTable/index.js
app/src/components/features/rules/UngroupOrDeleteRulesModal/index.js
app/src/components/user/DeleteConfirmationModal/index.js
app/src/views/containers/RulesContainer/RulesSidebar/index.tsx

[RQ-1109] disable trash

---

app/src/features/pricing/components/PremiumFeature/components/RequestFeatureModal/index.tsx
app/src/features/pricing/components/PricingModal/Checkout.tsx
app/src/features/pricing/components/PricingModal/index.tsx
app/src/features/pricing/components/PricingTable/index.tsx
app/src/features/pricing/components/UpgradeWorkspaceMenu/index.tsx
app/src/modules/analytics/events/misc/business/checkout/index.js

RQ-1117: Add source to pricing events

---

app/src/components/features/rules/DeleteRulesModal/index.js
app/src/components/user/DeleteConfirmationModal/index.js

[RQ-1109] fix: rules deletion

---

app/src/components/features/rules/DuplicateRuleModal/index.tsx

RQ-1119 fix: upgrade popover not showing for multiple duplication from editor

---

app/src/components/common/RuleTypeTag/RuleTypeTag.css
app/src/components/common/RuleTypeTag/index.jsx
app/src/components/features/rules/DeleteRulesModal/index.js
app/src/components/features/rules/DuplicateRuleModal/index.tsx
app/src/components/features/rules/RenameGroupModal/index.js
app/src/componentsV2/ContentTable/ContentTable.tsx
app/src/componentsV2/ContentTable/components/BulkActionBar/BulkActionBar.tsx
app/src/componentsV2/ContentTable/contentTable.scss
app/src/componentsV2/ContentTable/types/index.ts
app/src/features/rules/components/RulesList/components/RulesListIndex/RulesListIndex.tsx
app/src/features/rules/components/RulesList/components/RulesListIndex/context/index.ts
app/src/features/rules/components/RulesList/components/RulesListIndex/context/rules-context/index.tsx
app/src/features/rules/components/RulesList/components/RulesTable/RulesTable.tsx
app/src/features/rules/components/RulesList/components/RulesTable/hooks/useRuleTableActions.tsx
app/src/features/rules/components/RulesList/components/RulesTable/hooks/useRuleTableColumns.tsx
app/src/features/rules/components/RulesList/components/RulesTable/rulesTable.css
app/src/features/rules/types/rules.ts
app/src/lib/design-system/custom/variables.css
app/src/store/features/rules/selectors.ts
app/src/store/features/rules/slice.ts

Closes issue: 
- Updated base styles for rules table
- Added rules context
- Setup more record actions
- Setup Modals for single row action

update rules table style + modal setup

---

app/src/features/pricing/components/PricingTable/PricingTableButtons.tsx

[RQ-1121] fix: userPlanType in pricing table buttons

---

app/src/components/features/rules/RuleBuilder/Header/ActionButtons/CreateRuleButton/index.js

[RQ-1146] fix: rule not editing when limit reached

---

app/src/components/common/SharingModal/Workspaces/ShareFromPrivate.tsx
app/src/components/common/SharingModal/Workspaces/ShareFromWorkspace.tsx
app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/OnboardingSteps/TeamWorkspaces/WorkspaceCreation.tsx
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/MembersDetails/AddMemberModal/index.jsx

[RQ-1132] added source with team invites

---

app/src/components/common/SharingModal/DownloadRules/index.tsx
app/src/components/common/SharingModal/ShareLinkView.tsx
app/src/components/common/SharingModal/Workspaces/ShareFromPrivate.tsx
app/src/components/common/SharingModal/Workspaces/ShareFromWorkspace.tsx
app/src/components/common/SharingModal/actions.ts
app/src/components/features/rules/ChangeRuleGroupModal/index.js
app/src/componentsV2/ContentTable/ContentTable.tsx
app/src/componentsV2/ContentTable/components/BulkActionBar/BulkActionBar.tsx
app/src/componentsV2/ContentTable/components/BulkActionBar/bulkActionBar.scss
app/src/componentsV2/ContentTable/contentTable.scss
app/src/componentsV2/ContentTable/types/index.ts
app/src/features/rules/components/RulesList/components/RulesListIndex/RulesListIndex.tsx
app/src/features/rules/components/RulesList/components/RulesListIndex/context/index.ts
app/src/features/rules/components/RulesList/components/RulesListIndex/context/rules-context/index.tsx
app/src/features/rules/components/RulesList/components/RulesTable/RulesTable.tsx
app/src/features/rules/components/RulesList/components/RulesTable/components/index.ts
app/src/features/rules/components/RulesList/components/RulesTable/components/modals/ChangeRuleGroupModalWrapper/index.tsx
app/src/features/rules/components/RulesList/components/RulesTable/components/modals/DeleteRulesModalWrapper/index.tsx
app/src/features/rules/components/RulesList/components/RulesTable/components/modals/DuplicateRuleModalWrapper/index.tsx
app/src/features/rules/components/RulesList/components/RulesTable/components/modals/RenameGroupModalWrapper/index.tsx
app/src/features/rules/components/RulesList/components/RulesTable/hooks/useRuleTableActions.tsx
app/src/features/rules/components/RulesList/components/RulesTable/hooks/useRuleTableColumns.tsx
app/src/features/rules/components/RulesList/components/RulesTable/rulesTable.css
app/src/features/rules/components/RulesList/components/RulesTable/utils/index.ts
app/src/layouts/DashboardLayout/index.jsx
app/src/lib/design-system/custom/variables.css
app/src/store/features/rules/selectors.ts
app/src/store/features/rules/slice.ts
app/src/store/features/userActions.js
app/src/utils/rules/misc.js

feat: bulk actions in rules tables

---

app/package-lock.json
app/package.json
app/src/App.js
app/src/features/onboarding/components/auth/index.tsx
app/src/features/onboarding/components/gettingStarted/components/gettingStartedView/index.tsx
app/src/features/onboarding/components/gettingStarted/index.tsx
app/src/features/onboarding/components/loader/index.scss
app/src/features/onboarding/components/loader/index.tsx
app/src/features/onboarding/components/persona/components/personaScreen/index.tsx

RQ-1122 add loader

---

app/src/components/misc/CodeEditor/index.tsx

chore: add sentry message for when code editor is stuck on loading 

---

app/src/layouts/DashboardLayout/AppNotificationBanner/index.tsx
app/src/modules/analytics/events/common/constants.js
app/src/modules/analytics/events/common/onboarding/appBanner.ts

chore: add event for app notification banner viewed

---

app/src/components/features/rules/RulePairs/Pairs/DelayRulePair/index.js
app/src/components/features/rules/RulePairs/Pairs/HeadersRulePair/HeadersRulePairV2/HeadersPairModificationRowV2.js
app/src/components/features/rules/RulePairs/Pairs/HeadersRulePair/HeadersRulePairV2/index.js
app/src/components/features/rules/RulePairs/Pairs/ResponseRulePair/GraphqlRequestPayload/index.tsx
app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/AddQueryParamModificationRow/index.js
app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/CustomScriptRow/index.js
app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/DestinationURLRow/index.js
app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/QueryParamModificationRow/index.js
app/src/components/features/rules/RulePairs/RulePairs.css
app/src/lib/design-system/custom/base.css

RQ-1128: Fix rule editor responsiveness issues

---

app/src/features/onboarding/components/onboardingView/index.tsx

chore: fix new onboarding visibility toggle check

---

app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/hooks/useIsTeamAdmin.ts
app/src/store/index.js

fix: isTeamAdmin function call

---

app/src/components/common/SharingModal/Workspaces/ShareFromPrivate.tsx
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/CreateWorkspaceModal/index.jsx
app/src/utils/teams/index.ts

RQ-1149: Change default team name during team creation

---

app/src/styles/custom/custom.scss

chore: change one tap prompt position

---

app/src/features/onboarding/components/auth/index.tsx
app/src/features/onboarding/components/gettingStarted/index.tsx
app/src/features/onboarding/components/onboardingView/index.tsx
app/src/features/onboarding/components/persona/components/personaScreen/index.tsx

chore: fix step viewed analytics in new onboarding

---

app/src/layouts/DashboardLayout/MenuHeader/PremiumPlanBadge/PremiumPlanBadge.tsx
app/src/layouts/DashboardLayout/MenuHeader/PremiumPlanBadge/premiumPlanBadge.scss

[RQ-1184] show plan expired badge

---

app/src/components/landing/pricing/FAQs/index.js
app/src/features/pricing/constants/pricingFeatures.ts
app/src/lib/design-system/custom/base.css

RQ-1131: removed headers modification from pricing plan and FAQ change

---

app/src/layouts/DashboardLayout/MenuHeader/PremiumPlanBadge/PremiumPlanBadge.tsx
app/src/layouts/DashboardLayout/MenuHeader/PremiumPlanBadge/premiumPlanBadge.scss

[RQ-1184] fix: planName in premium badge

---

app/package-lock.json
app/package.json
app/src/components/landing/pricing/FAQs/index.js
app/src/components/modals/ContactUsModal/analytics/constants.ts
app/src/components/modals/ContactUsModal/analytics/index.ts
app/src/components/modals/ContactUsModal/index.tsx
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/BillingDetails/SubscriptionActionButtons/index.js
app/src/features/pricing/components/PricingTable/index.tsx
app/src/layouts/DashboardLayout/AppNotificationBanner/OrgNotificationBanner.tsx

RQ-1181: Scale organization banner for other companies

---

app/src/components/misc/CodeEditor/index.tsx

chore: hard fix for infinite loading code editor with forced reload. Tracking with sentry

---

app/src/components/common/RuleTypeTag/RuleTypeTag.css
app/src/components/common/SharingModal/DownloadRules/index.tsx
app/src/components/common/SharingModal/ShareLinkView.tsx
app/src/components/common/SharingModal/Workspaces/ShareFromPrivate.tsx
app/src/components/common/SharingModal/Workspaces/ShareFromWorkspace.tsx
app/src/components/common/SharingModal/Workspaces/index.tsx
app/src/components/common/SharingModal/index.tsx
app/src/components/features/rules/ChangeRuleGroupModal/index.js
app/src/componentsV2/ContentTable/components/BulkActionBar/BulkActionBar.tsx
app/src/componentsV2/ContentTable/contentTable.scss
app/src/componentsV2/ContentTable/types/index.ts
app/src/features/rules/components/RulesList/components/RulesListIndex/RulesListIndex.tsx
app/src/features/rules/components/RulesList/components/RulesTable/RulesTable.tsx
app/src/features/rules/components/RulesList/components/RulesTable/components/modals/ChangeRuleGroupModalWrapper/index.tsx
app/src/features/rules/components/RulesList/components/RulesTable/components/modals/DeleteRulesModalWrapper/index.tsx
app/src/features/rules/components/RulesList/components/RulesTable/components/modals/UngroupOrDeleteRulesModalWrapper/index.tsx
app/src/features/rules/components/RulesList/components/RulesTable/hooks/useRuleTableActions.tsx
app/src/features/rules/components/RulesList/components/RulesTable/hooks/useRuleTableColumns.tsx
app/src/lib/design-system/custom/variables.css

[RQ-1152] fix: bulk action bar closing issue

---

app/src/components/common/RuleTypeTag/RuleTypeTag.css
app/src/components/common/SharingModal/DownloadRules/index.tsx
app/src/components/common/SharingModal/ShareLinkView.tsx
app/src/components/common/SharingModal/Workspaces/ShareFromPrivate.tsx
app/src/components/common/SharingModal/Workspaces/ShareFromWorkspace.tsx
app/src/components/common/SharingModal/Workspaces/index.tsx
app/src/components/common/SharingModal/index.tsx
app/src/components/features/rules/ChangeRuleGroupModal/index.js
app/src/components/features/rules/CreateNewRuleGroupModal/index.js
app/src/components/features/rules/RuleBuilder/Header/EditorGroupDropdown/index.tsx
app/src/components/features/rules/RulesListContainer/RulesTable/index.js
app/src/componentsV2/ContentTable/components/BulkActionBar/BulkActionBar.tsx
app/src/componentsV2/ContentTable/contentTable.scss
app/src/componentsV2/ContentTable/types/index.ts
app/src/features/rules/analytics/groups/index.js
app/src/features/rules/components/RulesList/components/RulesListIndex/RulesListIndex.tsx
app/src/features/rules/components/RulesList/components/RulesListIndex/hooks/useFetchAndUpdateRules.tsx
app/src/features/rules/components/RulesList/components/RulesTable/RulesTable.tsx
app/src/features/rules/components/RulesList/components/RulesTable/components/modals/ChangeRuleGroupModalWrapper/index.tsx
app/src/features/rules/components/RulesList/components/RulesTable/components/modals/DeleteRulesModalWrapper/index.tsx
app/src/features/rules/components/RulesList/components/RulesTable/components/modals/UngroupOrDeleteRulesModalWrapper/index.tsx
app/src/features/rules/components/RulesList/components/RulesTable/hooks/useRuleTableActions.tsx
app/src/features/rules/components/RulesList/components/RulesTable/hooks/useRuleTableColumns.tsx
app/src/features/rules/types/rules.ts
app/src/lib/design-system/custom/variables.css

[RQ-1150] fix: rules table analytics and user attributes

---

app/src/components/landing/Appsumo/Appsumo.tsx
app/src/components/landing/pricing/WorkspaceDropdown/WorkspaceDropdown.tsx
app/src/components/user/AccountIndexPage/ManageAccount/ActiveLicenseInfo/SubscriptionInfo/index.js
app/src/components/user/AccountIndexPage/ManageAccount/ActiveLicenseInfo/index.js
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamsList/index.js
app/src/config/constants/sub/team-workspaces.js

[RQ-1202]: update workspace creation for appsumo flow

---

app/src/components/landing/Appsumo/Appsumo.tsx
app/src/components/user/AccountIndexPage/ManageAccount/ActiveLicenseInfo/index.js
app/src/layouts/DashboardLayout/MenuHeader/PremiumPlanBadge/PremiumPlanBadge.tsx

fix: hide trial subscription info for appsumo

---

app/src/layouts/DashboardLayout/MenuHeader/PremiumPlanBadge/PremiumPlanBadge.tsx

fix: hide premium plan badge for appsumo sessionbook subscription

---

browser-extension/mv2/src/client/js/requestResponseRuleHandler.js

[RQ-1208] added URL matching for redirect/replace rules when overriding fetch

---

app/src/hooks/ActiveWorkspace.js
app/src/hooks/ThirdPartyIntegrationsHandler.js
app/src/modules/analytics/index.js
app/src/modules/analytics/integrations/common.ts
app/src/modules/analytics/integrations/posthog.ts

feat: workspace tracking in analytics group context

---

app/src/components/misc/CodeEditor/index.tsx

Reverts requestly/requestly#1294

Revert "chore: hard fix for infinite loading code editor with forced reload. Tracking with sentry"

---

app/src/components/user/AccountIndexPage/ManageAccount/ActiveLicenseInfo/index.js

fix: hide appsumo subscriptions for other workspaces

---

app/src/components/Home/analytics/constants.ts
app/src/components/Home/analytics/index.ts
app/src/components/Home/components/ChangelogCard/index.tsx
app/src/components/Home/components/HelpCard/index.tsx
app/src/components/Home/components/MocksCard/components/MocksListItem/index.tsx
app/src/components/Home/components/MocksCard/index.tsx
app/src/components/Home/components/RulesCard/index.tsx
app/src/components/Home/components/Templates/index.tsx
app/src/components/Home/components/WorkspaceCard/components/CreateWorkspaceView/index.tsx
app/src/components/Home/components/WorkspaceCard/components/TeamsListView/components/TeamsListItem/index.tsx
app/src/components/Home/components/WorkspaceCard/components/TeamsListView/index.tsx
app/src/components/Home/home.scss
app/src/components/landing/ruleTemplates/RulePreviewModal/index.js
app/src/components/landing/ruleTemplates/TemplatesIndexPage.js
app/src/modules/analytics/events/common/constants.js
app/src/modules/analytics/events/features/templates/index.js

RQ-1182: Homepage analytics

---

browser-extension/mv2/src/client/js/requestResponseRuleHandler.js

[RQ-1215] fix: caching redirect/replace rules

---

app/src/hooks/ActiveWorkspace.js
app/src/hooks/ThirdPartyIntegrationsHandler.js
app/src/modules/analytics/index.js
app/src/modules/analytics/integrations/common.ts
app/src/modules/analytics/integrations/posthog.ts

Reverts requestly/requestly#1293

Revert "feat: workspace tracking in analytics group context"

---

app/src/components/landing/Appsumo/Appsumo.tsx

[RQ-1222] limit user to 10 appSumo codes

---

app/src/components/features/rules/RenameGroupModal/index.js
app/src/components/features/rules/RulesListContainer/RulesTable/index.js

Fix: Group rename

---

app/src/components/features/rules/ChangeRuleGroupModal/index.js
app/src/components/features/rules/RulesListContainer/index.js

Fix: Old table change group modal

---

app/src/features/rules/components/RulesList/components/RulesListIndex/RulesIndexViewWrapper.tsx
app/src/features/rules/routes/index.tsx

setup feature flag to show new rules table to internal users

---

app/src/features/rules/components/RulesList/components/RulesListIndex/RulesListIndex.tsx
app/src/features/rules/components/RulesList/components/RulesTable/utils/rules.ts
app/src/store/features/rules/selectors.ts

RQ-1217: fix pinned rules filtering in new rules table

---

app/src/features/rules/components/RulesList/components/RulesListIndex/RulesListIndex.tsx
app/src/features/rules/components/RulesList/components/RulesTable/RulesTable.tsx
app/src/features/rules/components/SharedList/components/SharedListViewer/SharedListViewer.tsx
app/src/store/features/rules/selectors.ts

RQ-1217: expand groups when searching

---

app/src/components/landing/pricing/EnterpriseRequestBanner/index.tsx

chore: fix request team plan banner shown event

---

app/src/layouts/DashboardLayout/MenuHeader/PremiumPlanBadge/PremiumPlanBadge.tsx

fix: status in plan badge

---

app/src/features/rules/components/RulesList/components/RulesListIndex/RulesListIndex.tsx

RQ-1217: fix new rule table searching

---

app/src/components/features/rules/UngroupOrDeleteRulesModal/index.js
app/src/components/user/DeleteConfirmationModal/index.js
app/src/features/rules/components/RulesList/components/RulesTable/hooks/useRuleTableColumns.tsx
app/src/features/rules/components/RulesList/components/RulesTable/rulesTable.css

RQ-1240: Fix delete rule/group modals messaging and CTA

---

app/src/features/settings/components/GlobalSettings/index.jsx

fix: global settings not visible in desktop app

---

app/src/components/sections/Navbars/NavbarRightContent/DesktopAppProxyInfo/index.jsx

chore: accidental-typo-fix

---

app/public/index.html

fixes: https://github.com/requestly/requestly/issues/1344
Closes issue:

chore: hard redirect to app.requestly.io inside index.html

---

app/src/features/settings/components/BillingTeam/components/MyBillingTeam/components/BillingTeamMembers/components/MemberTableActions.tsx

RQ-1247: fix billing org members table add btn

---

app/src/components/Home/components/WorkspaceCard/components/TeamsListView/index.tsx

[RQ-1255] fix: teamsList broken in home page

---

app/src/components/common/SentryMonitoring/MonitorMountedTime.tsx
app/src/components/features/rules/RulesIndexPage/index.js
app/src/features/rules/components/RulesList/components/RulesListIndex/RulesListIndex.tsx

chore: monitor time for which rules list loader is shown

---

app/src/components/common/SentryMonitoring/MonitorMountedTime.tsx

[RQ-1017] fix: sentry functions

---

app/src/actions/TeamWorkspaceActions.js
app/src/components/authentication/AuthForm/actions/index.js
app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/SwitchWorkspaceButton/index.jsx
app/src/hooks/ActiveWorkspace.js
app/src/hooks/DbListenerInit/DBListeners.js
app/src/hooks/DbListenerInit/availableTeamsListener.js
app/src/hooks/DbListenerInit/syncingNodeListener.ts
app/src/modules/analytics/events/features/syncing/index.js
app/src/modules/analytics/index.js
app/src/utils/StorageServiceWrapper.js
app/src/utils/syncing/SyncUtils.ts
app/src/utils/syncing/syncConstants.js
app/src/utils/syncing/syncDataUtils.js

Reverts requestly/requestly#1324

Revert "Fix: syncing merges local records to the wrong sync target"

---

app/src/modules/analytics/utils/index.js

RQ-1274: add workspaceId for workspace-level grouping in amplitude

---

app/src/features/settings/components/BillingTeam/components/MyBillingTeam/components/BillingInformation/index.tsx

[RQ-1268] fix: show payment method details

---

app/src/features/settings/components/BillingTeam/components/UserPlanDetails/index.tsx

chore: remove trial plan details if user has appsumo subscription

---

app/src/components/misc/PersonaSurvey/utils.ts
app/src/features/onboarding/components/onboardingView/index.tsx

chore: update installation date check for onboarding experiment

---

app/src/features/settings/components/BillingTeam/components/MyBillingTeam/components/BillingTeamMembers/index.tsx

[RQ-1284] show badge to highlight free users in billing team

---

app/src/config/constants/sub/links.js

fix: test url docs link
