app/src/components/landing/ruleTemplates/RulePreviewModal/index.js
=> RQLY-1268: fix: rules created from templates get overriden when reusing the same template

app/src/components/misc/PersonaSurvey/index.css, app/src/components/misc/PersonaSurvey/index.tsx, app/src/modules/analytics/events/misc/constants.js, app/src/modules/analytics/events/misc/personaSurvey.ts
Closes issue: 
Added a sign in option, after clicking on this , if the user logs in then the persona survey will not show up again
=> RQ-36 add sign in option in persona survey

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/FixedRequestLogPane.js
@tarunsamanta2k20 
Closes issue: 
#623 
#626
1. Remove 'Copy cURL' button from top left of the Request pane in Traffic Table.
2. bug: Close button should be on the top right of the request pane in the traffic inspector
=> remove the curl button from request log pane and shift the close button to the right in RequestlogPane

app/src/layouts/DashboardLayout/MenuHeader/index.js
=> chore: add documentation link in header

app/src/components/features/sharedLists/CreateSharedListModal/index.js
Closes issue: https://github.com/requestly/requestly/issues/624
- Fixed the Typo of the CTA share button content from "Copy Text" to "Copy Link".
=> fix: Share CTA Typo fixed from "Copy Text" to "Copy Link"

app/src/components/features/rules/RulesListContainer/RulesTable/index.js
Closes issue: #699 
Interchanged the Import/Export icons on the Rules list page.
=> Changed the export and import icons on rules list page

app/src/components/features/rules/RuleEditorSplitPane/ExecutionLogs.js
=> fix: refresh button clipping in execution logs

app/src/components/mode-specific/desktop/MySources/Sources/index.js, app/src/hooks/AppModeInitializer.js, app/src/store/features/appModeSpecificActions.js, app/src/store/index.js, app/src/store/initial-state/index.js, app/src/store/selectors.js
Adds a persistent `hasConnectedApp` key to the global slice.
The modal is shown once the proxy has started.
https://github.com/requestly/requestly/assets/57226514/2bc9cda6-b67e-4e12-9434-080c989bec0d
=> chore: show connect app modal on start if user has never connected any traffic source

browser-extension/common/src/popup/components/SessionRecording/SessionRecordingView.tsx, browser-extension/mv2/src/background/background.js
Closes issue: 
- Updated the copy `save recording` to `watch recording`  for both modes.
- Updated the migrated schema check in background
=> RQ-600: view session copies + update migrated schema check in background

app/src/components/features/rules/RuleBuilder/Header/ActionButtons/CreateRuleButton/actions/index.js
Closes issue: 
Please find the recording for the changes: https://app.requestly.io/sessions/saved/pPlEOoKkJjxTmhMj3jl8
=> [RQ-564] fix: wrong message when header rule condition incomplete

common/logger.js
Closes issue: 
* To enable Logger using query param add `debug` query param in URL
* To enable Logger from devtools console write **(only in web app)** :
`window.RQ.components.logger.enabled = true`
=> RQ-635 enable Logger in web app from devtools console 

app/src/modules/analytics/events/features/constants.js, app/src/modules/analytics/events/features/sessionRecording/index.js, app/src/views/features/sessions/SessionsIndexPageContainer/SessionsIndexPage/OnboardingView.tsx
adds `session_onboarding_page_viewed` for when session onboarding starts
rename sample recording viewed event to `sample_session_viewed`
=> chore: add event for session onboarding start

app/src/components/common/TestURLModal/index.tsx, app/src/utils/rules/misc.js
Closes issue: 
For RegEx matching rule, I noticed that upon save, the pattern string was auto-added the trailing ‘/’.
E.g.
Input > /test/ig
After save > /test/ig/
=> [RQ-643] fix: autofixer not working properly in case of bad regex

app/src/App.js, app/src/actions/FirebaseActions.js, app/src/components/misc/ExtensionContextInvalidationNotice/extensionContextInvalidationNotice.scss, app/src/components/misc/ExtensionContextInvalidationNotice/index.tsx, app/src/config/PageScriptMessageHandler.js, app/src/modules/analytics/events/misc/constants.js, app/src/modules/analytics/events/misc/extensionContextInvalidation.ts, browser-extension/mv2/src/background/background.js, common/constants.js
On extension update, background will notify all App tabs and App will show a sticky message on top.
=> RQ-641 Show extension context invalidation notice in App

app/src/views/features/sessions/SessionViewer/SessionDetails.tsx
=> [RQ-653] fix: prevent rrweb inputs from getting focus

browser-extension/mv2/src/background/background.js, browser-extension/mv2/src/client/js/client.js, browser-extension/mv2/src/client/js/ruleExecutionHandler.js, browser-extension/mv2/src/shared/constants.js
Because of pages being loaded from browser's BF cache, the content script has stale context and does not reload. In this PR, the content script notifies extension's background script to update extension icon and reload session data whenever page is loaded from cache.
=> RQ-686 Bug: Extension icon does not show session recording state on Browser back

app/src/components/features/rules/GettingStarted/PersonaRecommendation/FeatureCard/FeatureCard.css, app/src/components/features/rules/GettingStarted/PersonaRecommendation/FeatureCard/index.tsx, app/src/components/features/rules/GettingStarted/PersonaRecommendation/personaRecommendationData.tsx, app/src/components/features/rules/GettingStarted/PersonaRecommendation/types.ts
Closes issue: 
- Updated "Page HTML" as 3rd category on the page. 
- Within "Page HTML" added Replay Session in the first spot and changed the copy to "Record a session"
- Added a "NEW" tag like we have on header in Desktop app.
=> [RQ-684]: reorder persona recommendation screen

app/src/views/features/sessions/SessionViewer/SessionDetails.tsx, app/src/views/features/sessions/SessionViewer/SessionPropertiesPanel.tsx
Closes issue:  RQ-702
The player would play from the offset time only on the page load and not when start offset is changed while playing the session.
=> [RQ-702] fix: session viewer lagging when changing start time offset

app/src/views/features/sessions/SessionViewer/SessionDetails.tsx
Closes issue:  RQ-712
- `rrweb` listeners do not work when the focus is changed to another tab. Hence, the player keeps on playing.
- For fixing, this PR pauses the player `onBlur`.
=> [RQ-712] fix: current time greater than the video duration

browser-extension/mv2/src/background/background.js
- Cache the starting page URL when session recording started
- On page navigation/reload in same tab, check if above URL still satisfies the config
=> RQ-718 Fix: Disabling automatic recording keeps recording existing tabs even on page reload/navigation

app/src/views/features/sessions/SessionViewer/DraftSessionViewer.tsx
=> [RQ-769] Fix: confirmation shown twice on discarding draft session

browser-extension/common/src/custom-elements/abstract-classes/draggable-widget.ts
=> [RQ-821] fix: need to double click on session recording on-page widget sometimes

app/src/components/features/rules/GettingStarted/GettingStarted.js, app/src/components/features/rules/GettingStarted/PersonaRecommendation/FeatureCard/index.tsx, app/src/components/features/rules/GettingStarted/PersonaRecommendation/index.tsx, app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/OnboardingSteps/OnboardingAuthForm/index.tsx, app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/OnboardingSteps/PersonaSurvey/SurveyBanner.tsx, app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/OnboardingSteps/TeamWorkspaces/JoinWorkspace.tsx, app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/OnboardingSteps/TeamWorkspaces/WorkspaceCreation.tsx, app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/index.tsx, app/src/components/misc/PersonaSurvey/ModalFooter.tsx, app/src/components/misc/PersonaSurvey/index.tsx, app/src/components/misc/PersonaSurvey/utils.ts, app/src/hooks/AppModeInitializer.js, app/src/layouts/DashboardLayout/DashboardContent.js, app/src/layouts/DashboardLayout/index.jsx, app/src/modules/analytics/events/common/constants.js, app/src/modules/analytics/events/common/teams/index.js, app/src/modules/analytics/events/misc/constants.js, app/src/modules/analytics/events/misc/onboarding.ts
Closes issue: 
* Workspace onboarding is now 100% for web app
*  Persona survey is now 100% for desktop app
* Clicking on `skip for now` in login screen takes users to persona survey in workspace onboarding
* Refactor onboarding events and added page view events for workspace onboarding
=> RQ-855: App onboarding changes

browser-extension/mv2/src/background/background.js
=> [RQ-909] fix: stop recording widget not visible when recording from launch URL

app/src/layouts/DashboardLayout/Sidebar/PrimarySidebar/index.tsx, app/src/modules/analytics/events/features/apiClient/index.js, app/src/modules/analytics/events/features/constants.js, app/src/views/features/api-client/APIClientContainer.tsx, app/src/views/features/api-client/client-view/APIClientView.tsx
=> chore: show install extension dialog only after api client is used

app/src/views/features/sessions/SessionsIndexPageContainer/NetworkSessions/actions.ts
currently network sessions are saved locally as copies of the originally uploaded har.
This does not make sense if Requestly is meant to act as a har client that should reflect changes from the original har as well
=> fix: symlink instead of making copy of network session

browser-extension/common/src/custom-elements/abstract-classes/draggable-widget.ts, browser-extension/common/src/custom-elements/session-recording-widget/index.ts
=> [RQ-973] fix: cache position of draggable widgets

app/src/App.js, app/src/modules/analytics/events/extension.ts, browser-extension/mv2/src/client/js/ruleExecutionHandler.js
- Starts sending `rule_creator` in `rule_executed` event
- removes the old implementation for sending `rule_executed` events (adding unnecessary noise)
- adds event param `executor_is_creator`
=> chore: add event param executor_is_creator

browser-extension/common/src/popup/components/Popup/popup.css, browser-extension/common/src/popup/components/SessionRecording/SessionRecordingView.tsx, browser-extension/common/src/popup/components/SessionRecording/sessionRecordingView.css
=> fix: watch replay button for disabled state tooltip

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.js, app/src/store/features/desktop-traffic-table/selectors.ts
Fixes - https://github.com/requestly/requestly/issues/1252
Creates a dummy reference to the `DESKTOP_TRAFFIC_TABLE.responses` state stored in redux. Had to take this approach because `useSelector` cannot be used inside a callback function.
=> fix: add response body to exported logs

app/src/components/features/rules/RuleBuilder/Header/ActionButtons/CreateRuleButton/index.js, app/src/components/features/rules/RuleBuilder/Header/ActionButtons/actions/index.js, app/src/components/features/rules/RuleBuilder/actions/utils.js, app/src/components/landing/ruleTemplates/RulePreviewModal/index.js, app/src/components/misc/CodeEditor/index.tsx, app/src/utils/FunctionUtils.ts
Closes issue: 
- The saveRule Promise neither resolves nor rejects in the extension when extension is not available or context invalidated.
- addded a function in UI which rejects the promise on timeout of 3s if unsettled
- show toast to user that rule saving has failed
- logged the exceptions
=> [RQ-1220] added exception when rule saving fails

app/src/components/features/rules/RuleBuilder/Header/ActionButtons/CreateRuleButton/index.js
=> RQ-1223: show install extension popup on save rule click if extension not installed

app/src/components/features/rules/RuleBuilder/Header/ActionButtons/CreateRuleButton/index.js
=> fix: extension install popup visible when saving rule in desktop app

app/src/components/features/mobileDebugger/Layout/MobileDebuggerLayout.tsx, app/src/routes/mobileDebuggerRoutes.tsx
=> Add sunset warning in android debugger

app/src/actions/TeamWorkspaceActions.js, app/src/components/features/rules/RulesListContainer/RulesTable/index.js, app/src/features/rules/components/RulesList/components/RulesTable/hooks/useRuleTableActions.tsx, app/src/features/settings/components/Profile/ManageTeams/TeamViewer/TeamSettings/index.js, app/src/hooks/ActiveWorkspace.js, app/src/hooks/DbListenerInit/DBListeners.js, app/src/hooks/DbListenerInit/syncingNodeListener.ts, app/src/layouts/DashboardLayout/MenuHeader/WorkspaceSelector/index.jsx, app/src/utils/StorageServiceWrapper.js, app/src/utils/syncing/syncDataUtils.js
Some parts of the app was expecting the `saveRuleOrGroup` method to also return the saved value.
The fix was only to stop expecting a result to be passed into the following `then`. The callback does not need to be updated since the original `rule` still exists in an outer scope.
The [first commit](https://github.com/requestly/requestly/commit/e891ce5e86b8c5576b0d6286a85e8c178b50e725) just brings back changes from the [original fix](https://github.com/requestly/requestly/pull/1415) (which [was recently reverted](https://github.com/requestly/requestly/pull/1431) because of a severe issue that was introduced, which made it impossible to toggle rules)
Closes issue:
=> revert (revert) and fix side effects of recent changes in storage service wrapper

app/src/features/onboarding/components/auth/index.tsx
=> fix: move to persona screen if user is already logged in

app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/CustomScriptRow/index.js
=> fix: don't show as unsaved changes for first render of script rule

app/package-lock.json, app/package.json, app/src/config/constants/sub/features.js, app/src/hooks/DbListenerInit/syncingNodeListener.ts, app/src/utils/Compression.js, app/src/utils/syncing/syncDataUtils.js
compresses the pair value for 
1. Response rule
2. Request rule
3. Script rule that are of code type
in transit (to and from firebase) and storage. 
Syncing still works on the complete (uncompressed) records
=> feat: compress pair values of certain rule types

app/src/features/settings/components/BillingTeam/components/RequestTeamAccess/components/Reminder/index.tsx
=> fix: close join team reminder popover if user is premium

app/src/components/features/rules/RuleBuilder/Body/actions/index.js, app/src/components/features/rules/RuleBuilder/Body/index.js, app/src/lib/design-system/components/RQEditorTitle/index.tsx, app/src/utils/helpers/appDetails/UserProvider.ts
- ignore the extra comment string added
- Was happening because we set the default name of the rule
Closes issue:
=> fix: don't mark as unsaved changes on start of rule creation

app/src/utils/Compression.js
Observed a case where syncing completely stops if the console shows the error `incorrect header check` from the compression logic. 
Couldn't consistently reproduce but this should stop the error from halting the complete syncing flow and making the app unusable
=> chore: wrap compress/decompress in try-catch

app/src/components/features/rules/GettingStarted/WorkspaceOnboarding/OnboardingSteps/OnboardingAuthForm/index.tsx, app/src/features/rules/screens/rulesList/components/RulesList/components/GettingStarted/WorkspaceOnboarding/OnboardingSteps/OnboardingAuthForm/index.tsx, app/src/hooks/useGoogleOneTapLogin.ts, app/src/layouts/DashboardLayout/index.jsx
Also removes the prompt from 
Builds on top of https://github.com/requestly/requestly/pull/1625 so fixes have been tested on FedCM enabled OneTap
=> fix: oneTap prompt gets shown even when loggedIn

browser-extension/common/src/custom-elements/test-rule-widget/implicit-test-rule-widget/index.ts, browser-extension/mv2/src/client/js/ruleExecutionHandler.js
=> fix: implicit widget not lisiting applied rules when listener is not active

app/src/componentsV2/ContentList/components/ContentListTable/ContentListTable.tsx
=> [ENGG-1721] chore(fix): contentTable local storage state override

app/src/features/rules/screens/sharedListViewer/components/SharedListViewerList/hooks/useSharedListViewerColumns.tsx
=> [ENGG-1708] fix: shared list viewer breaks when clicking on group

browser-extension/common/src/types.ts, browser-extension/mv3/src/service-worker/services/requestProcessor/handleInitiatorDomainFunction.ts
=> [ENGG-1778] fix: rq_request_initiator_origin() not being handled on OPTIONS request

app/src/utils/Compression.js
improves [this](https://github.com/requestly/requestly/pull/1555) to also return the original (faulty) record in case of compression/decompression failure
=> chore: return original record if compression / decompression fails

app/src/modules/extension/utils.ts
=> [ENGG-1789] fix: batch mv3 migration

app/src/config/constants/sub/features.js, app/src/features/settings/components/GlobalSettings/components/SettingsItem/index.tsx, app/src/features/settings/components/Profile/ManageTeams/TeamViewer/TeamSettings/WorkspaceStatusSyncing/index.js, app/src/utils/syncing/syncDataUtils.js
introduces two feature flags:
1. `override_team_sync_status` - default value `false`
2. `overriden_sync_status_value` - default vaule `true`
The second flag is enforced only if first one is `true`. Else the localStorage state is used
=> feat: add featureFlag to override team syncing setting

app/src/actions/FirebaseActions.js, app/src/backend/user/userSubscription.ts, app/src/hooks/AuthHandler.ts, app/src/hooks/DbListenerInit/DBListeners.js, app/src/hooks/DbListenerInit/syncingNodeListener.ts, app/src/store/features/appModeSpecificActions.js, app/src/store/initial-state/index.js, app/src/store/selectors.js
This, although solves the core issue, but triggers the complete run of the AuthHandler useEffect several times which leads to redundant calls of the `blockingOperations` functions.
This happens because `initializations.auth` is set to `true` AFTER the blocking operations are FULLY complete. Unlike https://github.com/requestly/requestly/pull/1716 that sets the custom state to `true` once `blockingOperations` have been triggered
Still raising this as this was brought up during offline discussions 
> preliminary debug logs:
> ![image](https://github.com/requestly/requestly/assets/57226514/bc216547-692a-4673-b364-ed1448487c31)
=> fix authHandler performance issue with existing state

app/src/features/rules/modals/UngroupOrDeleteRulesModalWrapper/index.tsx, app/src/features/rules/screens/rulesList/components/RulesList/components/RulesTable/hooks/useRuleTableColumns.tsx
group children were normalized during the [table refactor](https://github.com/requestly/requestly/pull/1526). This might have got missed due to the ts-ignore
=> [ENGG-1727] fix: fetch rules of groups in the delete modal action

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficExporter/harLogs/converter.ts, app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficExporter/harLogs/types.ts, app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficExporter/harLogs/utils.ts, app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/NetworkTable/index.scss, app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/NetworkInspector/NetworkTable/index.tsx, app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/RequestSummary.js, app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/index.jsx
- adds `GaphQLDetails` property to `RQNetworkLog.request`
- searches over this property in the table
- adds prefix of operation name to the url column
=> feat: graphql details in network traffic table

app/src/modules/analytics/events/features/constants.js, app/src/modules/analytics/events/features/sessionRecording/networkSessions.ts, app/src/views/features/sessions/SessionsIndexPageContainer/NetworkSessions/ImportFromWebSessionsButton.tsx, app/src/views/features/sessions/SessionsIndexPageContainer/NetworkSessions/NetworkSessionViewer/NetworkSessionViewer.tsx, app/src/views/features/sessions/SessionsIndexPageContainer/NetworkSessions/NetworkSessionViewer/networkSessions.scss, app/src/views/features/sessions/SessionsIndexPageContainer/NetworkSessions/NetworkSessionsList.jsx
- writes a converter for webSessions network events to har
- adds analytics events
- does not use [the new import](https://github.com/requestly/requestly/pull/957) since it still isn't stable
https://github.com/requestly/requestly/assets/57226514/80d8e11d-4eee-420d-9361-22d2c365c8e6
=> feat: import websession for desktop network sessions viewer

browser-extension/mv3/tests/rules/request/requestRule.spec.ts, browser-extension/mv3/tests/rules/request/request_rules.json, browser-extension/mv3/tests/rules/request/testScenarios.ts
interceptors for fetch and xhr don't get setup properly. If I try to invoke and setup the page script manually, it doesn't work and gives such an error - `ReferenceError: _fetch is not defined`
so just commenting out all the cases for now
=> test mv3: request rule

browser-extension/mv3/tests/rules/response/responseRule.spec.ts, browser-extension/mv3/tests/rules/response/response_rules.json, browser-extension/mv3/tests/rules/response/testScenarios.ts
all pageAction requests give 404. tried both `response` and `requestEnd` event. The response for main document is captured but not for the pageAction request.
Tried to then move the mock server request to the main `testPageUrl`. The request to those endpoints just fail. might be a problem in mock server?
also tried with `--disable-web-security` flag to bypass if we were having cors errors. But even that didn't work
=> test mv3: response rule

browser-extension/mv3/tests/rules/script/scriptRule.spec.ts, browser-extension/mv3/tests/rules/script/script_rules.json, browser-extension/mv3/tests/rules/script/testScenarios.ts
tried all possible ways to extract elements from the loaded dom for verification (locator, $$, $, etc.) but none of them were even able to get a `p` tag, let alone our custom injected RQ elements. 
Looking at the logs, it seems like sites might be blocking the automation runner (also seen in other rules) [[Ref]](https://github.com/requestly/requestly/pull/1893#issuecomment-2216351774)
=> boilerplate: mv3 tests for script rule

app/src/layouts/DashboardLayout/MenuHeader/ProductsDropDown.tsx, app/src/layouts/DashboardLayout/MenuHeader/index.js
broken for desktop app. could had fixed that but then would required inputs from other teammates around what options should be displayed how on the desktop app. 
removing for now, can be brought back later.
=> fix: remove broken products down from being rendered on desktop app

app/src/features/onboarding/components/persona/components/personaScreen/index.tsx, app/src/routes/index.tsx, app/src/routes/inviteRoutes.tsx, app/src/routes/onboardingRoutes.tsx, app/src/src-SessionBear/routes/index.tsx
- had to do this to add just invites to the sessionBear routes
- could had added the onboarding routes _(since there is already a check [here](https://github.com/requestly/requestly/blob/f4884bf81db5250232a377762173f891393ef72f/app/src/features/onboarding/utils.ts#L11))_ but that could lead to confusing bugs later
=> refactor+fix: extract invite routes to a separate file 

app/src/components/features/mocksV2/MockEditorIndex/utils.ts
doing this to make it possible to specify URL params
=> chore: allow ':' in mock endpoint input

app/src/views/features/rules/RuleEditor/components/Header/ActionButtons/CreateRuleButton/index.jsx
after [these changes](https://github.com/requestly/requestly/pull/2026) transformed value (specifically script rule after syntactic validation) was no longer being used as the _rule data to be saved_
=> fix: use the transformed rule value after syntactic validation

app/src/views/features/rules/RuleEditor/components/Header/ActionButtons/CreateRuleButton/actions/insertScriptValidators.js
the check being commented out was added to make sure strings like 
`<div>hello</div><script>console.log("Hello, World!");</script><style>body { background-color: red; }</style>`
get parsed as html even though our usecase dictates that we don't have any other html tags in the console.
Strings with tags other than script, style or link end up in body when parsing with  `domParser`. 
The problem is that if the string contains a script tag like the following contains `span`
```javscript
const div = document.createElement("div");
div.id = "rq_banner";
div.innerHTML = "<span>🚀 Introducing this new feature powered by Requestly!!</span>";
document.body.appendChild(div);
```
this content will get detected as html rather than string (`isHTMLString` returns true for this)
hence removing the check …
=> fix: code string with html tags makes string be parsed as html

app/src/features/settings/components/Profile/ManageTeams/TeamViewer/MembersDetails/AddMemberModal/index.jsx, app/src/store/features/teams/selectors.js
- admins and owners will be able to select whether to invite as member or admin
- members can only invite (won't see dropdown)
P.S. introduces the `getUserTeamRole` reducer that will be useful later when implementing ACLs
=> fix: role selector when inviting to workspace

app/src/components/features/mocksV2/MockEditorIndex/Editor/index.tsx, app/src/components/features/mocksV2/MockEditorIndex/MockEditorIndex.tsx
Current UI from https://github.com/requestly/requestly/pull/2082 degrades the UX of mock editor hence hiding it for now, and bringing back old changes
=> chore: hide mock logs behind feature flag

app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/RequestBodyRow/index.js, app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/ResponseBodyRow/index.js, app/src/componentsV2/CodeEditor/components/Editor/Editor.tsx
------------
**Summary:**
This pull request simplifies the codebase by removing state management for static request body values and updating rendering for `RequestBodyRow` and `ResponseBodyRow` components.
**State Management:**
- Removes `editorStaticValue` state and related logic from `RequestBodyRow`.
**Rendering:**
- Both `RequestBodyRow` and `ResponseBodyRow` components now directly render `pair.request.value` and `pair.response.value` respectively.
**Categorized Changes:**
**State Management:**
- Removes `editorStaticValue` state and related logic.
**Rendering:**
- Updates `RequestBodyRow` and `ResponseBodyRow` components to render `pair.request.value` and `pair.response.value`.
**Hooks:**
- Introduces `getFeatureLimitValue` hook and uses it in the …
=> [ENGG-2197] fix: RQ rule editor default state

app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/RequestBodyRow/index.js, app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/ResponseBodyRow/index.js, app/src/componentsV2/CodeEditor/components/Editor/Editor.tsx
Reverts requestly/requestly#2114
------------
**Summary:**
1. Introduced state management for static request and response bodies.
2. Updated rendering of request and response body values based on their types.
**Key Points:**
- Added `editorStaticValue` state for managing static values of request and response bodies.
- Conditionally set `editorStaticValue` based on request/response type and value presence.
- Updated `RequestBodyRow` and `ResponseBodyRow` components to use `editorStaticValue`.
**Changes:**
**Request Body:**
1. Imported and added `useState` hook.
2. Declared `editorStaticValue` and `setEditorStaticValue` states.
3. Conditionally set `editorStaticValue` in `RequestBodyRow`.
4. Updated `value` assignment in `RequestBodyRow` to use `editorStaticValue`. …
=> Revert "[ENGG-2197] fix: RQ rule editor default state"

app/src/features/pricing/components/PricingPage/pricingIndexPage.scss
------------
**Summary:**
Added `min-width` property with a value of `300px` to the `.plan-card` class in the pricing page component for improved layout.
**Key Points:**
- Made change in `pricingIndexPage.scss` located in `app/src/features/pricing/components/PricingPage`.
- Affected `.plan-card` class styling.
**Categories:**
- **CSS:** Adjusted `min-width` property for `.plan-card` class.
- **Layout:** Modified pricing plan card layout.
- **PricingPage:** Updated Styling for Pricing Page component.
- **Styling:** Applied new CSS property to `.plan-card`.
- **plan-card:** Set `min-width` for specific pricing plan card class. 
<h6>To turn off PR summary, please visit <a href="https://app.typoapp.io/settings/dev-analytics/notification?tab=codeHealth">Notification …
=> fix: pricing page plan cards wrapping

app/src/components/features/mocksV2/MockEditorIndex/MockEditorIndex.tsx, app/src/utils/RedirectionUtils.js, app/src/views/features/rules/RuleEditor/components/Header/ActionButtons/CreateRuleButton/index.jsx
------------
**Summary:**
This pull request introduces a new boolean parameter `popCurrentRouteFromHistory` to several navigation functions in `ReductionUtils.js`, updates their implementation to use this parameter, and adds it to the calls to these functions in `MockEditorIndex.tsx`. Additionally, the `CreateRuleButton` component's redirect function now accepts two new parameters.
**Navigation Function Changes:**
- Added a new boolean parameter `popCurrentRouteFromHistory` to the functions `redirectToRuleEditor`, `redirectToMockEditorEditMock`, and `redirectToFileMockEditorEditMock` in `ReductionUtils.js`.
- Updated the implementation of these functions to include the new parameter and use it to replace the current route in the navigation history. …
=> ENGG-2233: Fix editors back button behaviour

app/src/components/common/SharingModal/index.tsx
------------
**Summary:**
This pull request modifies the SharingModal component, changing the active tab to "Shared list" and rendering corresponding components accordingly: ShareLinkView for "Shared list" tab and ShareInWorkspaces for "Share in workspace" tab.
**Key Points:**
1. Active tab changed from "Share in workspace" to "Shared list".
2. ShareInWorkspaces rendered for "Share in workspace" tab.
3. ShareLinkView rendered for "Shared list" tab. 
<h6>To turn off PR summary, please visit <a href="https://app.typoapp.io/settings/dev-analytics/notification?tab=codeHealth">Notification settings</a>.</h6>
=> [ENGG-2206] fix: make sharedlist first option in share modal

app/src/views/features/rules/RuleEditor/components/Header/ActionButtons/Status/index.js, app/src/views/features/rules/RuleEditor/components/Header/ActionButtons/actions/index.js
removed `allRules` from `useEffect` dependency array. it was causing infinite rerenders in case of insert script rule.
=> fix: remove unwanted 'allRules' from useEffect dependency array

app/src/components/mode-specific/desktop/InterceptTraffic/WebTraffic/TrafficTableV2/ActionHeader.jsx, app/src/modules/analytics/events/desktopApp/constants.js, app/src/modules/analytics/events/desktopApp/index.js
since we can't know for sure because 
1. it is more about the size of the logs, rather than the number of entries
2. the threshold might be different for machines with different specifications
starting with a tested estimate of 1500 logs. will change later if required
=> chore: show alert when trying to save too many network logs

package-lock.json, package.json
for some reason v1.0.4 was already published on npm even though the changes were not visible in code
=> chore: bump version of requestly-core to v1.0.5

.babelrc, app/package-lock.json, common/constants.js, common/logger.js, common/rule-processor/build.sh, common/rule-processor/package-lock.json, common/rule-processor/package.json, common/rule-processor/src/RuleProcessorFactory.js, common/rule-processor/src/index.ts, common/rule-processor/src/predefinedFunctions.js, common/rule-processor/src/processors/ModifyResponseRuleProcessor.js, common/rule-processor/tests/RuleHelper.spec.js, common/rule-processor/tests/helpers/MockObjects.js, common/rule-processor/tests/processors/DelayRequestRuleProcessor.spec.js, common/rule-processor/tests/processors/HeadersRuleProcessor.spec.js, common/rule-processor/tests/processors/QueryParamsRuleProcessor.spec.js, common/rule-processor/tests/processors/UserAgentRuleProcessor.spec.js, common/rule-processor/webpack.config.js, common/utils.js, index.js, package-lock.json, package.json, rollup.config.js
- had to do this to make it easily importable inside requestly-proxy (esm modules cannot run inside electron renderer)
- supporting PRs to work with this change are:
- https://github.com/requestly/requestly-proxy/pull/52
- https://github.com/requestly/requestly-desktop-app/pull/112
=> feat: bundle requestly-core as both cjs and esm

app/src/components/mode-specific/desktop/MySources/Sources/index.css, app/src/components/mode-specific/desktop/MySources/Sources/index.js
=> fix: android emulator device description was overflowing grid

app/src/components/mode-specific/desktop/MySources/Sources/index.css
https://github.com/requestly/requestly/pull/2237 broke the other tiles so adding a `minmax` to avoid uneven growth of grid columns
=> fix: add threshold to sources grid growth adjustments

app/src/features/apiClient/screens/apiClient/components/clientView/APIClientView.tsx, app/src/features/apiClient/screens/apiClient/utils.ts
Removed auto addition of https:// prefix on input blur and instead adding this if the prefix is not present after resolving the variables in the request URL
=> fix: API client request URL prefix

app/src/hooks/AppModeInitializer.js, app/src/modules/analytics/events/desktopApp/backgroundEvents.ts
UI to set the `active` state for `existing-terminal` based on the event from [these changes](https://github.com/requestly/requestly-desktop-app/pull/118)
=> feat: set existing-terminal as active when receiving event from background

app/src/store/index.js
- Filters added to the top filters in desktop app will be persisted after closing and reopening of the application
- Search bar will also persist the searched query
=> [ENGG-2413]Persist filters in traffic table

app/src/componentsV2/CodeEditor/components/Editor/Editor.tsx, app/src/componentsV2/CodeEditor/types/index.ts
- handle case when the content doesn't match any of the cases that we have handled (HTML/CSS/JS/JSON)
- replace `string.includes` check with a regex mapping
=> Fix api response fullscreen

app/src/features/apiClient/routes.tsx
Changes: 
- No need to handle `/new` env route as this will get handled in `/:envId` route
=> [ENGG-2443] fix: new environment variable route

app/src/features/apiClient/screens/apiClient/components/clientView/components/Scripts/components/ScriptEditor/ScriptEditor.tsx
- If the post-response script is defined, select that by default
- If both are defined, select Pre-Request
=> [ENGG-2511] Fix: Pre-script & post response UI precedence

app/src/features/apiClient/helpers/APIClientManager/index.ts, app/src/features/apiClient/screens/apiClient/components/clientView/APIClientView.tsx
adding context of request and other filterable details in to the explicitly tracked exceptions
=> fix sentry exception tracking in api client: 

app/src/features/apiClient/screens/apiClient/components/clientView/components/request/RequestBody.tsx, app/src/features/apiClient/screens/apiClient/components/clientView/components/request/components/RequestTabs/RequestTabs.tsx, app/src/features/apiClient/screens/apiClient/components/clientView/components/request/renderers/form-body-renderer.tsx, app/src/features/apiClient/screens/apiClient/components/clientView/components/request/renderers/json-body-renderer.tsx, app/src/features/apiClient/screens/apiClient/components/clientView/components/request/renderers/raw-body-renderer.tsx, app/src/features/apiClient/screens/apiClient/components/clientView/components/request/request-body-state-manager.ts, app/src/features/apiClient/screens/apiClient/components/clientView/components/request/request-body-types.ts, app/src/features/apiClient/types.ts
This is a refactor of types, component structure, and capability. We are moving away from `RequestBody` and embracing `RequestBodyContainer` which lets use hold data for different content types.
=> Added support to hold different content types in body

app/src/config/constants/sub/links.js, app/src/features/onboarding/components/auth/components/Form/index.scss, app/src/features/onboarding/components/auth/components/Form/index.tsx
=> ENGG-2809: Add T&C footer in auth modal

app/src/features/apiClient/screens/apiClient/components/clientView/components/request/components/KeyValueTable/KeyValueTable.tsx, app/src/features/apiClient/screens/apiClient/components/clientView/components/request/components/KeyValueTable/KeyValueTableRow.tsx, app/src/features/apiClient/screens/apiClient/components/clientView/components/request/components/RequestTabs/RequestTabs.tsx, app/src/features/apiClient/screens/apiClient/components/clientView/components/request/components/RequestTabs/components/HeadersTable/HeadersTable.tsx, app/src/features/apiClient/screens/apiClient/components/clientView/components/request/components/RequestTabs/components/QueryParamsTable/QueryParamsTable.tsx, app/src/features/apiClient/screens/apiClient/components/clientView/components/request/renderers/form-body-renderer.tsx
The component is currently highly coupled with API requestEntry state
* The table should only accept the `pairs`, `onChange` handler and `variables`
*  Let the respective parent component of KeyValueTable handle the request entry update
* Avoid passing `pairType`  prop,  parent will handle it.
=> [ENGG-2800]: Refactor KeyValueTable component

eligible-student-domains.md
This PR adds [Alfa-College Groningen](https://www.alfa-college.nl/) to the list of eligible domains for the Student Program.
For reference, see chat between user1738327488683 and Sachin on Crisp.
=> Add Alfa-College to eligible-student-domains.md

app/src/features/apiClient/screens/BrunoImporter/index.tsx
https://github.com/requestly/requestly/pull/2732 broke bruno importer, was not making new records for item[type="api"]
=> fix: create api from the repo layer, rather than trying to update it 

app/src/layouts/DashboardLayout/Sidebar/PrimarySidebar/PrimarySidebar.css, app/src/layouts/DashboardLayout/Sidebar/PrimarySidebar/components/InviteButton/InviteButton.tsx, app/src/layouts/DashboardLayout/Sidebar/PrimarySidebar/components/PrimarySidebarLink/PrimarySidebarLink.tsx, app/src/layouts/DashboardLayout/Sidebar/PrimarySidebar/index.tsx
=> ENGG-3251: App primary sidebar UI improvements

app/src/components/mode-specific/desktop/MySources/Sources/InstructionsModal/Android/CertificateDownload.js, app/src/components/mode-specific/desktop/MySources/Sources/InstructionsModal/ExistingBrowser.tsx, app/src/components/mode-specific/desktop/MySources/Sources/InstructionsModal/IOS/CertificateDownload.js, app/src/components/mode-specific/desktop/MySources/Sources/InstructionsModal/common/TestProxy.js, app/src/features/onboarding/components/auth/components/Form/index.tsx
- else was a bug in case of desktop app as the link would then be opened in the current renederer (with no way of going back to the app)
- did not enforce for `mailto` links as they already open the native email client
=> chore: add target to all anchor tags

app/src/components/features/mocksV2/MockEditorIndex/Editor/Header/index.css
=> fix: mock server header buttons UI alignment

app/src/views/features/rules/RuleEditor/components/Header/RuleEditorHeader.css
=> [ENGG-3400] fix: editor buttons overflowing

eligible-student-domains.md
This PR adds a new entry to the list found at [eligible-student-domains.md](https://github.com/requestly/requestly/blob/master/eligible-student-domains.md) that should cover most academic institutions in Albania, and allow their studends access to the [Requestly Student Program](https://requestly.com/student-program/).
Changes proposed:
- Added the academic TLD `.edu.al` to the list of eligible student domains.
=> Add .edu.al to eligible domains list for students plan

app/src/backend/billing/hooks/useBillingTeamsListener.ts
- `useBillingTeamListener` was overriding the user attribute value written by `AuthHandler`. AuthHandler should be the source of truth
=> fix: rq_subscription_type attribute

app/src/store/features/rulesActions.ts
- This PR tends to solve the issue of the sample script rule's data being corrupted by the `<script>` tag artifacts being added. 
- This is was a brittle system, that was made robust by adding the validation very closely to the record saving methods.
- The `updateRulePairAtGivenPath` action is being called even for sample rules. 
- Updates made via sample rules form deviations in the UX and the steps to be followed to save the rule.
- This needs to be solved wholistically later. But is leading to silent regressions (like the one stated above) and I guess also the issue [this PR](https://github.com/requestly/requestly/pull/2929) intends to fix as well
=> fix: block updates to sample rule

browser-extension/common/src/popup/components/Popup/index.tsx, browser-extension/mv3/src/service-worker/services/contextMenu.ts, browser-extension/mv3/src/service-worker/services/extensionIconManager.ts, browser-extension/mv3/src/service-worker/services/messageHandler/listener.ts, browser-extension/mv3/src/service-worker/services/utils.ts
1. Added debug logs
2. Removed the listener to handle extension activation status otherwise errors were not being captured
=> [ENGG-3627] added debug logs when toggling extension status

app/src/features/pricing/constants/pricingFeatures.ts
Changelog:
- Changed 5 Files to 5 Files (JS / CSS)
- Added a separate line-entry for 5 API Mock Endpoints (above 5 files)
- Similarly, Unlimited Files should be splited into two entries 
- Unlimited Files (JS, CSS)
- Unlimited Mock endpoints
- Add Unlimited Groups in Professional Plan
In Page:
In modal:
=> [ENGG-3683] fix: update pricing page copies

app/src/features/apiClient/screens/apiClient/components/clientView/components/request/components/AuthorizationView/AuthorizationForm/hooks/useAuthFormState.ts
Reason:
- so far the initial value for the form in `AuthorizationView` was calculated based on the `currentAuthType` in the `defaultAuth` (`defaultAuth` is the auth stored in the backend/store)
- So `defaultAuth` isn't updated when we change `AuthType` in the form because that would first need us to `Save` the changes -> **Reason No.1**
- `formState` of the form was not being recalculated for when `formType` is updated  -> **Reason No.2**
Solution:
1. update `getDefaultFormState` to use the authType from `formType` and not from the one stored in `defaultAuth`
2. add a useEffect that updates `formState` (adds new defaults) when `formType` is changed
=> fix: reset default formstate when formType is changed

app/src/features/apiClient/screens/apiClient/components/clientView/components/request/components/AuthorizationView/types/AuthConfig.ts
auth configs are invalid if empty string or nullish or not complete
=> fix: auth config validations

app/src/views/features/rules/RuleEditor/components/Header/ActionButtons/CreateRuleButton/actions/index.js
Headers names can only contain:
- Letters (A-Z, a-z)
- Digits (0-9)
- Hyphens (-)
- underscore (_)
=> [ENGG-3814] added header name validation for header rule
